// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ClockTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "ClockTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Clock.hpp"

#include "builtin_interfaces/msg/Time.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace rosgraph_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Clock_type_identifier(
        TypeIdentifierPair& type_ids_Clock)
{

    ReturnCode_t return_code_Clock {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Clock =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "rosgraph_msgs::msg::dds_::Clock_", type_ids_Clock);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Clock)
    {
        StructTypeFlag struct_flags_Clock = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Clock = "rosgraph_msgs::msg::dds_::Clock_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Clock;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Clock;
        AppliedAnnotationSeq tmp_ann_custom_Clock;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_Clock;
        PlacementKind placement_Clock = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_Clock = "*";
        std::string text_Clock;
        language_Clock = "comment";

        placement_Clock = PlacementKind::BEFORE_DECLARATION;

        text_Clock = "This message communicates the current time.\n\nFor more information, see https://design.ros2.org/articles/clock_and_time.html.";

        verbatim_Clock = TypeObjectUtils::build_applied_verbatim_annotation(placement_Clock, language_Clock, text_Clock);
        type_ann_builtin_Clock = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_Clock);

        if (!tmp_ann_custom_Clock.empty())
        {
            ann_custom_Clock = tmp_ann_custom_Clock;
        }

        CompleteTypeDetail detail_Clock = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Clock, ann_custom_Clock, type_name_Clock.to_string());
        CompleteStructHeader header_Clock;
        header_Clock = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Clock);
        CompleteStructMemberSeq member_seq_Clock;
        {
            TypeIdentifierPair type_ids_clock;
            ReturnCode_t return_code_clock {eprosima::fastdds::dds::RETCODE_OK};
            return_code_clock =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "builtin_interfaces::msg::dds_::Time_", type_ids_clock);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_clock)
            {
                builtin_interfaces::msg::register_Time_type_identifier(type_ids_clock);
            }
            StructMemberFlag member_flags_clock = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_clock = 0x00000000;
            bool common_clock_ec {false};
            CommonStructMember common_clock {TypeObjectUtils::build_common_struct_member(member_id_clock, member_flags_clock, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_clock, common_clock_ec))};
            if (!common_clock_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure clock member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_clock = "clock";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_clock;
            ann_custom_Clock.reset();
            CompleteMemberDetail detail_clock = TypeObjectUtils::build_complete_member_detail(name_clock, member_ann_builtin_clock, ann_custom_Clock);
            CompleteStructMember member_clock = TypeObjectUtils::build_complete_struct_member(common_clock, detail_clock);
            TypeObjectUtils::add_complete_struct_member(member_seq_Clock, member_clock);
        }
        CompleteStructType struct_type_Clock = TypeObjectUtils::build_complete_struct_type(struct_flags_Clock, header_Clock, member_seq_Clock);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Clock, type_name_Clock.to_string(), type_ids_Clock))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "rosgraph_msgs::msg::Clock already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace rosgraph_msgs

