// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SetEpisodeSettingsPubSubTypes.hpp
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */


#ifndef FAST_DDS_GENERATED__CARLA_MSGS_SRV_SETEPISODESETTINGS_PUBSUBTYPES_HPP
#define FAST_DDS_GENERATED__CARLA_MSGS_SRV_SETEPISODESETTINGS_PUBSUBTYPES_HPP

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>
#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>

#include "SetEpisodeSettings.hpp"

#include "carla_msgs/msg/CarlaEpisodeSettingsPubSubTypes.hpp"

#if !defined(FASTDDS_GEN_API_VER) || (FASTDDS_GEN_API_VER != 3)
#error \
    Generated SetEpisodeSettings is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // FASTDDS_GEN_API_VER

namespace carla_msgs
{
    namespace srv
    {

        #ifndef SWIG
        namespace detail {

        template<typename Tag, typename Tag::type M>
        struct SetEpisodeSettings_Request_rob
        {
            friend constexpr typename Tag::type get(
                    Tag)
            {
                return M;
            }

        };

        struct SetEpisodeSettings_Request_f
        {
            typedef carla_msgs::msg::CarlaEpisodeSettings SetEpisodeSettings_Request::* type;
            friend constexpr type get(
                    SetEpisodeSettings_Request_f);
        };

        template struct SetEpisodeSettings_Request_rob<SetEpisodeSettings_Request_f, &SetEpisodeSettings_Request::m_episode_settings>;

        template <typename T, typename Tag>
        inline size_t constexpr SetEpisodeSettings_Request_offset_of()
        {
            return ((::size_t) &reinterpret_cast<char const volatile&>((((T*)0)->*get(Tag()))));
        }

        } // namespace detail
        #endif // ifndef SWIG


        /*!
         * @brief This class represents the TopicDataType of the type SetEpisodeSettings_Request defined by the user in the IDL file.
         * @ingroup SetEpisodeSettings
         */
        class SetEpisodeSettings_RequestPubSubType : public eprosima::fastdds::dds::TopicDataType
        {
        public:

            typedef SetEpisodeSettings_Request type;

            eProsima_user_DllExport SetEpisodeSettings_RequestPubSubType();

            eProsima_user_DllExport ~SetEpisodeSettings_RequestPubSubType() override;

            eProsima_user_DllExport bool serialize(
                    const void* const data,
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

            eProsima_user_DllExport bool deserialize(
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    void* data) override;

            eProsima_user_DllExport uint32_t calculate_serialized_size(
                    const void* const data,
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

            eProsima_user_DllExport bool compute_key(
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
                    bool force_md5 = false) override;

            eProsima_user_DllExport bool compute_key(
                    const void* const data,
                    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
                    bool force_md5 = false) override;

            eProsima_user_DllExport void* create_data() override;

            eProsima_user_DllExport void delete_data(
                    void* data) override;

            //Register TypeObject representation in Fast DDS TypeObjectRegistry
            eProsima_user_DllExport void register_type_object_representation() override;

        #ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
            eProsima_user_DllExport inline bool is_bounded() const override
            {
                return true;
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

        #ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

            eProsima_user_DllExport inline bool is_plain(
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
            {
                if (data_representation == eprosima::fastdds::dds::DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)
                {
                    return is_plain_xcdrv2_impl();
                }
                else
                {
                    return is_plain_xcdrv1_impl();
                }
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

        #ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
            eProsima_user_DllExport inline bool construct_sample(
                    void* memory) const override
            {
                new (memory) SetEpisodeSettings_Request();
                return true;
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

        private:

            eprosima::fastdds::MD5 md5_;
            unsigned char* key_buffer_;


            static constexpr bool is_plain_xcdrv1_impl()
            {
                return 53ULL ==
                       (detail::SetEpisodeSettings_Request_offset_of<SetEpisodeSettings_Request, detail::SetEpisodeSettings_Request_f>() +
                       sizeof(carla_msgs::msg::CarlaEpisodeSettings));
            }

            static constexpr bool is_plain_xcdrv2_impl()
            {
                return 45ULL ==
                       (detail::SetEpisodeSettings_Request_offset_of<SetEpisodeSettings_Request, detail::SetEpisodeSettings_Request_f>() +
                       sizeof(carla_msgs::msg::CarlaEpisodeSettings));
            }

        };

        #ifndef SWIG
        namespace detail {

        template<typename Tag, typename Tag::type M>
        struct SetEpisodeSettings_Response_rob
        {
            friend constexpr typename Tag::type get(
                    Tag)
            {
                return M;
            }

        };

        struct SetEpisodeSettings_Response_f
        {
            typedef bool SetEpisodeSettings_Response::* type;
            friend constexpr type get(
                    SetEpisodeSettings_Response_f);
        };

        template struct SetEpisodeSettings_Response_rob<SetEpisodeSettings_Response_f, &SetEpisodeSettings_Response::m_success>;

        template <typename T, typename Tag>
        inline size_t constexpr SetEpisodeSettings_Response_offset_of()
        {
            return ((::size_t) &reinterpret_cast<char const volatile&>((((T*)0)->*get(Tag()))));
        }

        } // namespace detail
        #endif // ifndef SWIG


        /*!
         * @brief This class represents the TopicDataType of the type SetEpisodeSettings_Response defined by the user in the IDL file.
         * @ingroup SetEpisodeSettings
         */
        class SetEpisodeSettings_ResponsePubSubType : public eprosima::fastdds::dds::TopicDataType
        {
        public:

            typedef SetEpisodeSettings_Response type;

            eProsima_user_DllExport SetEpisodeSettings_ResponsePubSubType();

            eProsima_user_DllExport ~SetEpisodeSettings_ResponsePubSubType() override;

            eProsima_user_DllExport bool serialize(
                    const void* const data,
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

            eProsima_user_DllExport bool deserialize(
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    void* data) override;

            eProsima_user_DllExport uint32_t calculate_serialized_size(
                    const void* const data,
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

            eProsima_user_DllExport bool compute_key(
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
                    bool force_md5 = false) override;

            eProsima_user_DllExport bool compute_key(
                    const void* const data,
                    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
                    bool force_md5 = false) override;

            eProsima_user_DllExport void* create_data() override;

            eProsima_user_DllExport void delete_data(
                    void* data) override;

            //Register TypeObject representation in Fast DDS TypeObjectRegistry
            eProsima_user_DllExport void register_type_object_representation() override;

        #ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
            eProsima_user_DllExport inline bool is_bounded() const override
            {
                return true;
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

        #ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

            eProsima_user_DllExport inline bool is_plain(
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
            {
                if (data_representation == eprosima::fastdds::dds::DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)
                {
                    return is_plain_xcdrv2_impl();
                }
                else
                {
                    return is_plain_xcdrv1_impl();
                }
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

        #ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
            eProsima_user_DllExport inline bool construct_sample(
                    void* memory) const override
            {
                new (memory) SetEpisodeSettings_Response();
                return true;
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

        private:

            eprosima::fastdds::MD5 md5_;
            unsigned char* key_buffer_;


            static constexpr bool is_plain_xcdrv1_impl()
            {
                return 1ULL ==
                       (detail::SetEpisodeSettings_Response_offset_of<SetEpisodeSettings_Response, detail::SetEpisodeSettings_Response_f>() +
                       sizeof(bool));
            }

            static constexpr bool is_plain_xcdrv2_impl()
            {
                return 1ULL ==
                       (detail::SetEpisodeSettings_Response_offset_of<SetEpisodeSettings_Response, detail::SetEpisodeSettings_Response_f>() +
                       sizeof(bool));
            }

        };
    } // namespace srv
} // namespace carla_msgs

#endif // FAST_DDS_GENERATED__CARLA_MSGS_SRV_SETEPISODESETTINGS_PUBSUBTYPES_HPP

