// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SpawnObjectTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "SpawnObjectTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "SpawnObject.hpp"

#include "carla_msgs/msg/CarlaActorBlueprint.hpp"
#include "geometry_msgs/msg/Pose.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace carla_msgs {
namespace srv {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_SpawnObject_Request_type_identifier(
        TypeIdentifierPair& type_ids_SpawnObject_Request)
{

    ReturnCode_t return_code_SpawnObject_Request {eprosima::fastdds::dds::RETCODE_OK};
    return_code_SpawnObject_Request =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "carla_msgs::srv::dds_::SpawnObject_Request_", type_ids_SpawnObject_Request);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_SpawnObject_Request)
    {
        StructTypeFlag struct_flags_SpawnObject_Request = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_SpawnObject_Request = "carla_msgs::srv::dds_::SpawnObject_Request_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_SpawnObject_Request;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_SpawnObject_Request;
        AppliedAnnotationSeq tmp_ann_custom_SpawnObject_Request;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_SpawnObject_Request;
        PlacementKind placement_SpawnObject_Request = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_SpawnObject_Request = "*";
        std::string text_SpawnObject_Request;
        language_SpawnObject_Request = "comment";

        placement_SpawnObject_Request = PlacementKind::BEFORE_DECLARATION;

        text_SpawnObject_Request = "Copyright (c) 2020 Intel Corporation.\n\nThis work is licensed under the terms of the MIT license.\nFor a copy, see <https://opensource.org/licenses/MIT>.";

        verbatim_SpawnObject_Request = TypeObjectUtils::build_applied_verbatim_annotation(placement_SpawnObject_Request, language_SpawnObject_Request, text_SpawnObject_Request);
        type_ann_builtin_SpawnObject_Request = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_SpawnObject_Request);

        if (!tmp_ann_custom_SpawnObject_Request.empty())
        {
            ann_custom_SpawnObject_Request = tmp_ann_custom_SpawnObject_Request;
        }

        CompleteTypeDetail detail_SpawnObject_Request = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_SpawnObject_Request, ann_custom_SpawnObject_Request, type_name_SpawnObject_Request.to_string());
        CompleteStructHeader header_SpawnObject_Request;
        header_SpawnObject_Request = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_SpawnObject_Request);
        CompleteStructMemberSeq member_seq_SpawnObject_Request;
        {
            TypeIdentifierPair type_ids_blueprint;
            ReturnCode_t return_code_blueprint {eprosima::fastdds::dds::RETCODE_OK};
            return_code_blueprint =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "carla_msgs::msg::dds_::CarlaActorBlueprint_", type_ids_blueprint);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_blueprint)
            {
                carla_msgs::msg::register_CarlaActorBlueprint_type_identifier(type_ids_blueprint);
            }
            StructMemberFlag member_flags_blueprint = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_blueprint = 0x00000000;
            bool common_blueprint_ec {false};
            CommonStructMember common_blueprint {TypeObjectUtils::build_common_struct_member(member_id_blueprint, member_flags_blueprint, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_blueprint, common_blueprint_ec))};
            if (!common_blueprint_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure blueprint member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_blueprint = "blueprint";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_blueprint;
            ann_custom_SpawnObject_Request.reset();
            CompleteMemberDetail detail_blueprint = TypeObjectUtils::build_complete_member_detail(name_blueprint, member_ann_builtin_blueprint, ann_custom_SpawnObject_Request);
            CompleteStructMember member_blueprint = TypeObjectUtils::build_complete_struct_member(common_blueprint, detail_blueprint);
            TypeObjectUtils::add_complete_struct_member(member_seq_SpawnObject_Request, member_blueprint);
        }
        {
            TypeIdentifierPair type_ids_transform;
            ReturnCode_t return_code_transform {eprosima::fastdds::dds::RETCODE_OK};
            return_code_transform =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::Pose_", type_ids_transform);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_transform)
            {
                geometry_msgs::msg::register_Pose_type_identifier(type_ids_transform);
            }
            StructMemberFlag member_flags_transform = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_transform = 0x00000001;
            bool common_transform_ec {false};
            CommonStructMember common_transform {TypeObjectUtils::build_common_struct_member(member_id_transform, member_flags_transform, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_transform, common_transform_ec))};
            if (!common_transform_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure transform member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_transform = "transform";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_transform;
            ann_custom_SpawnObject_Request.reset();
            CompleteMemberDetail detail_transform = TypeObjectUtils::build_complete_member_detail(name_transform, member_ann_builtin_transform, ann_custom_SpawnObject_Request);
            CompleteStructMember member_transform = TypeObjectUtils::build_complete_struct_member(common_transform, detail_transform);
            TypeObjectUtils::add_complete_struct_member(member_seq_SpawnObject_Request, member_transform);
        }
        {
            TypeIdentifierPair type_ids_attach_to;
            ReturnCode_t return_code_attach_to {eprosima::fastdds::dds::RETCODE_OK};
            return_code_attach_to =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_attach_to);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_attach_to)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "attach_to Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_attach_to = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_attach_to = 0x00000002;
            bool common_attach_to_ec {false};
            CommonStructMember common_attach_to {TypeObjectUtils::build_common_struct_member(member_id_attach_to, member_flags_attach_to, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_attach_to, common_attach_to_ec))};
            if (!common_attach_to_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure attach_to member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_attach_to = "attach_to";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_attach_to;
            ann_custom_SpawnObject_Request.reset();
            CompleteMemberDetail detail_attach_to = TypeObjectUtils::build_complete_member_detail(name_attach_to, member_ann_builtin_attach_to, ann_custom_SpawnObject_Request);
            CompleteStructMember member_attach_to = TypeObjectUtils::build_complete_struct_member(common_attach_to, detail_attach_to);
            TypeObjectUtils::add_complete_struct_member(member_seq_SpawnObject_Request, member_attach_to);
        }
        {
            TypeIdentifierPair type_ids_random_pose;
            ReturnCode_t return_code_random_pose {eprosima::fastdds::dds::RETCODE_OK};
            return_code_random_pose =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_random_pose);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_random_pose)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "random_pose Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_random_pose = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_random_pose = 0x00000003;
            bool common_random_pose_ec {false};
            CommonStructMember common_random_pose {TypeObjectUtils::build_common_struct_member(member_id_random_pose, member_flags_random_pose, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_random_pose, common_random_pose_ec))};
            if (!common_random_pose_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure random_pose member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_random_pose = "random_pose";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_random_pose;
            ann_custom_SpawnObject_Request.reset();
            CompleteMemberDetail detail_random_pose = TypeObjectUtils::build_complete_member_detail(name_random_pose, member_ann_builtin_random_pose, ann_custom_SpawnObject_Request);
            CompleteStructMember member_random_pose = TypeObjectUtils::build_complete_struct_member(common_random_pose, detail_random_pose);
            TypeObjectUtils::add_complete_struct_member(member_seq_SpawnObject_Request, member_random_pose);
        }
        CompleteStructType struct_type_SpawnObject_Request = TypeObjectUtils::build_complete_struct_type(struct_flags_SpawnObject_Request, header_SpawnObject_Request, member_seq_SpawnObject_Request);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_SpawnObject_Request, type_name_SpawnObject_Request.to_string(), type_ids_SpawnObject_Request))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "carla_msgs::srv::SpawnObject_Request already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_SpawnObject_Response_type_identifier(
        TypeIdentifierPair& type_ids_SpawnObject_Response)
{

    ReturnCode_t return_code_SpawnObject_Response {eprosima::fastdds::dds::RETCODE_OK};
    return_code_SpawnObject_Response =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "carla_msgs::srv::dds_::SpawnObject_Response_", type_ids_SpawnObject_Response);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_SpawnObject_Response)
    {
        StructTypeFlag struct_flags_SpawnObject_Response = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_SpawnObject_Response = "carla_msgs::srv::dds_::SpawnObject_Response_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_SpawnObject_Response;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_SpawnObject_Response;
        CompleteTypeDetail detail_SpawnObject_Response = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_SpawnObject_Response, ann_custom_SpawnObject_Response, type_name_SpawnObject_Response.to_string());
        CompleteStructHeader header_SpawnObject_Response;
        header_SpawnObject_Response = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_SpawnObject_Response);
        CompleteStructMemberSeq member_seq_SpawnObject_Response;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_SpawnObject_Response.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_SpawnObject_Response);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_SpawnObject_Response, member_id);
        }
        {
            TypeIdentifierPair type_ids_error_string;
            ReturnCode_t return_code_error_string {eprosima::fastdds::dds::RETCODE_OK};
            return_code_error_string =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_error_string);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_error_string)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_error_string))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_error_string = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_error_string = 0x00000001;
            bool common_error_string_ec {false};
            CommonStructMember common_error_string {TypeObjectUtils::build_common_struct_member(member_id_error_string, member_flags_error_string, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_error_string, common_error_string_ec))};
            if (!common_error_string_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure error_string member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_error_string = "error_string";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_error_string;
            ann_custom_SpawnObject_Response.reset();
            CompleteMemberDetail detail_error_string = TypeObjectUtils::build_complete_member_detail(name_error_string, member_ann_builtin_error_string, ann_custom_SpawnObject_Response);
            CompleteStructMember member_error_string = TypeObjectUtils::build_complete_struct_member(common_error_string, detail_error_string);
            TypeObjectUtils::add_complete_struct_member(member_seq_SpawnObject_Response, member_error_string);
        }
        CompleteStructType struct_type_SpawnObject_Response = TypeObjectUtils::build_complete_struct_type(struct_flags_SpawnObject_Response, header_SpawnObject_Response, member_seq_SpawnObject_Response);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_SpawnObject_Response, type_name_SpawnObject_Response.to_string(), type_ids_SpawnObject_Response))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "carla_msgs::srv::SpawnObject_Response already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace srv

} // namespace carla_msgs

