// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaEgoVehicleTelemetryDataWheelTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "CarlaEgoVehicleTelemetryDataWheelTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "CarlaEgoVehicleTelemetryDataWheel.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace carla_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_CarlaEgoVehicleTelemetryDataWheel_type_identifier(
        TypeIdentifierPair& type_ids_CarlaEgoVehicleTelemetryDataWheel)
{

    ReturnCode_t return_code_CarlaEgoVehicleTelemetryDataWheel {eprosima::fastdds::dds::RETCODE_OK};
    return_code_CarlaEgoVehicleTelemetryDataWheel =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "carla_msgs::msg::dds_::CarlaEgoVehicleTelemetryDataWheel_", type_ids_CarlaEgoVehicleTelemetryDataWheel);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_CarlaEgoVehicleTelemetryDataWheel)
    {
        StructTypeFlag struct_flags_CarlaEgoVehicleTelemetryDataWheel = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_CarlaEgoVehicleTelemetryDataWheel = "carla_msgs::msg::dds_::CarlaEgoVehicleTelemetryDataWheel_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_CarlaEgoVehicleTelemetryDataWheel;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_CarlaEgoVehicleTelemetryDataWheel;
        AppliedAnnotationSeq tmp_ann_custom_CarlaEgoVehicleTelemetryDataWheel;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_CarlaEgoVehicleTelemetryDataWheel;
        PlacementKind placement_CarlaEgoVehicleTelemetryDataWheel = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_CarlaEgoVehicleTelemetryDataWheel = "*";
        std::string text_CarlaEgoVehicleTelemetryDataWheel;
        language_CarlaEgoVehicleTelemetryDataWheel = "comment";

        placement_CarlaEgoVehicleTelemetryDataWheel = PlacementKind::BEFORE_DECLARATION;

        text_CarlaEgoVehicleTelemetryDataWheel = "This work is licensed under the terms of the MIT license.\nFor a copy, see <https://opensource.org/licenses/MIT>.";

        verbatim_CarlaEgoVehicleTelemetryDataWheel = TypeObjectUtils::build_applied_verbatim_annotation(placement_CarlaEgoVehicleTelemetryDataWheel, language_CarlaEgoVehicleTelemetryDataWheel, text_CarlaEgoVehicleTelemetryDataWheel);
        type_ann_builtin_CarlaEgoVehicleTelemetryDataWheel = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_CarlaEgoVehicleTelemetryDataWheel);

        if (!tmp_ann_custom_CarlaEgoVehicleTelemetryDataWheel.empty())
        {
            ann_custom_CarlaEgoVehicleTelemetryDataWheel = tmp_ann_custom_CarlaEgoVehicleTelemetryDataWheel;
        }

        CompleteTypeDetail detail_CarlaEgoVehicleTelemetryDataWheel = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_CarlaEgoVehicleTelemetryDataWheel, ann_custom_CarlaEgoVehicleTelemetryDataWheel, type_name_CarlaEgoVehicleTelemetryDataWheel.to_string());
        CompleteStructHeader header_CarlaEgoVehicleTelemetryDataWheel;
        header_CarlaEgoVehicleTelemetryDataWheel = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_CarlaEgoVehicleTelemetryDataWheel);
        CompleteStructMemberSeq member_seq_CarlaEgoVehicleTelemetryDataWheel;
        {
            TypeIdentifierPair type_ids_tire_friction;
            ReturnCode_t return_code_tire_friction {eprosima::fastdds::dds::RETCODE_OK};
            return_code_tire_friction =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_tire_friction);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_tire_friction)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "tire_friction Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_tire_friction = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_tire_friction = 0x00000000;
            bool common_tire_friction_ec {false};
            CommonStructMember common_tire_friction {TypeObjectUtils::build_common_struct_member(member_id_tire_friction, member_flags_tire_friction, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_tire_friction, common_tire_friction_ec))};
            if (!common_tire_friction_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure tire_friction member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_tire_friction = "tire_friction";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_tire_friction;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_tire_friction = TypeObjectUtils::build_complete_member_detail(name_tire_friction, member_ann_builtin_tire_friction, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_tire_friction = TypeObjectUtils::build_complete_struct_member(common_tire_friction, detail_tire_friction);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_tire_friction);
        }
        {
            TypeIdentifierPair type_ids_lat_slip;
            ReturnCode_t return_code_lat_slip {eprosima::fastdds::dds::RETCODE_OK};
            return_code_lat_slip =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_lat_slip);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_lat_slip)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "lat_slip Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_lat_slip = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_lat_slip = 0x00000001;
            bool common_lat_slip_ec {false};
            CommonStructMember common_lat_slip {TypeObjectUtils::build_common_struct_member(member_id_lat_slip, member_flags_lat_slip, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_lat_slip, common_lat_slip_ec))};
            if (!common_lat_slip_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure lat_slip member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_lat_slip = "lat_slip";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_lat_slip;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_lat_slip = TypeObjectUtils::build_complete_member_detail(name_lat_slip, member_ann_builtin_lat_slip, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_lat_slip = TypeObjectUtils::build_complete_struct_member(common_lat_slip, detail_lat_slip);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_lat_slip);
        }
        {
            TypeIdentifierPair type_ids_long_slip;
            ReturnCode_t return_code_long_slip {eprosima::fastdds::dds::RETCODE_OK};
            return_code_long_slip =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_long_slip);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_long_slip)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "long_slip Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_long_slip = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_long_slip = 0x00000002;
            bool common_long_slip_ec {false};
            CommonStructMember common_long_slip {TypeObjectUtils::build_common_struct_member(member_id_long_slip, member_flags_long_slip, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_long_slip, common_long_slip_ec))};
            if (!common_long_slip_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure long_slip member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_long_slip = "long_slip";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_long_slip;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_long_slip = TypeObjectUtils::build_complete_member_detail(name_long_slip, member_ann_builtin_long_slip, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_long_slip = TypeObjectUtils::build_complete_struct_member(common_long_slip, detail_long_slip);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_long_slip);
        }
        {
            TypeIdentifierPair type_ids_omega;
            ReturnCode_t return_code_omega {eprosima::fastdds::dds::RETCODE_OK};
            return_code_omega =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_omega);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_omega)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "omega Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_omega = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_omega = 0x00000003;
            bool common_omega_ec {false};
            CommonStructMember common_omega {TypeObjectUtils::build_common_struct_member(member_id_omega, member_flags_omega, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_omega, common_omega_ec))};
            if (!common_omega_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure omega member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_omega = "omega";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_omega;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_omega = TypeObjectUtils::build_complete_member_detail(name_omega, member_ann_builtin_omega, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_omega = TypeObjectUtils::build_complete_struct_member(common_omega, detail_omega);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_omega);
        }
        {
            TypeIdentifierPair type_ids_tire_load;
            ReturnCode_t return_code_tire_load {eprosima::fastdds::dds::RETCODE_OK};
            return_code_tire_load =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_tire_load);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_tire_load)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "tire_load Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_tire_load = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_tire_load = 0x00000004;
            bool common_tire_load_ec {false};
            CommonStructMember common_tire_load {TypeObjectUtils::build_common_struct_member(member_id_tire_load, member_flags_tire_load, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_tire_load, common_tire_load_ec))};
            if (!common_tire_load_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure tire_load member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_tire_load = "tire_load";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_tire_load;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_tire_load = TypeObjectUtils::build_complete_member_detail(name_tire_load, member_ann_builtin_tire_load, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_tire_load = TypeObjectUtils::build_complete_struct_member(common_tire_load, detail_tire_load);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_tire_load);
        }
        {
            TypeIdentifierPair type_ids_normalized_tire_load;
            ReturnCode_t return_code_normalized_tire_load {eprosima::fastdds::dds::RETCODE_OK};
            return_code_normalized_tire_load =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_normalized_tire_load);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_normalized_tire_load)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "normalized_tire_load Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_normalized_tire_load = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_normalized_tire_load = 0x00000005;
            bool common_normalized_tire_load_ec {false};
            CommonStructMember common_normalized_tire_load {TypeObjectUtils::build_common_struct_member(member_id_normalized_tire_load, member_flags_normalized_tire_load, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_normalized_tire_load, common_normalized_tire_load_ec))};
            if (!common_normalized_tire_load_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure normalized_tire_load member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_normalized_tire_load = "normalized_tire_load";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_normalized_tire_load;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_normalized_tire_load = TypeObjectUtils::build_complete_member_detail(name_normalized_tire_load, member_ann_builtin_normalized_tire_load, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_normalized_tire_load = TypeObjectUtils::build_complete_struct_member(common_normalized_tire_load, detail_normalized_tire_load);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_normalized_tire_load);
        }
        {
            TypeIdentifierPair type_ids_torque;
            ReturnCode_t return_code_torque {eprosima::fastdds::dds::RETCODE_OK};
            return_code_torque =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_torque);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "torque Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_torque = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_torque = 0x00000006;
            bool common_torque_ec {false};
            CommonStructMember common_torque {TypeObjectUtils::build_common_struct_member(member_id_torque, member_flags_torque, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque, common_torque_ec))};
            if (!common_torque_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure torque member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_torque = "torque";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_torque;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_torque = TypeObjectUtils::build_complete_member_detail(name_torque, member_ann_builtin_torque, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_torque = TypeObjectUtils::build_complete_struct_member(common_torque, detail_torque);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_torque);
        }
        {
            TypeIdentifierPair type_ids_long_force;
            ReturnCode_t return_code_long_force {eprosima::fastdds::dds::RETCODE_OK};
            return_code_long_force =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_long_force);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_long_force)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "long_force Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_long_force = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_long_force = 0x00000007;
            bool common_long_force_ec {false};
            CommonStructMember common_long_force {TypeObjectUtils::build_common_struct_member(member_id_long_force, member_flags_long_force, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_long_force, common_long_force_ec))};
            if (!common_long_force_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure long_force member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_long_force = "long_force";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_long_force;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_long_force = TypeObjectUtils::build_complete_member_detail(name_long_force, member_ann_builtin_long_force, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_long_force = TypeObjectUtils::build_complete_struct_member(common_long_force, detail_long_force);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_long_force);
        }
        {
            TypeIdentifierPair type_ids_lat_force;
            ReturnCode_t return_code_lat_force {eprosima::fastdds::dds::RETCODE_OK};
            return_code_lat_force =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_lat_force);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_lat_force)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "lat_force Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_lat_force = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_lat_force = 0x00000008;
            bool common_lat_force_ec {false};
            CommonStructMember common_lat_force {TypeObjectUtils::build_common_struct_member(member_id_lat_force, member_flags_lat_force, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_lat_force, common_lat_force_ec))};
            if (!common_lat_force_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure lat_force member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_lat_force = "lat_force";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_lat_force;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_lat_force = TypeObjectUtils::build_complete_member_detail(name_lat_force, member_ann_builtin_lat_force, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_lat_force = TypeObjectUtils::build_complete_struct_member(common_lat_force, detail_lat_force);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_lat_force);
        }
        {
            TypeIdentifierPair type_ids_normalized_long_force;
            ReturnCode_t return_code_normalized_long_force {eprosima::fastdds::dds::RETCODE_OK};
            return_code_normalized_long_force =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_normalized_long_force);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_normalized_long_force)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "normalized_long_force Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_normalized_long_force = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_normalized_long_force = 0x00000009;
            bool common_normalized_long_force_ec {false};
            CommonStructMember common_normalized_long_force {TypeObjectUtils::build_common_struct_member(member_id_normalized_long_force, member_flags_normalized_long_force, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_normalized_long_force, common_normalized_long_force_ec))};
            if (!common_normalized_long_force_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure normalized_long_force member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_normalized_long_force = "normalized_long_force";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_normalized_long_force;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_normalized_long_force = TypeObjectUtils::build_complete_member_detail(name_normalized_long_force, member_ann_builtin_normalized_long_force, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_normalized_long_force = TypeObjectUtils::build_complete_struct_member(common_normalized_long_force, detail_normalized_long_force);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_normalized_long_force);
        }
        {
            TypeIdentifierPair type_ids_normalized_lat_force;
            ReturnCode_t return_code_normalized_lat_force {eprosima::fastdds::dds::RETCODE_OK};
            return_code_normalized_lat_force =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_normalized_lat_force);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_normalized_lat_force)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "normalized_lat_force Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_normalized_lat_force = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_normalized_lat_force = 0x0000000a;
            bool common_normalized_lat_force_ec {false};
            CommonStructMember common_normalized_lat_force {TypeObjectUtils::build_common_struct_member(member_id_normalized_lat_force, member_flags_normalized_lat_force, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_normalized_lat_force, common_normalized_lat_force_ec))};
            if (!common_normalized_lat_force_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure normalized_lat_force member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_normalized_lat_force = "normalized_lat_force";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_normalized_lat_force;
            ann_custom_CarlaEgoVehicleTelemetryDataWheel.reset();
            CompleteMemberDetail detail_normalized_lat_force = TypeObjectUtils::build_complete_member_detail(name_normalized_lat_force, member_ann_builtin_normalized_lat_force, ann_custom_CarlaEgoVehicleTelemetryDataWheel);
            CompleteStructMember member_normalized_lat_force = TypeObjectUtils::build_complete_struct_member(common_normalized_lat_force, detail_normalized_lat_force);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryDataWheel, member_normalized_lat_force);
        }
        CompleteStructType struct_type_CarlaEgoVehicleTelemetryDataWheel = TypeObjectUtils::build_complete_struct_type(struct_flags_CarlaEgoVehicleTelemetryDataWheel, header_CarlaEgoVehicleTelemetryDataWheel, member_seq_CarlaEgoVehicleTelemetryDataWheel);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_CarlaEgoVehicleTelemetryDataWheel, type_name_CarlaEgoVehicleTelemetryDataWheel.to_string(), type_ids_CarlaEgoVehicleTelemetryDataWheel))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "carla_msgs::msg::CarlaEgoVehicleTelemetryDataWheel already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace carla_msgs

