// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaTrafficLightStatusList.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLATRAFFICLIGHTSTATUSLIST_HPP
#define FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLATRAFFICLIGHTSTATUSLIST_HPP

#include <cstdint>
#include <utility>
#include <vector>

#include "CarlaTrafficLightStatus.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CARLATRAFFICLIGHTSTATUSLIST_SOURCE)
#define CARLATRAFFICLIGHTSTATUSLIST_DllAPI __declspec( dllexport )
#else
#define CARLATRAFFICLIGHTSTATUSLIST_DllAPI __declspec( dllimport )
#endif // CARLATRAFFICLIGHTSTATUSLIST_SOURCE
#else
#define CARLATRAFFICLIGHTSTATUSLIST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CARLATRAFFICLIGHTSTATUSLIST_DllAPI
#endif // _WIN32

namespace carla_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CarlaTrafficLightStatusList defined by the user in the IDL file.
 * @ingroup CarlaTrafficLightStatusList
 */
class CarlaTrafficLightStatusList
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CarlaTrafficLightStatusList()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CarlaTrafficLightStatusList()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CarlaTrafficLightStatusList that will be copied.
     */
    eProsima_user_DllExport CarlaTrafficLightStatusList(
            const CarlaTrafficLightStatusList& x)
    {
                    m_traffic_lights = x.m_traffic_lights;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CarlaTrafficLightStatusList that will be copied.
     */
    eProsima_user_DllExport CarlaTrafficLightStatusList(
            CarlaTrafficLightStatusList&& x) noexcept
    {
        m_traffic_lights = std::move(x.m_traffic_lights);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CarlaTrafficLightStatusList that will be copied.
     */
    eProsima_user_DllExport CarlaTrafficLightStatusList& operator =(
            const CarlaTrafficLightStatusList& x)
    {

                    m_traffic_lights = x.m_traffic_lights;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CarlaTrafficLightStatusList that will be copied.
     */
    eProsima_user_DllExport CarlaTrafficLightStatusList& operator =(
            CarlaTrafficLightStatusList&& x) noexcept
    {

        m_traffic_lights = std::move(x.m_traffic_lights);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaTrafficLightStatusList object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CarlaTrafficLightStatusList& x) const
    {
        return (m_traffic_lights == x.m_traffic_lights);
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaTrafficLightStatusList object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CarlaTrafficLightStatusList& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member traffic_lights
     * @param _traffic_lights New value to be copied in member traffic_lights
     */
    eProsima_user_DllExport void traffic_lights(
            const std::vector<CarlaTrafficLightStatus>& _traffic_lights)
    {
        m_traffic_lights = _traffic_lights;
    }

    /*!
     * @brief This function moves the value in member traffic_lights
     * @param _traffic_lights New value to be moved in member traffic_lights
     */
    eProsima_user_DllExport void traffic_lights(
            std::vector<CarlaTrafficLightStatus>&& _traffic_lights)
    {
        m_traffic_lights = std::move(_traffic_lights);
    }

    /*!
     * @brief This function returns a constant reference to member traffic_lights
     * @return Constant reference to member traffic_lights
     */
    eProsima_user_DllExport const std::vector<CarlaTrafficLightStatus>& traffic_lights() const
    {
        return m_traffic_lights;
    }

    /*!
     * @brief This function returns a reference to member traffic_lights
     * @return Reference to member traffic_lights
     */
    eProsima_user_DllExport std::vector<CarlaTrafficLightStatus>& traffic_lights()
    {
        return m_traffic_lights;
    }



private:

    std::vector<CarlaTrafficLightStatus> m_traffic_lights;

};

} // namespace msg

} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLATRAFFICLIGHTSTATUSLIST_HPP_


