// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaEpisodeSettings.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLAEPISODESETTINGS_HPP
#define FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLAEPISODESETTINGS_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CARLAEPISODESETTINGS_SOURCE)
#define CARLAEPISODESETTINGS_DllAPI __declspec( dllexport )
#else
#define CARLAEPISODESETTINGS_DllAPI __declspec( dllimport )
#endif // CARLAEPISODESETTINGS_SOURCE
#else
#define CARLAEPISODESETTINGS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CARLAEPISODESETTINGS_DllAPI
#endif // _WIN32

namespace carla_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CarlaEpisodeSettings defined by the user in the IDL file.
 * @ingroup CarlaEpisodeSettings
 */
class CarlaEpisodeSettings
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CarlaEpisodeSettings()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CarlaEpisodeSettings()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CarlaEpisodeSettings that will be copied.
     */
    eProsima_user_DllExport CarlaEpisodeSettings(
            const CarlaEpisodeSettings& x)
    {
                    m_synchronous_mode = x.m_synchronous_mode;

                    m_no_rendering_mode = x.m_no_rendering_mode;

                    m_fixed_delta_seconds = x.m_fixed_delta_seconds;

                    m_substepping = x.m_substepping;

                    m_max_substep_delta_time = x.m_max_substep_delta_time;

                    m_max_substeps = x.m_max_substeps;

                    m_max_culling_distance = x.m_max_culling_distance;

                    m_deterministic_ragdolls = x.m_deterministic_ragdolls;

                    m_tile_stream_distance = x.m_tile_stream_distance;

                    m_actor_active_distance = x.m_actor_active_distance;

                    m_spectator_as_ego = x.m_spectator_as_ego;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CarlaEpisodeSettings that will be copied.
     */
    eProsima_user_DllExport CarlaEpisodeSettings(
            CarlaEpisodeSettings&& x) noexcept
    {
        m_synchronous_mode = x.m_synchronous_mode;
        m_no_rendering_mode = x.m_no_rendering_mode;
        m_fixed_delta_seconds = x.m_fixed_delta_seconds;
        m_substepping = x.m_substepping;
        m_max_substep_delta_time = x.m_max_substep_delta_time;
        m_max_substeps = x.m_max_substeps;
        m_max_culling_distance = x.m_max_culling_distance;
        m_deterministic_ragdolls = x.m_deterministic_ragdolls;
        m_tile_stream_distance = x.m_tile_stream_distance;
        m_actor_active_distance = x.m_actor_active_distance;
        m_spectator_as_ego = x.m_spectator_as_ego;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CarlaEpisodeSettings that will be copied.
     */
    eProsima_user_DllExport CarlaEpisodeSettings& operator =(
            const CarlaEpisodeSettings& x)
    {

                    m_synchronous_mode = x.m_synchronous_mode;

                    m_no_rendering_mode = x.m_no_rendering_mode;

                    m_fixed_delta_seconds = x.m_fixed_delta_seconds;

                    m_substepping = x.m_substepping;

                    m_max_substep_delta_time = x.m_max_substep_delta_time;

                    m_max_substeps = x.m_max_substeps;

                    m_max_culling_distance = x.m_max_culling_distance;

                    m_deterministic_ragdolls = x.m_deterministic_ragdolls;

                    m_tile_stream_distance = x.m_tile_stream_distance;

                    m_actor_active_distance = x.m_actor_active_distance;

                    m_spectator_as_ego = x.m_spectator_as_ego;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CarlaEpisodeSettings that will be copied.
     */
    eProsima_user_DllExport CarlaEpisodeSettings& operator =(
            CarlaEpisodeSettings&& x) noexcept
    {

        m_synchronous_mode = x.m_synchronous_mode;
        m_no_rendering_mode = x.m_no_rendering_mode;
        m_fixed_delta_seconds = x.m_fixed_delta_seconds;
        m_substepping = x.m_substepping;
        m_max_substep_delta_time = x.m_max_substep_delta_time;
        m_max_substeps = x.m_max_substeps;
        m_max_culling_distance = x.m_max_culling_distance;
        m_deterministic_ragdolls = x.m_deterministic_ragdolls;
        m_tile_stream_distance = x.m_tile_stream_distance;
        m_actor_active_distance = x.m_actor_active_distance;
        m_spectator_as_ego = x.m_spectator_as_ego;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaEpisodeSettings object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CarlaEpisodeSettings& x) const
    {
        return (m_synchronous_mode == x.m_synchronous_mode &&
           m_no_rendering_mode == x.m_no_rendering_mode &&
           m_fixed_delta_seconds == x.m_fixed_delta_seconds &&
           m_substepping == x.m_substepping &&
           m_max_substep_delta_time == x.m_max_substep_delta_time &&
           m_max_substeps == x.m_max_substeps &&
           m_max_culling_distance == x.m_max_culling_distance &&
           m_deterministic_ragdolls == x.m_deterministic_ragdolls &&
           m_tile_stream_distance == x.m_tile_stream_distance &&
           m_actor_active_distance == x.m_actor_active_distance &&
           m_spectator_as_ego == x.m_spectator_as_ego);
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaEpisodeSettings object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CarlaEpisodeSettings& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member synchronous_mode
     * @param _synchronous_mode New value for member synchronous_mode
     */
    eProsima_user_DllExport void synchronous_mode(
            bool _synchronous_mode)
    {
        m_synchronous_mode = _synchronous_mode;
    }

    /*!
     * @brief This function returns the value of member synchronous_mode
     * @return Value of member synchronous_mode
     */
    eProsima_user_DllExport bool synchronous_mode() const
    {
        return m_synchronous_mode;
    }

    /*!
     * @brief This function returns a reference to member synchronous_mode
     * @return Reference to member synchronous_mode
     */
    eProsima_user_DllExport bool& synchronous_mode()
    {
        return m_synchronous_mode;
    }


    /*!
     * @brief This function sets a value in member no_rendering_mode
     * @param _no_rendering_mode New value for member no_rendering_mode
     */
    eProsima_user_DllExport void no_rendering_mode(
            bool _no_rendering_mode)
    {
        m_no_rendering_mode = _no_rendering_mode;
    }

    /*!
     * @brief This function returns the value of member no_rendering_mode
     * @return Value of member no_rendering_mode
     */
    eProsima_user_DllExport bool no_rendering_mode() const
    {
        return m_no_rendering_mode;
    }

    /*!
     * @brief This function returns a reference to member no_rendering_mode
     * @return Reference to member no_rendering_mode
     */
    eProsima_user_DllExport bool& no_rendering_mode()
    {
        return m_no_rendering_mode;
    }


    /*!
     * @brief This function sets a value in member fixed_delta_seconds
     * @param _fixed_delta_seconds New value for member fixed_delta_seconds
     */
    eProsima_user_DllExport void fixed_delta_seconds(
            double _fixed_delta_seconds)
    {
        m_fixed_delta_seconds = _fixed_delta_seconds;
    }

    /*!
     * @brief This function returns the value of member fixed_delta_seconds
     * @return Value of member fixed_delta_seconds
     */
    eProsima_user_DllExport double fixed_delta_seconds() const
    {
        return m_fixed_delta_seconds;
    }

    /*!
     * @brief This function returns a reference to member fixed_delta_seconds
     * @return Reference to member fixed_delta_seconds
     */
    eProsima_user_DllExport double& fixed_delta_seconds()
    {
        return m_fixed_delta_seconds;
    }


    /*!
     * @brief This function sets a value in member substepping
     * @param _substepping New value for member substepping
     */
    eProsima_user_DllExport void substepping(
            bool _substepping)
    {
        m_substepping = _substepping;
    }

    /*!
     * @brief This function returns the value of member substepping
     * @return Value of member substepping
     */
    eProsima_user_DllExport bool substepping() const
    {
        return m_substepping;
    }

    /*!
     * @brief This function returns a reference to member substepping
     * @return Reference to member substepping
     */
    eProsima_user_DllExport bool& substepping()
    {
        return m_substepping;
    }


    /*!
     * @brief This function sets a value in member max_substep_delta_time
     * @param _max_substep_delta_time New value for member max_substep_delta_time
     */
    eProsima_user_DllExport void max_substep_delta_time(
            double _max_substep_delta_time)
    {
        m_max_substep_delta_time = _max_substep_delta_time;
    }

    /*!
     * @brief This function returns the value of member max_substep_delta_time
     * @return Value of member max_substep_delta_time
     */
    eProsima_user_DllExport double max_substep_delta_time() const
    {
        return m_max_substep_delta_time;
    }

    /*!
     * @brief This function returns a reference to member max_substep_delta_time
     * @return Reference to member max_substep_delta_time
     */
    eProsima_user_DllExport double& max_substep_delta_time()
    {
        return m_max_substep_delta_time;
    }


    /*!
     * @brief This function sets a value in member max_substeps
     * @param _max_substeps New value for member max_substeps
     */
    eProsima_user_DllExport void max_substeps(
            int32_t _max_substeps)
    {
        m_max_substeps = _max_substeps;
    }

    /*!
     * @brief This function returns the value of member max_substeps
     * @return Value of member max_substeps
     */
    eProsima_user_DllExport int32_t max_substeps() const
    {
        return m_max_substeps;
    }

    /*!
     * @brief This function returns a reference to member max_substeps
     * @return Reference to member max_substeps
     */
    eProsima_user_DllExport int32_t& max_substeps()
    {
        return m_max_substeps;
    }


    /*!
     * @brief This function sets a value in member max_culling_distance
     * @param _max_culling_distance New value for member max_culling_distance
     */
    eProsima_user_DllExport void max_culling_distance(
            float _max_culling_distance)
    {
        m_max_culling_distance = _max_culling_distance;
    }

    /*!
     * @brief This function returns the value of member max_culling_distance
     * @return Value of member max_culling_distance
     */
    eProsima_user_DllExport float max_culling_distance() const
    {
        return m_max_culling_distance;
    }

    /*!
     * @brief This function returns a reference to member max_culling_distance
     * @return Reference to member max_culling_distance
     */
    eProsima_user_DllExport float& max_culling_distance()
    {
        return m_max_culling_distance;
    }


    /*!
     * @brief This function sets a value in member deterministic_ragdolls
     * @param _deterministic_ragdolls New value for member deterministic_ragdolls
     */
    eProsima_user_DllExport void deterministic_ragdolls(
            bool _deterministic_ragdolls)
    {
        m_deterministic_ragdolls = _deterministic_ragdolls;
    }

    /*!
     * @brief This function returns the value of member deterministic_ragdolls
     * @return Value of member deterministic_ragdolls
     */
    eProsima_user_DllExport bool deterministic_ragdolls() const
    {
        return m_deterministic_ragdolls;
    }

    /*!
     * @brief This function returns a reference to member deterministic_ragdolls
     * @return Reference to member deterministic_ragdolls
     */
    eProsima_user_DllExport bool& deterministic_ragdolls()
    {
        return m_deterministic_ragdolls;
    }


    /*!
     * @brief This function sets a value in member tile_stream_distance
     * @param _tile_stream_distance New value for member tile_stream_distance
     */
    eProsima_user_DllExport void tile_stream_distance(
            float _tile_stream_distance)
    {
        m_tile_stream_distance = _tile_stream_distance;
    }

    /*!
     * @brief This function returns the value of member tile_stream_distance
     * @return Value of member tile_stream_distance
     */
    eProsima_user_DllExport float tile_stream_distance() const
    {
        return m_tile_stream_distance;
    }

    /*!
     * @brief This function returns a reference to member tile_stream_distance
     * @return Reference to member tile_stream_distance
     */
    eProsima_user_DllExport float& tile_stream_distance()
    {
        return m_tile_stream_distance;
    }


    /*!
     * @brief This function sets a value in member actor_active_distance
     * @param _actor_active_distance New value for member actor_active_distance
     */
    eProsima_user_DllExport void actor_active_distance(
            float _actor_active_distance)
    {
        m_actor_active_distance = _actor_active_distance;
    }

    /*!
     * @brief This function returns the value of member actor_active_distance
     * @return Value of member actor_active_distance
     */
    eProsima_user_DllExport float actor_active_distance() const
    {
        return m_actor_active_distance;
    }

    /*!
     * @brief This function returns a reference to member actor_active_distance
     * @return Reference to member actor_active_distance
     */
    eProsima_user_DllExport float& actor_active_distance()
    {
        return m_actor_active_distance;
    }


    /*!
     * @brief This function sets a value in member spectator_as_ego
     * @param _spectator_as_ego New value for member spectator_as_ego
     */
    eProsima_user_DllExport void spectator_as_ego(
            bool _spectator_as_ego)
    {
        m_spectator_as_ego = _spectator_as_ego;
    }

    /*!
     * @brief This function returns the value of member spectator_as_ego
     * @return Value of member spectator_as_ego
     */
    eProsima_user_DllExport bool spectator_as_ego() const
    {
        return m_spectator_as_ego;
    }

    /*!
     * @brief This function returns a reference to member spectator_as_ego
     * @return Reference to member spectator_as_ego
     */
    eProsima_user_DllExport bool& spectator_as_ego()
    {
        return m_spectator_as_ego;
    }



private:

    bool m_synchronous_mode{false};
    bool m_no_rendering_mode{false};
    double m_fixed_delta_seconds{0.0};
    bool m_substepping{true};
    double m_max_substep_delta_time{0.01};
    int32_t m_max_substeps{10};
    float m_max_culling_distance{0.0};
    bool m_deterministic_ragdolls{false};
    float m_tile_stream_distance{3000.0};
    float m_actor_active_distance{2000.0};
    bool m_spectator_as_ego{true};

};

} // namespace msg

} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLAEPISODESETTINGS_HPP_


