// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaEgoVehicleInfo.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLAEGOVEHICLEINFO_HPP
#define FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLAEGOVEHICLEINFO_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include "CarlaEgoVehicleInfoWheel.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CARLAEGOVEHICLEINFO_SOURCE)
#define CARLAEGOVEHICLEINFO_DllAPI __declspec( dllexport )
#else
#define CARLAEGOVEHICLEINFO_DllAPI __declspec( dllimport )
#endif // CARLAEGOVEHICLEINFO_SOURCE
#else
#define CARLAEGOVEHICLEINFO_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CARLAEGOVEHICLEINFO_DllAPI
#endif // _WIN32

namespace carla_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CarlaEgoVehicleInfo defined by the user in the IDL file.
 * @ingroup CarlaEgoVehicleInfo
 */
class CarlaEgoVehicleInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CarlaEgoVehicleInfo()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CarlaEgoVehicleInfo()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CarlaEgoVehicleInfo that will be copied.
     */
    eProsima_user_DllExport CarlaEgoVehicleInfo(
            const CarlaEgoVehicleInfo& x)
    {
                    m_id = x.m_id;

                    m_type = x.m_type;

                    m_rolename = x.m_rolename;

                    m_wheels = x.m_wheels;

                    m_max_rpm = x.m_max_rpm;

                    m_moi = x.m_moi;

                    m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;

                    m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;

                    m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;

                    m_use_gear_autobox = x.m_use_gear_autobox;

                    m_gear_switch_time = x.m_gear_switch_time;

                    m_clutch_strength = x.m_clutch_strength;

                    m_mass = x.m_mass;

                    m_drag_coefficient = x.m_drag_coefficient;

                    m_center_of_mass = x.m_center_of_mass;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CarlaEgoVehicleInfo that will be copied.
     */
    eProsima_user_DllExport CarlaEgoVehicleInfo(
            CarlaEgoVehicleInfo&& x) noexcept
    {
        m_id = x.m_id;
        m_type = std::move(x.m_type);
        m_rolename = std::move(x.m_rolename);
        m_wheels = std::move(x.m_wheels);
        m_max_rpm = x.m_max_rpm;
        m_moi = x.m_moi;
        m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;
        m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;
        m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;
        m_use_gear_autobox = x.m_use_gear_autobox;
        m_gear_switch_time = x.m_gear_switch_time;
        m_clutch_strength = x.m_clutch_strength;
        m_mass = x.m_mass;
        m_drag_coefficient = x.m_drag_coefficient;
        m_center_of_mass = std::move(x.m_center_of_mass);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CarlaEgoVehicleInfo that will be copied.
     */
    eProsima_user_DllExport CarlaEgoVehicleInfo& operator =(
            const CarlaEgoVehicleInfo& x)
    {

                    m_id = x.m_id;

                    m_type = x.m_type;

                    m_rolename = x.m_rolename;

                    m_wheels = x.m_wheels;

                    m_max_rpm = x.m_max_rpm;

                    m_moi = x.m_moi;

                    m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;

                    m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;

                    m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;

                    m_use_gear_autobox = x.m_use_gear_autobox;

                    m_gear_switch_time = x.m_gear_switch_time;

                    m_clutch_strength = x.m_clutch_strength;

                    m_mass = x.m_mass;

                    m_drag_coefficient = x.m_drag_coefficient;

                    m_center_of_mass = x.m_center_of_mass;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CarlaEgoVehicleInfo that will be copied.
     */
    eProsima_user_DllExport CarlaEgoVehicleInfo& operator =(
            CarlaEgoVehicleInfo&& x) noexcept
    {

        m_id = x.m_id;
        m_type = std::move(x.m_type);
        m_rolename = std::move(x.m_rolename);
        m_wheels = std::move(x.m_wheels);
        m_max_rpm = x.m_max_rpm;
        m_moi = x.m_moi;
        m_damping_rate_full_throttle = x.m_damping_rate_full_throttle;
        m_damping_rate_zero_throttle_clutch_engaged = x.m_damping_rate_zero_throttle_clutch_engaged;
        m_damping_rate_zero_throttle_clutch_disengaged = x.m_damping_rate_zero_throttle_clutch_disengaged;
        m_use_gear_autobox = x.m_use_gear_autobox;
        m_gear_switch_time = x.m_gear_switch_time;
        m_clutch_strength = x.m_clutch_strength;
        m_mass = x.m_mass;
        m_drag_coefficient = x.m_drag_coefficient;
        m_center_of_mass = std::move(x.m_center_of_mass);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaEgoVehicleInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CarlaEgoVehicleInfo& x) const
    {
        return (m_id == x.m_id &&
           m_type == x.m_type &&
           m_rolename == x.m_rolename &&
           m_wheels == x.m_wheels &&
           m_max_rpm == x.m_max_rpm &&
           m_moi == x.m_moi &&
           m_damping_rate_full_throttle == x.m_damping_rate_full_throttle &&
           m_damping_rate_zero_throttle_clutch_engaged == x.m_damping_rate_zero_throttle_clutch_engaged &&
           m_damping_rate_zero_throttle_clutch_disengaged == x.m_damping_rate_zero_throttle_clutch_disengaged &&
           m_use_gear_autobox == x.m_use_gear_autobox &&
           m_gear_switch_time == x.m_gear_switch_time &&
           m_clutch_strength == x.m_clutch_strength &&
           m_mass == x.m_mass &&
           m_drag_coefficient == x.m_drag_coefficient &&
           m_center_of_mass == x.m_center_of_mass);
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaEgoVehicleInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CarlaEgoVehicleInfo& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            uint32_t _id)
    {
        m_id = _id;
    }

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport uint32_t id() const
    {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport uint32_t& id()
    {
        return m_id;
    }


    /*!
     * @brief This function copies the value in member type
     * @param _type New value to be copied in member type
     */
    eProsima_user_DllExport void type(
            const std::string& _type)
    {
        m_type = _type;
    }

    /*!
     * @brief This function moves the value in member type
     * @param _type New value to be moved in member type
     */
    eProsima_user_DllExport void type(
            std::string&& _type)
    {
        m_type = std::move(_type);
    }

    /*!
     * @brief This function returns a constant reference to member type
     * @return Constant reference to member type
     */
    eProsima_user_DllExport const std::string& type() const
    {
        return m_type;
    }

    /*!
     * @brief This function returns a reference to member type
     * @return Reference to member type
     */
    eProsima_user_DllExport std::string& type()
    {
        return m_type;
    }


    /*!
     * @brief This function copies the value in member rolename
     * @param _rolename New value to be copied in member rolename
     */
    eProsima_user_DllExport void rolename(
            const std::string& _rolename)
    {
        m_rolename = _rolename;
    }

    /*!
     * @brief This function moves the value in member rolename
     * @param _rolename New value to be moved in member rolename
     */
    eProsima_user_DllExport void rolename(
            std::string&& _rolename)
    {
        m_rolename = std::move(_rolename);
    }

    /*!
     * @brief This function returns a constant reference to member rolename
     * @return Constant reference to member rolename
     */
    eProsima_user_DllExport const std::string& rolename() const
    {
        return m_rolename;
    }

    /*!
     * @brief This function returns a reference to member rolename
     * @return Reference to member rolename
     */
    eProsima_user_DllExport std::string& rolename()
    {
        return m_rolename;
    }


    /*!
     * @brief This function copies the value in member wheels
     * @param _wheels New value to be copied in member wheels
     */
    eProsima_user_DllExport void wheels(
            const std::vector<CarlaEgoVehicleInfoWheel>& _wheels)
    {
        m_wheels = _wheels;
    }

    /*!
     * @brief This function moves the value in member wheels
     * @param _wheels New value to be moved in member wheels
     */
    eProsima_user_DllExport void wheels(
            std::vector<CarlaEgoVehicleInfoWheel>&& _wheels)
    {
        m_wheels = std::move(_wheels);
    }

    /*!
     * @brief This function returns a constant reference to member wheels
     * @return Constant reference to member wheels
     */
    eProsima_user_DllExport const std::vector<CarlaEgoVehicleInfoWheel>& wheels() const
    {
        return m_wheels;
    }

    /*!
     * @brief This function returns a reference to member wheels
     * @return Reference to member wheels
     */
    eProsima_user_DllExport std::vector<CarlaEgoVehicleInfoWheel>& wheels()
    {
        return m_wheels;
    }


    /*!
     * @brief This function sets a value in member max_rpm
     * @param _max_rpm New value for member max_rpm
     */
    eProsima_user_DllExport void max_rpm(
            float _max_rpm)
    {
        m_max_rpm = _max_rpm;
    }

    /*!
     * @brief This function returns the value of member max_rpm
     * @return Value of member max_rpm
     */
    eProsima_user_DllExport float max_rpm() const
    {
        return m_max_rpm;
    }

    /*!
     * @brief This function returns a reference to member max_rpm
     * @return Reference to member max_rpm
     */
    eProsima_user_DllExport float& max_rpm()
    {
        return m_max_rpm;
    }


    /*!
     * @brief This function sets a value in member moi
     * @param _moi New value for member moi
     */
    eProsima_user_DllExport void moi(
            float _moi)
    {
        m_moi = _moi;
    }

    /*!
     * @brief This function returns the value of member moi
     * @return Value of member moi
     */
    eProsima_user_DllExport float moi() const
    {
        return m_moi;
    }

    /*!
     * @brief This function returns a reference to member moi
     * @return Reference to member moi
     */
    eProsima_user_DllExport float& moi()
    {
        return m_moi;
    }


    /*!
     * @brief This function sets a value in member damping_rate_full_throttle
     * @param _damping_rate_full_throttle New value for member damping_rate_full_throttle
     */
    eProsima_user_DllExport void damping_rate_full_throttle(
            float _damping_rate_full_throttle)
    {
        m_damping_rate_full_throttle = _damping_rate_full_throttle;
    }

    /*!
     * @brief This function returns the value of member damping_rate_full_throttle
     * @return Value of member damping_rate_full_throttle
     */
    eProsima_user_DllExport float damping_rate_full_throttle() const
    {
        return m_damping_rate_full_throttle;
    }

    /*!
     * @brief This function returns a reference to member damping_rate_full_throttle
     * @return Reference to member damping_rate_full_throttle
     */
    eProsima_user_DllExport float& damping_rate_full_throttle()
    {
        return m_damping_rate_full_throttle;
    }


    /*!
     * @brief This function sets a value in member damping_rate_zero_throttle_clutch_engaged
     * @param _damping_rate_zero_throttle_clutch_engaged New value for member damping_rate_zero_throttle_clutch_engaged
     */
    eProsima_user_DllExport void damping_rate_zero_throttle_clutch_engaged(
            float _damping_rate_zero_throttle_clutch_engaged)
    {
        m_damping_rate_zero_throttle_clutch_engaged = _damping_rate_zero_throttle_clutch_engaged;
    }

    /*!
     * @brief This function returns the value of member damping_rate_zero_throttle_clutch_engaged
     * @return Value of member damping_rate_zero_throttle_clutch_engaged
     */
    eProsima_user_DllExport float damping_rate_zero_throttle_clutch_engaged() const
    {
        return m_damping_rate_zero_throttle_clutch_engaged;
    }

    /*!
     * @brief This function returns a reference to member damping_rate_zero_throttle_clutch_engaged
     * @return Reference to member damping_rate_zero_throttle_clutch_engaged
     */
    eProsima_user_DllExport float& damping_rate_zero_throttle_clutch_engaged()
    {
        return m_damping_rate_zero_throttle_clutch_engaged;
    }


    /*!
     * @brief This function sets a value in member damping_rate_zero_throttle_clutch_disengaged
     * @param _damping_rate_zero_throttle_clutch_disengaged New value for member damping_rate_zero_throttle_clutch_disengaged
     */
    eProsima_user_DllExport void damping_rate_zero_throttle_clutch_disengaged(
            float _damping_rate_zero_throttle_clutch_disengaged)
    {
        m_damping_rate_zero_throttle_clutch_disengaged = _damping_rate_zero_throttle_clutch_disengaged;
    }

    /*!
     * @brief This function returns the value of member damping_rate_zero_throttle_clutch_disengaged
     * @return Value of member damping_rate_zero_throttle_clutch_disengaged
     */
    eProsima_user_DllExport float damping_rate_zero_throttle_clutch_disengaged() const
    {
        return m_damping_rate_zero_throttle_clutch_disengaged;
    }

    /*!
     * @brief This function returns a reference to member damping_rate_zero_throttle_clutch_disengaged
     * @return Reference to member damping_rate_zero_throttle_clutch_disengaged
     */
    eProsima_user_DllExport float& damping_rate_zero_throttle_clutch_disengaged()
    {
        return m_damping_rate_zero_throttle_clutch_disengaged;
    }


    /*!
     * @brief This function sets a value in member use_gear_autobox
     * @param _use_gear_autobox New value for member use_gear_autobox
     */
    eProsima_user_DllExport void use_gear_autobox(
            bool _use_gear_autobox)
    {
        m_use_gear_autobox = _use_gear_autobox;
    }

    /*!
     * @brief This function returns the value of member use_gear_autobox
     * @return Value of member use_gear_autobox
     */
    eProsima_user_DllExport bool use_gear_autobox() const
    {
        return m_use_gear_autobox;
    }

    /*!
     * @brief This function returns a reference to member use_gear_autobox
     * @return Reference to member use_gear_autobox
     */
    eProsima_user_DllExport bool& use_gear_autobox()
    {
        return m_use_gear_autobox;
    }


    /*!
     * @brief This function sets a value in member gear_switch_time
     * @param _gear_switch_time New value for member gear_switch_time
     */
    eProsima_user_DllExport void gear_switch_time(
            float _gear_switch_time)
    {
        m_gear_switch_time = _gear_switch_time;
    }

    /*!
     * @brief This function returns the value of member gear_switch_time
     * @return Value of member gear_switch_time
     */
    eProsima_user_DllExport float gear_switch_time() const
    {
        return m_gear_switch_time;
    }

    /*!
     * @brief This function returns a reference to member gear_switch_time
     * @return Reference to member gear_switch_time
     */
    eProsima_user_DllExport float& gear_switch_time()
    {
        return m_gear_switch_time;
    }


    /*!
     * @brief This function sets a value in member clutch_strength
     * @param _clutch_strength New value for member clutch_strength
     */
    eProsima_user_DllExport void clutch_strength(
            float _clutch_strength)
    {
        m_clutch_strength = _clutch_strength;
    }

    /*!
     * @brief This function returns the value of member clutch_strength
     * @return Value of member clutch_strength
     */
    eProsima_user_DllExport float clutch_strength() const
    {
        return m_clutch_strength;
    }

    /*!
     * @brief This function returns a reference to member clutch_strength
     * @return Reference to member clutch_strength
     */
    eProsima_user_DllExport float& clutch_strength()
    {
        return m_clutch_strength;
    }


    /*!
     * @brief This function sets a value in member mass
     * @param _mass New value for member mass
     */
    eProsima_user_DllExport void mass(
            float _mass)
    {
        m_mass = _mass;
    }

    /*!
     * @brief This function returns the value of member mass
     * @return Value of member mass
     */
    eProsima_user_DllExport float mass() const
    {
        return m_mass;
    }

    /*!
     * @brief This function returns a reference to member mass
     * @return Reference to member mass
     */
    eProsima_user_DllExport float& mass()
    {
        return m_mass;
    }


    /*!
     * @brief This function sets a value in member drag_coefficient
     * @param _drag_coefficient New value for member drag_coefficient
     */
    eProsima_user_DllExport void drag_coefficient(
            float _drag_coefficient)
    {
        m_drag_coefficient = _drag_coefficient;
    }

    /*!
     * @brief This function returns the value of member drag_coefficient
     * @return Value of member drag_coefficient
     */
    eProsima_user_DllExport float drag_coefficient() const
    {
        return m_drag_coefficient;
    }

    /*!
     * @brief This function returns a reference to member drag_coefficient
     * @return Reference to member drag_coefficient
     */
    eProsima_user_DllExport float& drag_coefficient()
    {
        return m_drag_coefficient;
    }


    /*!
     * @brief This function copies the value in member center_of_mass
     * @param _center_of_mass New value to be copied in member center_of_mass
     */
    eProsima_user_DllExport void center_of_mass(
            const geometry_msgs::msg::Vector3& _center_of_mass)
    {
        m_center_of_mass = _center_of_mass;
    }

    /*!
     * @brief This function moves the value in member center_of_mass
     * @param _center_of_mass New value to be moved in member center_of_mass
     */
    eProsima_user_DllExport void center_of_mass(
            geometry_msgs::msg::Vector3&& _center_of_mass)
    {
        m_center_of_mass = std::move(_center_of_mass);
    }

    /*!
     * @brief This function returns a constant reference to member center_of_mass
     * @return Constant reference to member center_of_mass
     */
    eProsima_user_DllExport const geometry_msgs::msg::Vector3& center_of_mass() const
    {
        return m_center_of_mass;
    }

    /*!
     * @brief This function returns a reference to member center_of_mass
     * @return Reference to member center_of_mass
     */
    eProsima_user_DllExport geometry_msgs::msg::Vector3& center_of_mass()
    {
        return m_center_of_mass;
    }



private:

    uint32_t m_id{0};
    std::string m_type;
    std::string m_rolename;
    std::vector<CarlaEgoVehicleInfoWheel> m_wheels;
    float m_max_rpm{0.0};
    float m_moi{0.0};
    float m_damping_rate_full_throttle{0.0};
    float m_damping_rate_zero_throttle_clutch_engaged{0.0};
    float m_damping_rate_zero_throttle_clutch_disengaged{0.0};
    bool m_use_gear_autobox{false};
    float m_gear_switch_time{0.0};
    float m_clutch_strength{0.0};
    float m_mass{0.0};
    float m_drag_coefficient{0.0};
    geometry_msgs::msg::Vector3 m_center_of_mass;

};

} // namespace msg

} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLAEGOVEHICLEINFO_HPP_


