// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaBoundingBox.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLABOUNDINGBOX_HPP
#define FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLABOUNDINGBOX_HPP

#include <cstdint>
#include <utility>
#include "geometry_msgs/msg/Vector3.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CARLABOUNDINGBOX_SOURCE)
#define CARLABOUNDINGBOX_DllAPI __declspec( dllexport )
#else
#define CARLABOUNDINGBOX_DllAPI __declspec( dllimport )
#endif // CARLABOUNDINGBOX_SOURCE
#else
#define CARLABOUNDINGBOX_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CARLABOUNDINGBOX_DllAPI
#endif // _WIN32

namespace carla_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CarlaBoundingBox defined by the user in the IDL file.
 * @ingroup CarlaBoundingBox
 */
class CarlaBoundingBox
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CarlaBoundingBox()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CarlaBoundingBox()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CarlaBoundingBox that will be copied.
     */
    eProsima_user_DllExport CarlaBoundingBox(
            const CarlaBoundingBox& x)
    {
                    m_center = x.m_center;

                    m_size = x.m_size;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CarlaBoundingBox that will be copied.
     */
    eProsima_user_DllExport CarlaBoundingBox(
            CarlaBoundingBox&& x) noexcept
    {
        m_center = std::move(x.m_center);
        m_size = std::move(x.m_size);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CarlaBoundingBox that will be copied.
     */
    eProsima_user_DllExport CarlaBoundingBox& operator =(
            const CarlaBoundingBox& x)
    {

                    m_center = x.m_center;

                    m_size = x.m_size;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CarlaBoundingBox that will be copied.
     */
    eProsima_user_DllExport CarlaBoundingBox& operator =(
            CarlaBoundingBox&& x) noexcept
    {

        m_center = std::move(x.m_center);
        m_size = std::move(x.m_size);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaBoundingBox object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CarlaBoundingBox& x) const
    {
        return (m_center == x.m_center &&
           m_size == x.m_size);
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaBoundingBox object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CarlaBoundingBox& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member center
     * @param _center New value to be copied in member center
     */
    eProsima_user_DllExport void center(
            const geometry_msgs::msg::Vector3& _center)
    {
        m_center = _center;
    }

    /*!
     * @brief This function moves the value in member center
     * @param _center New value to be moved in member center
     */
    eProsima_user_DllExport void center(
            geometry_msgs::msg::Vector3&& _center)
    {
        m_center = std::move(_center);
    }

    /*!
     * @brief This function returns a constant reference to member center
     * @return Constant reference to member center
     */
    eProsima_user_DllExport const geometry_msgs::msg::Vector3& center() const
    {
        return m_center;
    }

    /*!
     * @brief This function returns a reference to member center
     * @return Reference to member center
     */
    eProsima_user_DllExport geometry_msgs::msg::Vector3& center()
    {
        return m_center;
    }


    /*!
     * @brief This function copies the value in member size
     * @param _size New value to be copied in member size
     */
    eProsima_user_DllExport void size(
            const geometry_msgs::msg::Vector3& _size)
    {
        m_size = _size;
    }

    /*!
     * @brief This function moves the value in member size
     * @param _size New value to be moved in member size
     */
    eProsima_user_DllExport void size(
            geometry_msgs::msg::Vector3&& _size)
    {
        m_size = std::move(_size);
    }

    /*!
     * @brief This function returns a constant reference to member size
     * @return Constant reference to member size
     */
    eProsima_user_DllExport const geometry_msgs::msg::Vector3& size() const
    {
        return m_size;
    }

    /*!
     * @brief This function returns a reference to member size
     * @return Reference to member size
     */
    eProsima_user_DllExport geometry_msgs::msg::Vector3& size()
    {
        return m_size;
    }



private:

    geometry_msgs::msg::Vector3 m_center;
    geometry_msgs::msg::Vector3 m_size;

};

} // namespace msg

} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLABOUNDINGBOX_HPP_


