// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaTrafficLightInfoTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "CarlaTrafficLightInfoTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "CarlaTrafficLightInfo.hpp"

#include "CarlaBoundingBox.hpp"
#include "geometry_msgs/msg/Pose.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace carla_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_CarlaTrafficLightInfo_type_identifier(
        TypeIdentifierPair& type_ids_CarlaTrafficLightInfo)
{

    ReturnCode_t return_code_CarlaTrafficLightInfo {eprosima::fastdds::dds::RETCODE_OK};
    return_code_CarlaTrafficLightInfo =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "carla_msgs::msg::dds_::CarlaTrafficLightInfo_", type_ids_CarlaTrafficLightInfo);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_CarlaTrafficLightInfo)
    {
        StructTypeFlag struct_flags_CarlaTrafficLightInfo = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_CarlaTrafficLightInfo = "carla_msgs::msg::dds_::CarlaTrafficLightInfo_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_CarlaTrafficLightInfo;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_CarlaTrafficLightInfo;
        AppliedAnnotationSeq tmp_ann_custom_CarlaTrafficLightInfo;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_CarlaTrafficLightInfo;
        PlacementKind placement_CarlaTrafficLightInfo = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_CarlaTrafficLightInfo = "*";
        std::string text_CarlaTrafficLightInfo;
        language_CarlaTrafficLightInfo = "comment";

        placement_CarlaTrafficLightInfo = PlacementKind::BEFORE_DECLARATION;

        text_CarlaTrafficLightInfo = "Copyright (c) 2020 Intel Corporation.\n\nThis work is licensed under the terms of the MIT license.\nFor a copy, see <https://opensource.org/licenses/MIT>.";

        verbatim_CarlaTrafficLightInfo = TypeObjectUtils::build_applied_verbatim_annotation(placement_CarlaTrafficLightInfo, language_CarlaTrafficLightInfo, text_CarlaTrafficLightInfo);
        type_ann_builtin_CarlaTrafficLightInfo = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_CarlaTrafficLightInfo);

        if (!tmp_ann_custom_CarlaTrafficLightInfo.empty())
        {
            ann_custom_CarlaTrafficLightInfo = tmp_ann_custom_CarlaTrafficLightInfo;
        }

        CompleteTypeDetail detail_CarlaTrafficLightInfo = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_CarlaTrafficLightInfo, ann_custom_CarlaTrafficLightInfo, type_name_CarlaTrafficLightInfo.to_string());
        CompleteStructHeader header_CarlaTrafficLightInfo;
        header_CarlaTrafficLightInfo = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_CarlaTrafficLightInfo);
        CompleteStructMemberSeq member_seq_CarlaTrafficLightInfo;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_CarlaTrafficLightInfo.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_CarlaTrafficLightInfo);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaTrafficLightInfo, member_id);
        }
        {
            TypeIdentifierPair type_ids_transform;
            ReturnCode_t return_code_transform {eprosima::fastdds::dds::RETCODE_OK};
            return_code_transform =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::Pose_", type_ids_transform);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_transform)
            {
                geometry_msgs::msg::register_Pose_type_identifier(type_ids_transform);
            }
            StructMemberFlag member_flags_transform = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_transform = 0x00000001;
            bool common_transform_ec {false};
            CommonStructMember common_transform {TypeObjectUtils::build_common_struct_member(member_id_transform, member_flags_transform, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_transform, common_transform_ec))};
            if (!common_transform_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure transform member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_transform = "transform";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_transform;
            ann_custom_CarlaTrafficLightInfo.reset();
            CompleteMemberDetail detail_transform = TypeObjectUtils::build_complete_member_detail(name_transform, member_ann_builtin_transform, ann_custom_CarlaTrafficLightInfo);
            CompleteStructMember member_transform = TypeObjectUtils::build_complete_struct_member(common_transform, detail_transform);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaTrafficLightInfo, member_transform);
        }
        {
            TypeIdentifierPair type_ids_trigger_volume;
            ReturnCode_t return_code_trigger_volume {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trigger_volume =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "carla_msgs::msg::dds_::CarlaBoundingBox_", type_ids_trigger_volume);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trigger_volume)
            {
                carla_msgs::msg::register_CarlaBoundingBox_type_identifier(type_ids_trigger_volume);
            }
            StructMemberFlag member_flags_trigger_volume = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trigger_volume = 0x00000002;
            bool common_trigger_volume_ec {false};
            CommonStructMember common_trigger_volume {TypeObjectUtils::build_common_struct_member(member_id_trigger_volume, member_flags_trigger_volume, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trigger_volume, common_trigger_volume_ec))};
            if (!common_trigger_volume_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trigger_volume member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trigger_volume = "trigger_volume";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trigger_volume;
            ann_custom_CarlaTrafficLightInfo.reset();
            AppliedAnnotationSeq tmp_ann_custom_trigger_volume;
            eprosima::fastcdr::optional<std::string> unit_trigger_volume;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_trigger_volume;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_trigger_volume;
            eprosima::fastcdr::optional<std::string> hash_id_trigger_volume;
            if (unit_trigger_volume.has_value() || min_trigger_volume.has_value() || max_trigger_volume.has_value() || hash_id_trigger_volume.has_value())
            {
                member_ann_builtin_trigger_volume = TypeObjectUtils::build_applied_builtin_member_annotations(unit_trigger_volume, min_trigger_volume, max_trigger_volume, hash_id_trigger_volume);
            }
            if (!tmp_ann_custom_trigger_volume.empty())
            {
                ann_custom_CarlaTrafficLightInfo = tmp_ann_custom_trigger_volume;
            }
            CompleteMemberDetail detail_trigger_volume = TypeObjectUtils::build_complete_member_detail(name_trigger_volume, member_ann_builtin_trigger_volume, ann_custom_CarlaTrafficLightInfo);
            CompleteStructMember member_trigger_volume = TypeObjectUtils::build_complete_struct_member(common_trigger_volume, detail_trigger_volume);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaTrafficLightInfo, member_trigger_volume);
        }
        CompleteStructType struct_type_CarlaTrafficLightInfo = TypeObjectUtils::build_complete_struct_type(struct_flags_CarlaTrafficLightInfo, header_CarlaTrafficLightInfo, member_seq_CarlaTrafficLightInfo);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_CarlaTrafficLightInfo, type_name_CarlaTrafficLightInfo.to_string(), type_ids_CarlaTrafficLightInfo))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "carla_msgs::msg::CarlaTrafficLightInfo already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace carla_msgs

