// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaControl.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLACONTROL_HPP
#define FAST_DDS_GENERATED__CARLA_MSGS_MSG_CARLACONTROL_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CARLACONTROL_SOURCE)
#define CARLACONTROL_DllAPI __declspec( dllexport )
#else
#define CARLACONTROL_DllAPI __declspec( dllimport )
#endif // CARLACONTROL_SOURCE
#else
#define CARLACONTROL_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CARLACONTROL_DllAPI
#endif // _WIN32

namespace carla_msgs {

namespace msg {

namespace CarlaControl_Constants {

const int8_t PLAY = 0;
const int8_t PAUSE = 1;
const int8_t STEP_ONCE = 2;

} // namespace CarlaControl_Constants
/*!
 * @brief This class represents the structure CarlaControl defined by the user in the IDL file.
 * @ingroup CarlaControl
 */
class CarlaControl
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CarlaControl()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CarlaControl()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CarlaControl that will be copied.
     */
    eProsima_user_DllExport CarlaControl(
            const CarlaControl& x)
    {
                    m_command = x.m_command;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CarlaControl that will be copied.
     */
    eProsima_user_DllExport CarlaControl(
            CarlaControl&& x) noexcept
    {
        m_command = x.m_command;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CarlaControl that will be copied.
     */
    eProsima_user_DllExport CarlaControl& operator =(
            const CarlaControl& x)
    {

                    m_command = x.m_command;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CarlaControl that will be copied.
     */
    eProsima_user_DllExport CarlaControl& operator =(
            CarlaControl&& x) noexcept
    {

        m_command = x.m_command;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaControl object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CarlaControl& x) const
    {
        return (m_command == x.m_command);
    }

    /*!
     * @brief Comparison operator.
     * @param x CarlaControl object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CarlaControl& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member command
     * @param _command New value for member command
     */
    eProsima_user_DllExport void command(
            int8_t _command)
    {
        m_command = _command;
    }

    /*!
     * @brief This function returns the value of member command
     * @return Value of member command
     */
    eProsima_user_DllExport int8_t command() const
    {
        return m_command;
    }

    /*!
     * @brief This function returns a reference to member command
     * @return Reference to member command
     */
    eProsima_user_DllExport int8_t& command()
    {
        return m_command;
    }



private:

    int8_t m_command{0};

};

} // namespace msg

} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLACONTROL_HPP_


