// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaEgoVehicleTelemetryDataTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "CarlaEgoVehicleTelemetryDataTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "CarlaEgoVehicleTelemetryData.hpp"

#include "CarlaEgoVehicleTelemetryDataWheel.hpp"
#include "std_msgs/msg/Header.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace carla_msgs {
namespace msg {
namespace CarlaEgoVehicleTelemetryData_Constants {
} // namespace CarlaEgoVehicleTelemetryData_Constants
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_CarlaEgoVehicleTelemetryData_type_identifier(
        TypeIdentifierPair& type_ids_CarlaEgoVehicleTelemetryData)
{

    ReturnCode_t return_code_CarlaEgoVehicleTelemetryData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_CarlaEgoVehicleTelemetryData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "carla_msgs::msg::dds_::CarlaEgoVehicleTelemetryData_", type_ids_CarlaEgoVehicleTelemetryData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_CarlaEgoVehicleTelemetryData)
    {
        StructTypeFlag struct_flags_CarlaEgoVehicleTelemetryData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_CarlaEgoVehicleTelemetryData = "carla_msgs::msg::dds_::CarlaEgoVehicleTelemetryData_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_CarlaEgoVehicleTelemetryData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_CarlaEgoVehicleTelemetryData;
        AppliedAnnotationSeq tmp_ann_custom_CarlaEgoVehicleTelemetryData;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_CarlaEgoVehicleTelemetryData;
        PlacementKind placement_CarlaEgoVehicleTelemetryData = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_CarlaEgoVehicleTelemetryData = "*";
        std::string text_CarlaEgoVehicleTelemetryData;
        language_CarlaEgoVehicleTelemetryData = "comment";

        placement_CarlaEgoVehicleTelemetryData = PlacementKind::BEFORE_DECLARATION;

        text_CarlaEgoVehicleTelemetryData = "This work is licensed under the terms of the MIT license.\nFor a copy, see <https://opensource.org/licenses/MIT>.";

        verbatim_CarlaEgoVehicleTelemetryData = TypeObjectUtils::build_applied_verbatim_annotation(placement_CarlaEgoVehicleTelemetryData, language_CarlaEgoVehicleTelemetryData, text_CarlaEgoVehicleTelemetryData);
        type_ann_builtin_CarlaEgoVehicleTelemetryData = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_CarlaEgoVehicleTelemetryData);

        if (!tmp_ann_custom_CarlaEgoVehicleTelemetryData.empty())
        {
            ann_custom_CarlaEgoVehicleTelemetryData = tmp_ann_custom_CarlaEgoVehicleTelemetryData;
        }

        CompleteTypeDetail detail_CarlaEgoVehicleTelemetryData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_CarlaEgoVehicleTelemetryData, ann_custom_CarlaEgoVehicleTelemetryData, type_name_CarlaEgoVehicleTelemetryData.to_string());
        CompleteStructHeader header_CarlaEgoVehicleTelemetryData;
        header_CarlaEgoVehicleTelemetryData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_CarlaEgoVehicleTelemetryData);
        CompleteStructMemberSeq member_seq_CarlaEgoVehicleTelemetryData;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "std_msgs::msg::dds_::Header_", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                std_msgs::msg::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_header);
        }
        {
            TypeIdentifierPair type_ids_speed;
            ReturnCode_t return_code_speed {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_speed);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed = 0x00000001;
            bool common_speed_ec {false};
            CommonStructMember common_speed {TypeObjectUtils::build_common_struct_member(member_id_speed, member_flags_speed, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed, common_speed_ec))};
            if (!common_speed_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed = "speed";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_speed = TypeObjectUtils::build_complete_member_detail(name_speed, member_ann_builtin_speed, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_speed = TypeObjectUtils::build_complete_struct_member(common_speed, detail_speed);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_speed);
        }
        {
            TypeIdentifierPair type_ids_steer;
            ReturnCode_t return_code_steer {eprosima::fastdds::dds::RETCODE_OK};
            return_code_steer =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_steer);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_steer)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "steer Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_steer = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_steer = 0x00000002;
            bool common_steer_ec {false};
            CommonStructMember common_steer {TypeObjectUtils::build_common_struct_member(member_id_steer, member_flags_steer, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_steer, common_steer_ec))};
            if (!common_steer_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure steer member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_steer = "steer";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_steer;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_steer = TypeObjectUtils::build_complete_member_detail(name_steer, member_ann_builtin_steer, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_steer = TypeObjectUtils::build_complete_struct_member(common_steer, detail_steer);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_steer);
        }
        {
            TypeIdentifierPair type_ids_throttle;
            ReturnCode_t return_code_throttle {eprosima::fastdds::dds::RETCODE_OK};
            return_code_throttle =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_throttle);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_throttle)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "throttle Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_throttle = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_throttle = 0x00000003;
            bool common_throttle_ec {false};
            CommonStructMember common_throttle {TypeObjectUtils::build_common_struct_member(member_id_throttle, member_flags_throttle, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_throttle, common_throttle_ec))};
            if (!common_throttle_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure throttle member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_throttle = "throttle";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_throttle;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_throttle = TypeObjectUtils::build_complete_member_detail(name_throttle, member_ann_builtin_throttle, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_throttle = TypeObjectUtils::build_complete_struct_member(common_throttle, detail_throttle);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_throttle);
        }
        {
            TypeIdentifierPair type_ids_brake;
            ReturnCode_t return_code_brake {eprosima::fastdds::dds::RETCODE_OK};
            return_code_brake =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_brake);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_brake)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "brake Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_brake = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_brake = 0x00000004;
            bool common_brake_ec {false};
            CommonStructMember common_brake {TypeObjectUtils::build_common_struct_member(member_id_brake, member_flags_brake, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_brake, common_brake_ec))};
            if (!common_brake_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure brake member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_brake = "brake";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_brake;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_brake = TypeObjectUtils::build_complete_member_detail(name_brake, member_ann_builtin_brake, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_brake = TypeObjectUtils::build_complete_struct_member(common_brake, detail_brake);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_brake);
        }
        {
            TypeIdentifierPair type_ids_engine_rpm;
            ReturnCode_t return_code_engine_rpm {eprosima::fastdds::dds::RETCODE_OK};
            return_code_engine_rpm =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_engine_rpm);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_engine_rpm)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "engine_rpm Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_engine_rpm = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_engine_rpm = 0x00000005;
            bool common_engine_rpm_ec {false};
            CommonStructMember common_engine_rpm {TypeObjectUtils::build_common_struct_member(member_id_engine_rpm, member_flags_engine_rpm, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_engine_rpm, common_engine_rpm_ec))};
            if (!common_engine_rpm_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure engine_rpm member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_engine_rpm = "engine_rpm";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_engine_rpm;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_engine_rpm = TypeObjectUtils::build_complete_member_detail(name_engine_rpm, member_ann_builtin_engine_rpm, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_engine_rpm = TypeObjectUtils::build_complete_struct_member(common_engine_rpm, detail_engine_rpm);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_engine_rpm);
        }
        {
            TypeIdentifierPair type_ids_gear;
            ReturnCode_t return_code_gear {eprosima::fastdds::dds::RETCODE_OK};
            return_code_gear =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_gear);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_gear)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "gear Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_gear = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_gear = 0x00000006;
            bool common_gear_ec {false};
            CommonStructMember common_gear {TypeObjectUtils::build_common_struct_member(member_id_gear, member_flags_gear, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_gear, common_gear_ec))};
            if (!common_gear_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure gear member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_gear = "gear";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_gear;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_gear = TypeObjectUtils::build_complete_member_detail(name_gear, member_ann_builtin_gear, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_gear = TypeObjectUtils::build_complete_struct_member(common_gear, detail_gear);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_gear);
        }
        {
            TypeIdentifierPair type_ids_drag;
            ReturnCode_t return_code_drag {eprosima::fastdds::dds::RETCODE_OK};
            return_code_drag =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_drag);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_drag)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "drag Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_drag = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_drag = 0x00000007;
            bool common_drag_ec {false};
            CommonStructMember common_drag {TypeObjectUtils::build_common_struct_member(member_id_drag, member_flags_drag, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_drag, common_drag_ec))};
            if (!common_drag_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure drag member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_drag = "drag";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_drag;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_drag = TypeObjectUtils::build_complete_member_detail(name_drag, member_ann_builtin_drag, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_drag = TypeObjectUtils::build_complete_struct_member(common_drag, detail_drag);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_drag);
        }
        {
            TypeIdentifierPair type_ids_wheels;
            ReturnCode_t return_code_wheels {eprosima::fastdds::dds::RETCODE_OK};
            return_code_wheels =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded", type_ids_wheels);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_wheels)
            {
                return_code_wheels =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "carla_msgs::msg::dds_::CarlaEgoVehicleTelemetryDataWheel_", type_ids_wheels);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_wheels)
                {
                    carla_msgs::msg::register_CarlaEgoVehicleTelemetryDataWheel_type_identifier(type_ids_wheels);
                }
                bool element_identifier_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_wheels, element_identifier_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_wheels.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded, element_flags_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded", type_ids_wheels))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_carla_msgs_msg_CarlaEgoVehicleTelemetryDataWheel_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_wheels = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_wheels = 0x00000008;
            bool common_wheels_ec {false};
            CommonStructMember common_wheels {TypeObjectUtils::build_common_struct_member(member_id_wheels, member_flags_wheels, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_wheels, common_wheels_ec))};
            if (!common_wheels_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure wheels member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_wheels = "wheels";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_wheels;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            CompleteMemberDetail detail_wheels = TypeObjectUtils::build_complete_member_detail(name_wheels, member_ann_builtin_wheels, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_wheels = TypeObjectUtils::build_complete_struct_member(common_wheels, detail_wheels);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_wheels);
        }
        {
            TypeIdentifierPair type_ids_light_state_flags;
            ReturnCode_t return_code_light_state_flags {eprosima::fastdds::dds::RETCODE_OK};
            return_code_light_state_flags =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_light_state_flags);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_light_state_flags)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "light_state_flags Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_light_state_flags = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_light_state_flags = 0x00000009;
            bool common_light_state_flags_ec {false};
            CommonStructMember common_light_state_flags {TypeObjectUtils::build_common_struct_member(member_id_light_state_flags, member_flags_light_state_flags, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_light_state_flags, common_light_state_flags_ec))};
            if (!common_light_state_flags_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure light_state_flags member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_light_state_flags = "light_state_flags";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_light_state_flags;
            ann_custom_CarlaEgoVehicleTelemetryData.reset();
            AppliedAnnotationSeq tmp_ann_custom_light_state_flags;
            eprosima::fastcdr::optional<std::string> unit_light_state_flags;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_light_state_flags;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_light_state_flags;
            eprosima::fastcdr::optional<std::string> hash_id_light_state_flags;
            if (unit_light_state_flags.has_value() || min_light_state_flags.has_value() || max_light_state_flags.has_value() || hash_id_light_state_flags.has_value())
            {
                member_ann_builtin_light_state_flags = TypeObjectUtils::build_applied_builtin_member_annotations(unit_light_state_flags, min_light_state_flags, max_light_state_flags, hash_id_light_state_flags);
            }
            if (!tmp_ann_custom_light_state_flags.empty())
            {
                ann_custom_CarlaEgoVehicleTelemetryData = tmp_ann_custom_light_state_flags;
            }
            CompleteMemberDetail detail_light_state_flags = TypeObjectUtils::build_complete_member_detail(name_light_state_flags, member_ann_builtin_light_state_flags, ann_custom_CarlaEgoVehicleTelemetryData);
            CompleteStructMember member_light_state_flags = TypeObjectUtils::build_complete_struct_member(common_light_state_flags, detail_light_state_flags);
            TypeObjectUtils::add_complete_struct_member(member_seq_CarlaEgoVehicleTelemetryData, member_light_state_flags);
        }
        CompleteStructType struct_type_CarlaEgoVehicleTelemetryData = TypeObjectUtils::build_complete_struct_type(struct_flags_CarlaEgoVehicleTelemetryData, header_CarlaEgoVehicleTelemetryData, member_seq_CarlaEgoVehicleTelemetryData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_CarlaEgoVehicleTelemetryData, type_name_CarlaEgoVehicleTelemetryData.to_string(), type_ids_CarlaEgoVehicleTelemetryData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "carla_msgs::msg::CarlaEgoVehicleTelemetryData already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace carla_msgs

