// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Float32TypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "Float32TypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Float32.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace std_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Float32_type_identifier(
        TypeIdentifierPair& type_ids_Float32)
{

    ReturnCode_t return_code_Float32 {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Float32 =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "std_msgs::msg::dds_::Float32_", type_ids_Float32);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Float32)
    {
        StructTypeFlag struct_flags_Float32 = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Float32 = "std_msgs::msg::dds_::Float32_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Float32;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Float32;
        AppliedAnnotationSeq tmp_ann_custom_Float32;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_Float32;
        PlacementKind placement_Float32 = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_Float32 = "*";
        std::string text_Float32;
        language_Float32 = "comment";

        placement_Float32 = PlacementKind::BEFORE_DECLARATION;

        text_Float32 = "This was originally provided as an example message.\nIt is deprecated as of Foxy\nIt is recommended to create your own semantically meaningful message.\nHowever if you would like to continue using this please use the equivalent in example_msgs.";

        verbatim_Float32 = TypeObjectUtils::build_applied_verbatim_annotation(placement_Float32, language_Float32, text_Float32);
        type_ann_builtin_Float32 = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_Float32);

        if (!tmp_ann_custom_Float32.empty())
        {
            ann_custom_Float32 = tmp_ann_custom_Float32;
        }

        CompleteTypeDetail detail_Float32 = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Float32, ann_custom_Float32, type_name_Float32.to_string());
        CompleteStructHeader header_Float32;
        header_Float32 = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Float32);
        CompleteStructMemberSeq member_seq_Float32;
        {
            TypeIdentifierPair type_ids_data;
            ReturnCode_t return_code_data {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_data);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "data Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data = 0x00000000;
            bool common_data_ec {false};
            CommonStructMember common_data {TypeObjectUtils::build_common_struct_member(member_id_data, member_flags_data, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
            if (!common_data_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data = "data";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
            ann_custom_Float32.reset();
            CompleteMemberDetail detail_data = TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_Float32);
            CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
            TypeObjectUtils::add_complete_struct_member(member_seq_Float32, member_data);
        }
        CompleteStructType struct_type_Float32 = TypeObjectUtils::build_complete_struct_type(struct_flags_Float32, header_Float32, member_seq_Float32);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Float32, type_name_Float32.to_string(), type_ids_Float32))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "std_msgs::msg::Float32 already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace std_msgs

