// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BasicVehicleContainerHighFrequency.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_BASICVEHICLECONTAINERHIGHFREQUENCY_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_BASICVEHICLECONTAINERHIGHFREQUENCY_HPP

#include <cstdint>
#include <utility>
#include "DriveDirection.hpp"
#include "Speed.hpp"
#include "Heading.hpp"
#include "VehicleWidth.hpp"
#include "CenDsrcTollingZone.hpp"
#include "YawRate.hpp"
#include "VehicleLength.hpp"
#include "CurvatureCalculationMode.hpp"
#include "LanePosition.hpp"
#include "LateralAcceleration.hpp"
#include "VerticalAcceleration.hpp"
#include "SteeringWheelAngle.hpp"
#include "LongitudinalAcceleration.hpp"
#include "Curvature.hpp"
#include "PerformanceClass.hpp"
#include "AccelerationControl.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BASICVEHICLECONTAINERHIGHFREQUENCY_SOURCE)
#define BASICVEHICLECONTAINERHIGHFREQUENCY_DllAPI __declspec( dllexport )
#else
#define BASICVEHICLECONTAINERHIGHFREQUENCY_DllAPI __declspec( dllimport )
#endif // BASICVEHICLECONTAINERHIGHFREQUENCY_SOURCE
#else
#define BASICVEHICLECONTAINERHIGHFREQUENCY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BASICVEHICLECONTAINERHIGHFREQUENCY_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure BasicVehicleContainerHighFrequency defined by the user in the IDL file.
 * @ingroup BasicVehicleContainerHighFrequency
 */
class BasicVehicleContainerHighFrequency
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BasicVehicleContainerHighFrequency()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BasicVehicleContainerHighFrequency()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BasicVehicleContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerHighFrequency(
            const BasicVehicleContainerHighFrequency& x)
    {
                    m_heading = x.m_heading;

                    m_speed = x.m_speed;

                    m_drive_direction = x.m_drive_direction;

                    m_vehicle_length = x.m_vehicle_length;

                    m_vehicle_width = x.m_vehicle_width;

                    m_longitudinal_acceleration = x.m_longitudinal_acceleration;

                    m_curvature = x.m_curvature;

                    m_curvature_calculation_mode = x.m_curvature_calculation_mode;

                    m_yaw_rate = x.m_yaw_rate;

                    m_acceleration_control = x.m_acceleration_control;

                    m_acceleration_control_is_present = x.m_acceleration_control_is_present;

                    m_lane_position = x.m_lane_position;

                    m_lane_position_is_present = x.m_lane_position_is_present;

                    m_steering_wheel_angle = x.m_steering_wheel_angle;

                    m_steering_wheel_angle_is_present = x.m_steering_wheel_angle_is_present;

                    m_lateral_acceleration = x.m_lateral_acceleration;

                    m_lateral_acceleration_is_present = x.m_lateral_acceleration_is_present;

                    m_vertical_acceleration = x.m_vertical_acceleration;

                    m_vertical_acceleration_is_present = x.m_vertical_acceleration_is_present;

                    m_performance_class = x.m_performance_class;

                    m_performance_class_is_present = x.m_performance_class_is_present;

                    m_cen_dsrc_tolling_zone = x.m_cen_dsrc_tolling_zone;

                    m_cen_dsrc_tolling_zone_is_present = x.m_cen_dsrc_tolling_zone_is_present;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BasicVehicleContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerHighFrequency(
            BasicVehicleContainerHighFrequency&& x) noexcept
    {
        m_heading = std::move(x.m_heading);
        m_speed = std::move(x.m_speed);
        m_drive_direction = std::move(x.m_drive_direction);
        m_vehicle_length = std::move(x.m_vehicle_length);
        m_vehicle_width = std::move(x.m_vehicle_width);
        m_longitudinal_acceleration = std::move(x.m_longitudinal_acceleration);
        m_curvature = std::move(x.m_curvature);
        m_curvature_calculation_mode = std::move(x.m_curvature_calculation_mode);
        m_yaw_rate = std::move(x.m_yaw_rate);
        m_acceleration_control = std::move(x.m_acceleration_control);
        m_acceleration_control_is_present = x.m_acceleration_control_is_present;
        m_lane_position = std::move(x.m_lane_position);
        m_lane_position_is_present = x.m_lane_position_is_present;
        m_steering_wheel_angle = std::move(x.m_steering_wheel_angle);
        m_steering_wheel_angle_is_present = x.m_steering_wheel_angle_is_present;
        m_lateral_acceleration = std::move(x.m_lateral_acceleration);
        m_lateral_acceleration_is_present = x.m_lateral_acceleration_is_present;
        m_vertical_acceleration = std::move(x.m_vertical_acceleration);
        m_vertical_acceleration_is_present = x.m_vertical_acceleration_is_present;
        m_performance_class = std::move(x.m_performance_class);
        m_performance_class_is_present = x.m_performance_class_is_present;
        m_cen_dsrc_tolling_zone = std::move(x.m_cen_dsrc_tolling_zone);
        m_cen_dsrc_tolling_zone_is_present = x.m_cen_dsrc_tolling_zone_is_present;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BasicVehicleContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerHighFrequency& operator =(
            const BasicVehicleContainerHighFrequency& x)
    {

                    m_heading = x.m_heading;

                    m_speed = x.m_speed;

                    m_drive_direction = x.m_drive_direction;

                    m_vehicle_length = x.m_vehicle_length;

                    m_vehicle_width = x.m_vehicle_width;

                    m_longitudinal_acceleration = x.m_longitudinal_acceleration;

                    m_curvature = x.m_curvature;

                    m_curvature_calculation_mode = x.m_curvature_calculation_mode;

                    m_yaw_rate = x.m_yaw_rate;

                    m_acceleration_control = x.m_acceleration_control;

                    m_acceleration_control_is_present = x.m_acceleration_control_is_present;

                    m_lane_position = x.m_lane_position;

                    m_lane_position_is_present = x.m_lane_position_is_present;

                    m_steering_wheel_angle = x.m_steering_wheel_angle;

                    m_steering_wheel_angle_is_present = x.m_steering_wheel_angle_is_present;

                    m_lateral_acceleration = x.m_lateral_acceleration;

                    m_lateral_acceleration_is_present = x.m_lateral_acceleration_is_present;

                    m_vertical_acceleration = x.m_vertical_acceleration;

                    m_vertical_acceleration_is_present = x.m_vertical_acceleration_is_present;

                    m_performance_class = x.m_performance_class;

                    m_performance_class_is_present = x.m_performance_class_is_present;

                    m_cen_dsrc_tolling_zone = x.m_cen_dsrc_tolling_zone;

                    m_cen_dsrc_tolling_zone_is_present = x.m_cen_dsrc_tolling_zone_is_present;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BasicVehicleContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerHighFrequency& operator =(
            BasicVehicleContainerHighFrequency&& x) noexcept
    {

        m_heading = std::move(x.m_heading);
        m_speed = std::move(x.m_speed);
        m_drive_direction = std::move(x.m_drive_direction);
        m_vehicle_length = std::move(x.m_vehicle_length);
        m_vehicle_width = std::move(x.m_vehicle_width);
        m_longitudinal_acceleration = std::move(x.m_longitudinal_acceleration);
        m_curvature = std::move(x.m_curvature);
        m_curvature_calculation_mode = std::move(x.m_curvature_calculation_mode);
        m_yaw_rate = std::move(x.m_yaw_rate);
        m_acceleration_control = std::move(x.m_acceleration_control);
        m_acceleration_control_is_present = x.m_acceleration_control_is_present;
        m_lane_position = std::move(x.m_lane_position);
        m_lane_position_is_present = x.m_lane_position_is_present;
        m_steering_wheel_angle = std::move(x.m_steering_wheel_angle);
        m_steering_wheel_angle_is_present = x.m_steering_wheel_angle_is_present;
        m_lateral_acceleration = std::move(x.m_lateral_acceleration);
        m_lateral_acceleration_is_present = x.m_lateral_acceleration_is_present;
        m_vertical_acceleration = std::move(x.m_vertical_acceleration);
        m_vertical_acceleration_is_present = x.m_vertical_acceleration_is_present;
        m_performance_class = std::move(x.m_performance_class);
        m_performance_class_is_present = x.m_performance_class_is_present;
        m_cen_dsrc_tolling_zone = std::move(x.m_cen_dsrc_tolling_zone);
        m_cen_dsrc_tolling_zone_is_present = x.m_cen_dsrc_tolling_zone_is_present;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BasicVehicleContainerHighFrequency object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BasicVehicleContainerHighFrequency& x) const
    {
        return (m_heading == x.m_heading &&
           m_speed == x.m_speed &&
           m_drive_direction == x.m_drive_direction &&
           m_vehicle_length == x.m_vehicle_length &&
           m_vehicle_width == x.m_vehicle_width &&
           m_longitudinal_acceleration == x.m_longitudinal_acceleration &&
           m_curvature == x.m_curvature &&
           m_curvature_calculation_mode == x.m_curvature_calculation_mode &&
           m_yaw_rate == x.m_yaw_rate &&
           m_acceleration_control == x.m_acceleration_control &&
           m_acceleration_control_is_present == x.m_acceleration_control_is_present &&
           m_lane_position == x.m_lane_position &&
           m_lane_position_is_present == x.m_lane_position_is_present &&
           m_steering_wheel_angle == x.m_steering_wheel_angle &&
           m_steering_wheel_angle_is_present == x.m_steering_wheel_angle_is_present &&
           m_lateral_acceleration == x.m_lateral_acceleration &&
           m_lateral_acceleration_is_present == x.m_lateral_acceleration_is_present &&
           m_vertical_acceleration == x.m_vertical_acceleration &&
           m_vertical_acceleration_is_present == x.m_vertical_acceleration_is_present &&
           m_performance_class == x.m_performance_class &&
           m_performance_class_is_present == x.m_performance_class_is_present &&
           m_cen_dsrc_tolling_zone == x.m_cen_dsrc_tolling_zone &&
           m_cen_dsrc_tolling_zone_is_present == x.m_cen_dsrc_tolling_zone_is_present);
    }

    /*!
     * @brief Comparison operator.
     * @param x BasicVehicleContainerHighFrequency object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BasicVehicleContainerHighFrequency& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member heading
     * @param _heading New value to be copied in member heading
     */
    eProsima_user_DllExport void heading(
            const Heading& _heading)
    {
        m_heading = _heading;
    }

    /*!
     * @brief This function moves the value in member heading
     * @param _heading New value to be moved in member heading
     */
    eProsima_user_DllExport void heading(
            Heading&& _heading)
    {
        m_heading = std::move(_heading);
    }

    /*!
     * @brief This function returns a constant reference to member heading
     * @return Constant reference to member heading
     */
    eProsima_user_DllExport const Heading& heading() const
    {
        return m_heading;
    }

    /*!
     * @brief This function returns a reference to member heading
     * @return Reference to member heading
     */
    eProsima_user_DllExport Heading& heading()
    {
        return m_heading;
    }


    /*!
     * @brief This function copies the value in member speed
     * @param _speed New value to be copied in member speed
     */
    eProsima_user_DllExport void speed(
            const Speed& _speed)
    {
        m_speed = _speed;
    }

    /*!
     * @brief This function moves the value in member speed
     * @param _speed New value to be moved in member speed
     */
    eProsima_user_DllExport void speed(
            Speed&& _speed)
    {
        m_speed = std::move(_speed);
    }

    /*!
     * @brief This function returns a constant reference to member speed
     * @return Constant reference to member speed
     */
    eProsima_user_DllExport const Speed& speed() const
    {
        return m_speed;
    }

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport Speed& speed()
    {
        return m_speed;
    }


    /*!
     * @brief This function copies the value in member drive_direction
     * @param _drive_direction New value to be copied in member drive_direction
     */
    eProsima_user_DllExport void drive_direction(
            const DriveDirection& _drive_direction)
    {
        m_drive_direction = _drive_direction;
    }

    /*!
     * @brief This function moves the value in member drive_direction
     * @param _drive_direction New value to be moved in member drive_direction
     */
    eProsima_user_DllExport void drive_direction(
            DriveDirection&& _drive_direction)
    {
        m_drive_direction = std::move(_drive_direction);
    }

    /*!
     * @brief This function returns a constant reference to member drive_direction
     * @return Constant reference to member drive_direction
     */
    eProsima_user_DllExport const DriveDirection& drive_direction() const
    {
        return m_drive_direction;
    }

    /*!
     * @brief This function returns a reference to member drive_direction
     * @return Reference to member drive_direction
     */
    eProsima_user_DllExport DriveDirection& drive_direction()
    {
        return m_drive_direction;
    }


    /*!
     * @brief This function copies the value in member vehicle_length
     * @param _vehicle_length New value to be copied in member vehicle_length
     */
    eProsima_user_DllExport void vehicle_length(
            const VehicleLength& _vehicle_length)
    {
        m_vehicle_length = _vehicle_length;
    }

    /*!
     * @brief This function moves the value in member vehicle_length
     * @param _vehicle_length New value to be moved in member vehicle_length
     */
    eProsima_user_DllExport void vehicle_length(
            VehicleLength&& _vehicle_length)
    {
        m_vehicle_length = std::move(_vehicle_length);
    }

    /*!
     * @brief This function returns a constant reference to member vehicle_length
     * @return Constant reference to member vehicle_length
     */
    eProsima_user_DllExport const VehicleLength& vehicle_length() const
    {
        return m_vehicle_length;
    }

    /*!
     * @brief This function returns a reference to member vehicle_length
     * @return Reference to member vehicle_length
     */
    eProsima_user_DllExport VehicleLength& vehicle_length()
    {
        return m_vehicle_length;
    }


    /*!
     * @brief This function copies the value in member vehicle_width
     * @param _vehicle_width New value to be copied in member vehicle_width
     */
    eProsima_user_DllExport void vehicle_width(
            const VehicleWidth& _vehicle_width)
    {
        m_vehicle_width = _vehicle_width;
    }

    /*!
     * @brief This function moves the value in member vehicle_width
     * @param _vehicle_width New value to be moved in member vehicle_width
     */
    eProsima_user_DllExport void vehicle_width(
            VehicleWidth&& _vehicle_width)
    {
        m_vehicle_width = std::move(_vehicle_width);
    }

    /*!
     * @brief This function returns a constant reference to member vehicle_width
     * @return Constant reference to member vehicle_width
     */
    eProsima_user_DllExport const VehicleWidth& vehicle_width() const
    {
        return m_vehicle_width;
    }

    /*!
     * @brief This function returns a reference to member vehicle_width
     * @return Reference to member vehicle_width
     */
    eProsima_user_DllExport VehicleWidth& vehicle_width()
    {
        return m_vehicle_width;
    }


    /*!
     * @brief This function copies the value in member longitudinal_acceleration
     * @param _longitudinal_acceleration New value to be copied in member longitudinal_acceleration
     */
    eProsima_user_DllExport void longitudinal_acceleration(
            const LongitudinalAcceleration& _longitudinal_acceleration)
    {
        m_longitudinal_acceleration = _longitudinal_acceleration;
    }

    /*!
     * @brief This function moves the value in member longitudinal_acceleration
     * @param _longitudinal_acceleration New value to be moved in member longitudinal_acceleration
     */
    eProsima_user_DllExport void longitudinal_acceleration(
            LongitudinalAcceleration&& _longitudinal_acceleration)
    {
        m_longitudinal_acceleration = std::move(_longitudinal_acceleration);
    }

    /*!
     * @brief This function returns a constant reference to member longitudinal_acceleration
     * @return Constant reference to member longitudinal_acceleration
     */
    eProsima_user_DllExport const LongitudinalAcceleration& longitudinal_acceleration() const
    {
        return m_longitudinal_acceleration;
    }

    /*!
     * @brief This function returns a reference to member longitudinal_acceleration
     * @return Reference to member longitudinal_acceleration
     */
    eProsima_user_DllExport LongitudinalAcceleration& longitudinal_acceleration()
    {
        return m_longitudinal_acceleration;
    }


    /*!
     * @brief This function copies the value in member curvature
     * @param _curvature New value to be copied in member curvature
     */
    eProsima_user_DllExport void curvature(
            const Curvature& _curvature)
    {
        m_curvature = _curvature;
    }

    /*!
     * @brief This function moves the value in member curvature
     * @param _curvature New value to be moved in member curvature
     */
    eProsima_user_DllExport void curvature(
            Curvature&& _curvature)
    {
        m_curvature = std::move(_curvature);
    }

    /*!
     * @brief This function returns a constant reference to member curvature
     * @return Constant reference to member curvature
     */
    eProsima_user_DllExport const Curvature& curvature() const
    {
        return m_curvature;
    }

    /*!
     * @brief This function returns a reference to member curvature
     * @return Reference to member curvature
     */
    eProsima_user_DllExport Curvature& curvature()
    {
        return m_curvature;
    }


    /*!
     * @brief This function copies the value in member curvature_calculation_mode
     * @param _curvature_calculation_mode New value to be copied in member curvature_calculation_mode
     */
    eProsima_user_DllExport void curvature_calculation_mode(
            const CurvatureCalculationMode& _curvature_calculation_mode)
    {
        m_curvature_calculation_mode = _curvature_calculation_mode;
    }

    /*!
     * @brief This function moves the value in member curvature_calculation_mode
     * @param _curvature_calculation_mode New value to be moved in member curvature_calculation_mode
     */
    eProsima_user_DllExport void curvature_calculation_mode(
            CurvatureCalculationMode&& _curvature_calculation_mode)
    {
        m_curvature_calculation_mode = std::move(_curvature_calculation_mode);
    }

    /*!
     * @brief This function returns a constant reference to member curvature_calculation_mode
     * @return Constant reference to member curvature_calculation_mode
     */
    eProsima_user_DllExport const CurvatureCalculationMode& curvature_calculation_mode() const
    {
        return m_curvature_calculation_mode;
    }

    /*!
     * @brief This function returns a reference to member curvature_calculation_mode
     * @return Reference to member curvature_calculation_mode
     */
    eProsima_user_DllExport CurvatureCalculationMode& curvature_calculation_mode()
    {
        return m_curvature_calculation_mode;
    }


    /*!
     * @brief This function copies the value in member yaw_rate
     * @param _yaw_rate New value to be copied in member yaw_rate
     */
    eProsima_user_DllExport void yaw_rate(
            const YawRate& _yaw_rate)
    {
        m_yaw_rate = _yaw_rate;
    }

    /*!
     * @brief This function moves the value in member yaw_rate
     * @param _yaw_rate New value to be moved in member yaw_rate
     */
    eProsima_user_DllExport void yaw_rate(
            YawRate&& _yaw_rate)
    {
        m_yaw_rate = std::move(_yaw_rate);
    }

    /*!
     * @brief This function returns a constant reference to member yaw_rate
     * @return Constant reference to member yaw_rate
     */
    eProsima_user_DllExport const YawRate& yaw_rate() const
    {
        return m_yaw_rate;
    }

    /*!
     * @brief This function returns a reference to member yaw_rate
     * @return Reference to member yaw_rate
     */
    eProsima_user_DllExport YawRate& yaw_rate()
    {
        return m_yaw_rate;
    }


    /*!
     * @brief This function copies the value in member acceleration_control
     * @param _acceleration_control New value to be copied in member acceleration_control
     */
    eProsima_user_DllExport void acceleration_control(
            const AccelerationControl& _acceleration_control)
    {
        m_acceleration_control = _acceleration_control;
    }

    /*!
     * @brief This function moves the value in member acceleration_control
     * @param _acceleration_control New value to be moved in member acceleration_control
     */
    eProsima_user_DllExport void acceleration_control(
            AccelerationControl&& _acceleration_control)
    {
        m_acceleration_control = std::move(_acceleration_control);
    }

    /*!
     * @brief This function returns a constant reference to member acceleration_control
     * @return Constant reference to member acceleration_control
     */
    eProsima_user_DllExport const AccelerationControl& acceleration_control() const
    {
        return m_acceleration_control;
    }

    /*!
     * @brief This function returns a reference to member acceleration_control
     * @return Reference to member acceleration_control
     */
    eProsima_user_DllExport AccelerationControl& acceleration_control()
    {
        return m_acceleration_control;
    }


    /*!
     * @brief This function sets a value in member acceleration_control_is_present
     * @param _acceleration_control_is_present New value for member acceleration_control_is_present
     */
    eProsima_user_DllExport void acceleration_control_is_present(
            bool _acceleration_control_is_present)
    {
        m_acceleration_control_is_present = _acceleration_control_is_present;
    }

    /*!
     * @brief This function returns the value of member acceleration_control_is_present
     * @return Value of member acceleration_control_is_present
     */
    eProsima_user_DllExport bool acceleration_control_is_present() const
    {
        return m_acceleration_control_is_present;
    }

    /*!
     * @brief This function returns a reference to member acceleration_control_is_present
     * @return Reference to member acceleration_control_is_present
     */
    eProsima_user_DllExport bool& acceleration_control_is_present()
    {
        return m_acceleration_control_is_present;
    }


    /*!
     * @brief This function copies the value in member lane_position
     * @param _lane_position New value to be copied in member lane_position
     */
    eProsima_user_DllExport void lane_position(
            const LanePosition& _lane_position)
    {
        m_lane_position = _lane_position;
    }

    /*!
     * @brief This function moves the value in member lane_position
     * @param _lane_position New value to be moved in member lane_position
     */
    eProsima_user_DllExport void lane_position(
            LanePosition&& _lane_position)
    {
        m_lane_position = std::move(_lane_position);
    }

    /*!
     * @brief This function returns a constant reference to member lane_position
     * @return Constant reference to member lane_position
     */
    eProsima_user_DllExport const LanePosition& lane_position() const
    {
        return m_lane_position;
    }

    /*!
     * @brief This function returns a reference to member lane_position
     * @return Reference to member lane_position
     */
    eProsima_user_DllExport LanePosition& lane_position()
    {
        return m_lane_position;
    }


    /*!
     * @brief This function sets a value in member lane_position_is_present
     * @param _lane_position_is_present New value for member lane_position_is_present
     */
    eProsima_user_DllExport void lane_position_is_present(
            bool _lane_position_is_present)
    {
        m_lane_position_is_present = _lane_position_is_present;
    }

    /*!
     * @brief This function returns the value of member lane_position_is_present
     * @return Value of member lane_position_is_present
     */
    eProsima_user_DllExport bool lane_position_is_present() const
    {
        return m_lane_position_is_present;
    }

    /*!
     * @brief This function returns a reference to member lane_position_is_present
     * @return Reference to member lane_position_is_present
     */
    eProsima_user_DllExport bool& lane_position_is_present()
    {
        return m_lane_position_is_present;
    }


    /*!
     * @brief This function copies the value in member steering_wheel_angle
     * @param _steering_wheel_angle New value to be copied in member steering_wheel_angle
     */
    eProsima_user_DllExport void steering_wheel_angle(
            const SteeringWheelAngle& _steering_wheel_angle)
    {
        m_steering_wheel_angle = _steering_wheel_angle;
    }

    /*!
     * @brief This function moves the value in member steering_wheel_angle
     * @param _steering_wheel_angle New value to be moved in member steering_wheel_angle
     */
    eProsima_user_DllExport void steering_wheel_angle(
            SteeringWheelAngle&& _steering_wheel_angle)
    {
        m_steering_wheel_angle = std::move(_steering_wheel_angle);
    }

    /*!
     * @brief This function returns a constant reference to member steering_wheel_angle
     * @return Constant reference to member steering_wheel_angle
     */
    eProsima_user_DllExport const SteeringWheelAngle& steering_wheel_angle() const
    {
        return m_steering_wheel_angle;
    }

    /*!
     * @brief This function returns a reference to member steering_wheel_angle
     * @return Reference to member steering_wheel_angle
     */
    eProsima_user_DllExport SteeringWheelAngle& steering_wheel_angle()
    {
        return m_steering_wheel_angle;
    }


    /*!
     * @brief This function sets a value in member steering_wheel_angle_is_present
     * @param _steering_wheel_angle_is_present New value for member steering_wheel_angle_is_present
     */
    eProsima_user_DllExport void steering_wheel_angle_is_present(
            bool _steering_wheel_angle_is_present)
    {
        m_steering_wheel_angle_is_present = _steering_wheel_angle_is_present;
    }

    /*!
     * @brief This function returns the value of member steering_wheel_angle_is_present
     * @return Value of member steering_wheel_angle_is_present
     */
    eProsima_user_DllExport bool steering_wheel_angle_is_present() const
    {
        return m_steering_wheel_angle_is_present;
    }

    /*!
     * @brief This function returns a reference to member steering_wheel_angle_is_present
     * @return Reference to member steering_wheel_angle_is_present
     */
    eProsima_user_DllExport bool& steering_wheel_angle_is_present()
    {
        return m_steering_wheel_angle_is_present;
    }


    /*!
     * @brief This function copies the value in member lateral_acceleration
     * @param _lateral_acceleration New value to be copied in member lateral_acceleration
     */
    eProsima_user_DllExport void lateral_acceleration(
            const LateralAcceleration& _lateral_acceleration)
    {
        m_lateral_acceleration = _lateral_acceleration;
    }

    /*!
     * @brief This function moves the value in member lateral_acceleration
     * @param _lateral_acceleration New value to be moved in member lateral_acceleration
     */
    eProsima_user_DllExport void lateral_acceleration(
            LateralAcceleration&& _lateral_acceleration)
    {
        m_lateral_acceleration = std::move(_lateral_acceleration);
    }

    /*!
     * @brief This function returns a constant reference to member lateral_acceleration
     * @return Constant reference to member lateral_acceleration
     */
    eProsima_user_DllExport const LateralAcceleration& lateral_acceleration() const
    {
        return m_lateral_acceleration;
    }

    /*!
     * @brief This function returns a reference to member lateral_acceleration
     * @return Reference to member lateral_acceleration
     */
    eProsima_user_DllExport LateralAcceleration& lateral_acceleration()
    {
        return m_lateral_acceleration;
    }


    /*!
     * @brief This function sets a value in member lateral_acceleration_is_present
     * @param _lateral_acceleration_is_present New value for member lateral_acceleration_is_present
     */
    eProsima_user_DllExport void lateral_acceleration_is_present(
            bool _lateral_acceleration_is_present)
    {
        m_lateral_acceleration_is_present = _lateral_acceleration_is_present;
    }

    /*!
     * @brief This function returns the value of member lateral_acceleration_is_present
     * @return Value of member lateral_acceleration_is_present
     */
    eProsima_user_DllExport bool lateral_acceleration_is_present() const
    {
        return m_lateral_acceleration_is_present;
    }

    /*!
     * @brief This function returns a reference to member lateral_acceleration_is_present
     * @return Reference to member lateral_acceleration_is_present
     */
    eProsima_user_DllExport bool& lateral_acceleration_is_present()
    {
        return m_lateral_acceleration_is_present;
    }


    /*!
     * @brief This function copies the value in member vertical_acceleration
     * @param _vertical_acceleration New value to be copied in member vertical_acceleration
     */
    eProsima_user_DllExport void vertical_acceleration(
            const VerticalAcceleration& _vertical_acceleration)
    {
        m_vertical_acceleration = _vertical_acceleration;
    }

    /*!
     * @brief This function moves the value in member vertical_acceleration
     * @param _vertical_acceleration New value to be moved in member vertical_acceleration
     */
    eProsima_user_DllExport void vertical_acceleration(
            VerticalAcceleration&& _vertical_acceleration)
    {
        m_vertical_acceleration = std::move(_vertical_acceleration);
    }

    /*!
     * @brief This function returns a constant reference to member vertical_acceleration
     * @return Constant reference to member vertical_acceleration
     */
    eProsima_user_DllExport const VerticalAcceleration& vertical_acceleration() const
    {
        return m_vertical_acceleration;
    }

    /*!
     * @brief This function returns a reference to member vertical_acceleration
     * @return Reference to member vertical_acceleration
     */
    eProsima_user_DllExport VerticalAcceleration& vertical_acceleration()
    {
        return m_vertical_acceleration;
    }


    /*!
     * @brief This function sets a value in member vertical_acceleration_is_present
     * @param _vertical_acceleration_is_present New value for member vertical_acceleration_is_present
     */
    eProsima_user_DllExport void vertical_acceleration_is_present(
            bool _vertical_acceleration_is_present)
    {
        m_vertical_acceleration_is_present = _vertical_acceleration_is_present;
    }

    /*!
     * @brief This function returns the value of member vertical_acceleration_is_present
     * @return Value of member vertical_acceleration_is_present
     */
    eProsima_user_DllExport bool vertical_acceleration_is_present() const
    {
        return m_vertical_acceleration_is_present;
    }

    /*!
     * @brief This function returns a reference to member vertical_acceleration_is_present
     * @return Reference to member vertical_acceleration_is_present
     */
    eProsima_user_DllExport bool& vertical_acceleration_is_present()
    {
        return m_vertical_acceleration_is_present;
    }


    /*!
     * @brief This function copies the value in member performance_class
     * @param _performance_class New value to be copied in member performance_class
     */
    eProsima_user_DllExport void performance_class(
            const PerformanceClass& _performance_class)
    {
        m_performance_class = _performance_class;
    }

    /*!
     * @brief This function moves the value in member performance_class
     * @param _performance_class New value to be moved in member performance_class
     */
    eProsima_user_DllExport void performance_class(
            PerformanceClass&& _performance_class)
    {
        m_performance_class = std::move(_performance_class);
    }

    /*!
     * @brief This function returns a constant reference to member performance_class
     * @return Constant reference to member performance_class
     */
    eProsima_user_DllExport const PerformanceClass& performance_class() const
    {
        return m_performance_class;
    }

    /*!
     * @brief This function returns a reference to member performance_class
     * @return Reference to member performance_class
     */
    eProsima_user_DllExport PerformanceClass& performance_class()
    {
        return m_performance_class;
    }


    /*!
     * @brief This function sets a value in member performance_class_is_present
     * @param _performance_class_is_present New value for member performance_class_is_present
     */
    eProsima_user_DllExport void performance_class_is_present(
            bool _performance_class_is_present)
    {
        m_performance_class_is_present = _performance_class_is_present;
    }

    /*!
     * @brief This function returns the value of member performance_class_is_present
     * @return Value of member performance_class_is_present
     */
    eProsima_user_DllExport bool performance_class_is_present() const
    {
        return m_performance_class_is_present;
    }

    /*!
     * @brief This function returns a reference to member performance_class_is_present
     * @return Reference to member performance_class_is_present
     */
    eProsima_user_DllExport bool& performance_class_is_present()
    {
        return m_performance_class_is_present;
    }


    /*!
     * @brief This function copies the value in member cen_dsrc_tolling_zone
     * @param _cen_dsrc_tolling_zone New value to be copied in member cen_dsrc_tolling_zone
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone(
            const CenDsrcTollingZone& _cen_dsrc_tolling_zone)
    {
        m_cen_dsrc_tolling_zone = _cen_dsrc_tolling_zone;
    }

    /*!
     * @brief This function moves the value in member cen_dsrc_tolling_zone
     * @param _cen_dsrc_tolling_zone New value to be moved in member cen_dsrc_tolling_zone
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone(
            CenDsrcTollingZone&& _cen_dsrc_tolling_zone)
    {
        m_cen_dsrc_tolling_zone = std::move(_cen_dsrc_tolling_zone);
    }

    /*!
     * @brief This function returns a constant reference to member cen_dsrc_tolling_zone
     * @return Constant reference to member cen_dsrc_tolling_zone
     */
    eProsima_user_DllExport const CenDsrcTollingZone& cen_dsrc_tolling_zone() const
    {
        return m_cen_dsrc_tolling_zone;
    }

    /*!
     * @brief This function returns a reference to member cen_dsrc_tolling_zone
     * @return Reference to member cen_dsrc_tolling_zone
     */
    eProsima_user_DllExport CenDsrcTollingZone& cen_dsrc_tolling_zone()
    {
        return m_cen_dsrc_tolling_zone;
    }


    /*!
     * @brief This function sets a value in member cen_dsrc_tolling_zone_is_present
     * @param _cen_dsrc_tolling_zone_is_present New value for member cen_dsrc_tolling_zone_is_present
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_is_present(
            bool _cen_dsrc_tolling_zone_is_present)
    {
        m_cen_dsrc_tolling_zone_is_present = _cen_dsrc_tolling_zone_is_present;
    }

    /*!
     * @brief This function returns the value of member cen_dsrc_tolling_zone_is_present
     * @return Value of member cen_dsrc_tolling_zone_is_present
     */
    eProsima_user_DllExport bool cen_dsrc_tolling_zone_is_present() const
    {
        return m_cen_dsrc_tolling_zone_is_present;
    }

    /*!
     * @brief This function returns a reference to member cen_dsrc_tolling_zone_is_present
     * @return Reference to member cen_dsrc_tolling_zone_is_present
     */
    eProsima_user_DllExport bool& cen_dsrc_tolling_zone_is_present()
    {
        return m_cen_dsrc_tolling_zone_is_present;
    }



private:

    Heading m_heading;
    Speed m_speed;
    DriveDirection m_drive_direction;
    VehicleLength m_vehicle_length;
    VehicleWidth m_vehicle_width;
    LongitudinalAcceleration m_longitudinal_acceleration;
    Curvature m_curvature;
    CurvatureCalculationMode m_curvature_calculation_mode;
    YawRate m_yaw_rate;
    AccelerationControl m_acceleration_control;
    bool m_acceleration_control_is_present{false};
    LanePosition m_lane_position;
    bool m_lane_position_is_present{false};
    SteeringWheelAngle m_steering_wheel_angle;
    bool m_steering_wheel_angle_is_present{false};
    LateralAcceleration m_lateral_acceleration;
    bool m_lateral_acceleration_is_present{false};
    VerticalAcceleration m_vertical_acceleration;
    bool m_vertical_acceleration_is_present{false};
    PerformanceClass m_performance_class;
    bool m_performance_class_is_present{false};
    CenDsrcTollingZone m_cen_dsrc_tolling_zone;
    bool m_cen_dsrc_tolling_zone_is_present{false};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_BASICVEHICLECONTAINERHIGHFREQUENCY_HPP_


