// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BasicVehicleContainerLowFrequency.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_BASICVEHICLECONTAINERLOWFREQUENCY_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_BASICVEHICLECONTAINERLOWFREQUENCY_HPP

#include <cstdint>
#include <utility>
#include "VehicleRole.hpp"
#include "ExteriorLights.hpp"
#include "PathHistory.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BASICVEHICLECONTAINERLOWFREQUENCY_SOURCE)
#define BASICVEHICLECONTAINERLOWFREQUENCY_DllAPI __declspec( dllexport )
#else
#define BASICVEHICLECONTAINERLOWFREQUENCY_DllAPI __declspec( dllimport )
#endif // BASICVEHICLECONTAINERLOWFREQUENCY_SOURCE
#else
#define BASICVEHICLECONTAINERLOWFREQUENCY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BASICVEHICLECONTAINERLOWFREQUENCY_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure BasicVehicleContainerLowFrequency defined by the user in the IDL file.
 * @ingroup BasicVehicleContainerLowFrequency
 */
class BasicVehicleContainerLowFrequency
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BasicVehicleContainerLowFrequency()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BasicVehicleContainerLowFrequency()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BasicVehicleContainerLowFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerLowFrequency(
            const BasicVehicleContainerLowFrequency& x)
    {
                    m_vehicle_role = x.m_vehicle_role;

                    m_exterior_lights = x.m_exterior_lights;

                    m_path_history = x.m_path_history;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BasicVehicleContainerLowFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerLowFrequency(
            BasicVehicleContainerLowFrequency&& x) noexcept
    {
        m_vehicle_role = std::move(x.m_vehicle_role);
        m_exterior_lights = std::move(x.m_exterior_lights);
        m_path_history = std::move(x.m_path_history);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BasicVehicleContainerLowFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerLowFrequency& operator =(
            const BasicVehicleContainerLowFrequency& x)
    {

                    m_vehicle_role = x.m_vehicle_role;

                    m_exterior_lights = x.m_exterior_lights;

                    m_path_history = x.m_path_history;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BasicVehicleContainerLowFrequency that will be copied.
     */
    eProsima_user_DllExport BasicVehicleContainerLowFrequency& operator =(
            BasicVehicleContainerLowFrequency&& x) noexcept
    {

        m_vehicle_role = std::move(x.m_vehicle_role);
        m_exterior_lights = std::move(x.m_exterior_lights);
        m_path_history = std::move(x.m_path_history);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BasicVehicleContainerLowFrequency object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BasicVehicleContainerLowFrequency& x) const
    {
        return (m_vehicle_role == x.m_vehicle_role &&
           m_exterior_lights == x.m_exterior_lights &&
           m_path_history == x.m_path_history);
    }

    /*!
     * @brief Comparison operator.
     * @param x BasicVehicleContainerLowFrequency object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BasicVehicleContainerLowFrequency& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member vehicle_role
     * @param _vehicle_role New value to be copied in member vehicle_role
     */
    eProsima_user_DllExport void vehicle_role(
            const VehicleRole& _vehicle_role)
    {
        m_vehicle_role = _vehicle_role;
    }

    /*!
     * @brief This function moves the value in member vehicle_role
     * @param _vehicle_role New value to be moved in member vehicle_role
     */
    eProsima_user_DllExport void vehicle_role(
            VehicleRole&& _vehicle_role)
    {
        m_vehicle_role = std::move(_vehicle_role);
    }

    /*!
     * @brief This function returns a constant reference to member vehicle_role
     * @return Constant reference to member vehicle_role
     */
    eProsima_user_DllExport const VehicleRole& vehicle_role() const
    {
        return m_vehicle_role;
    }

    /*!
     * @brief This function returns a reference to member vehicle_role
     * @return Reference to member vehicle_role
     */
    eProsima_user_DllExport VehicleRole& vehicle_role()
    {
        return m_vehicle_role;
    }


    /*!
     * @brief This function copies the value in member exterior_lights
     * @param _exterior_lights New value to be copied in member exterior_lights
     */
    eProsima_user_DllExport void exterior_lights(
            const ExteriorLights& _exterior_lights)
    {
        m_exterior_lights = _exterior_lights;
    }

    /*!
     * @brief This function moves the value in member exterior_lights
     * @param _exterior_lights New value to be moved in member exterior_lights
     */
    eProsima_user_DllExport void exterior_lights(
            ExteriorLights&& _exterior_lights)
    {
        m_exterior_lights = std::move(_exterior_lights);
    }

    /*!
     * @brief This function returns a constant reference to member exterior_lights
     * @return Constant reference to member exterior_lights
     */
    eProsima_user_DllExport const ExteriorLights& exterior_lights() const
    {
        return m_exterior_lights;
    }

    /*!
     * @brief This function returns a reference to member exterior_lights
     * @return Reference to member exterior_lights
     */
    eProsima_user_DllExport ExteriorLights& exterior_lights()
    {
        return m_exterior_lights;
    }


    /*!
     * @brief This function copies the value in member path_history
     * @param _path_history New value to be copied in member path_history
     */
    eProsima_user_DllExport void path_history(
            const PathHistory& _path_history)
    {
        m_path_history = _path_history;
    }

    /*!
     * @brief This function moves the value in member path_history
     * @param _path_history New value to be moved in member path_history
     */
    eProsima_user_DllExport void path_history(
            PathHistory&& _path_history)
    {
        m_path_history = std::move(_path_history);
    }

    /*!
     * @brief This function returns a constant reference to member path_history
     * @return Constant reference to member path_history
     */
    eProsima_user_DllExport const PathHistory& path_history() const
    {
        return m_path_history;
    }

    /*!
     * @brief This function returns a reference to member path_history
     * @return Reference to member path_history
     */
    eProsima_user_DllExport PathHistory& path_history()
    {
        return m_path_history;
    }



private:

    VehicleRole m_vehicle_role;
    ExteriorLights m_exterior_lights;
    PathHistory m_path_history;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_BASICVEHICLECONTAINERLOWFREQUENCY_HPP_


