// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CAM.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_CAM_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_CAM_HPP

#include <cstdint>
#include <utility>
#include "ItsPduHeader.hpp"
#include "CoopAwareness.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CAM_SOURCE)
#define CAM_DllAPI __declspec( dllexport )
#else
#define CAM_DllAPI __declspec( dllimport )
#endif // CAM_SOURCE
#else
#define CAM_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CAM_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CAM defined by the user in the IDL file.
 * @ingroup CAM
 */
class CAM
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CAM()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CAM()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CAM that will be copied.
     */
    eProsima_user_DllExport CAM(
            const CAM& x)
    {
                    m_header = x.m_header;

                    m_cam = x.m_cam;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CAM that will be copied.
     */
    eProsima_user_DllExport CAM(
            CAM&& x) noexcept
    {
        m_header = std::move(x.m_header);
        m_cam = std::move(x.m_cam);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CAM that will be copied.
     */
    eProsima_user_DllExport CAM& operator =(
            const CAM& x)
    {

                    m_header = x.m_header;

                    m_cam = x.m_cam;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CAM that will be copied.
     */
    eProsima_user_DllExport CAM& operator =(
            CAM&& x) noexcept
    {

        m_header = std::move(x.m_header);
        m_cam = std::move(x.m_cam);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CAM object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CAM& x) const
    {
        return (m_header == x.m_header &&
           m_cam == x.m_cam);
    }

    /*!
     * @brief Comparison operator.
     * @param x CAM object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CAM& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const ItsPduHeader& _header)
    {
        m_header = _header;
    }

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            ItsPduHeader&& _header)
    {
        m_header = std::move(_header);
    }

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const ItsPduHeader& header() const
    {
        return m_header;
    }

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport ItsPduHeader& header()
    {
        return m_header;
    }


    /*!
     * @brief This function copies the value in member cam
     * @param _cam New value to be copied in member cam
     */
    eProsima_user_DllExport void cam(
            const CoopAwareness& _cam)
    {
        m_cam = _cam;
    }

    /*!
     * @brief This function moves the value in member cam
     * @param _cam New value to be moved in member cam
     */
    eProsima_user_DllExport void cam(
            CoopAwareness&& _cam)
    {
        m_cam = std::move(_cam);
    }

    /*!
     * @brief This function returns a constant reference to member cam
     * @return Constant reference to member cam
     */
    eProsima_user_DllExport const CoopAwareness& cam() const
    {
        return m_cam;
    }

    /*!
     * @brief This function returns a reference to member cam
     * @return Reference to member cam
     */
    eProsima_user_DllExport CoopAwareness& cam()
    {
        return m_cam;
    }



private:

    ItsPduHeader m_header;
    CoopAwareness m_cam;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_CAM_HPP_


