// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CamParametersTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "CamParametersTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "CamParameters.hpp"

#include "SpecialVehicleContainer.hpp"
#include "BasicContainer.hpp"
#include "HighFrequencyContainer.hpp"
#include "LowFrequencyContainer.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace etsi_its_cam_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_CamParameters_type_identifier(
        TypeIdentifierPair& type_ids_CamParameters)
{

    ReturnCode_t return_code_CamParameters {eprosima::fastdds::dds::RETCODE_OK};
    return_code_CamParameters =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "etsi_its_cam_msgs::msg::dds_::CamParameters_", type_ids_CamParameters);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_CamParameters)
    {
        StructTypeFlag struct_flags_CamParameters = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_CamParameters = "etsi_its_cam_msgs::msg::dds_::CamParameters_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_CamParameters;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_CamParameters;
        AppliedAnnotationSeq tmp_ann_custom_CamParameters;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_CamParameters;
        PlacementKind placement_CamParameters = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_CamParameters = "*";
        std::string text_CamParameters;
        language_CamParameters = "comment";

        placement_CamParameters = PlacementKind::BEFORE_DECLARATION;

        text_CamParameters = "==============================================================================\nMIT License\n\nCopyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n==============================================================================";

        verbatim_CamParameters = TypeObjectUtils::build_applied_verbatim_annotation(placement_CamParameters, language_CamParameters, text_CamParameters);
        type_ann_builtin_CamParameters = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_CamParameters);

        if (!tmp_ann_custom_CamParameters.empty())
        {
            ann_custom_CamParameters = tmp_ann_custom_CamParameters;
        }

        CompleteTypeDetail detail_CamParameters = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_CamParameters, ann_custom_CamParameters, type_name_CamParameters.to_string());
        CompleteStructHeader header_CamParameters;
        header_CamParameters = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_CamParameters);
        CompleteStructMemberSeq member_seq_CamParameters;
        {
            TypeIdentifierPair type_ids_basic_container;
            ReturnCode_t return_code_basic_container {eprosima::fastdds::dds::RETCODE_OK};
            return_code_basic_container =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::BasicContainer_", type_ids_basic_container);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_basic_container)
            {
                etsi_its_cam_msgs::msg::register_BasicContainer_type_identifier(type_ids_basic_container);
            }
            StructMemberFlag member_flags_basic_container = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_basic_container = 0x00000000;
            bool common_basic_container_ec {false};
            CommonStructMember common_basic_container {TypeObjectUtils::build_common_struct_member(member_id_basic_container, member_flags_basic_container, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_basic_container, common_basic_container_ec))};
            if (!common_basic_container_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure basic_container member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_basic_container = "basic_container";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_basic_container;
            ann_custom_CamParameters.reset();
            AppliedAnnotationSeq tmp_ann_custom_basic_container;
            eprosima::fastcdr::optional<std::string> unit_basic_container;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_basic_container;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_basic_container;
            eprosima::fastcdr::optional<std::string> hash_id_basic_container;
            if (unit_basic_container.has_value() || min_basic_container.has_value() || max_basic_container.has_value() || hash_id_basic_container.has_value())
            {
                member_ann_builtin_basic_container = TypeObjectUtils::build_applied_builtin_member_annotations(unit_basic_container, min_basic_container, max_basic_container, hash_id_basic_container);
            }
            if (!tmp_ann_custom_basic_container.empty())
            {
                ann_custom_CamParameters = tmp_ann_custom_basic_container;
            }
            CompleteMemberDetail detail_basic_container = TypeObjectUtils::build_complete_member_detail(name_basic_container, member_ann_builtin_basic_container, ann_custom_CamParameters);
            CompleteStructMember member_basic_container = TypeObjectUtils::build_complete_struct_member(common_basic_container, detail_basic_container);
            TypeObjectUtils::add_complete_struct_member(member_seq_CamParameters, member_basic_container);
        }
        {
            TypeIdentifierPair type_ids_high_frequency_container;
            ReturnCode_t return_code_high_frequency_container {eprosima::fastdds::dds::RETCODE_OK};
            return_code_high_frequency_container =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::HighFrequencyContainer_", type_ids_high_frequency_container);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_high_frequency_container)
            {
                etsi_its_cam_msgs::msg::register_HighFrequencyContainer_type_identifier(type_ids_high_frequency_container);
            }
            StructMemberFlag member_flags_high_frequency_container = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_high_frequency_container = 0x00000001;
            bool common_high_frequency_container_ec {false};
            CommonStructMember common_high_frequency_container {TypeObjectUtils::build_common_struct_member(member_id_high_frequency_container, member_flags_high_frequency_container, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_high_frequency_container, common_high_frequency_container_ec))};
            if (!common_high_frequency_container_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure high_frequency_container member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_high_frequency_container = "high_frequency_container";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_high_frequency_container;
            ann_custom_CamParameters.reset();
            CompleteMemberDetail detail_high_frequency_container = TypeObjectUtils::build_complete_member_detail(name_high_frequency_container, member_ann_builtin_high_frequency_container, ann_custom_CamParameters);
            CompleteStructMember member_high_frequency_container = TypeObjectUtils::build_complete_struct_member(common_high_frequency_container, detail_high_frequency_container);
            TypeObjectUtils::add_complete_struct_member(member_seq_CamParameters, member_high_frequency_container);
        }
        {
            TypeIdentifierPair type_ids_low_frequency_container;
            ReturnCode_t return_code_low_frequency_container {eprosima::fastdds::dds::RETCODE_OK};
            return_code_low_frequency_container =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::LowFrequencyContainer_", type_ids_low_frequency_container);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_low_frequency_container)
            {
                etsi_its_cam_msgs::msg::register_LowFrequencyContainer_type_identifier(type_ids_low_frequency_container);
            }
            StructMemberFlag member_flags_low_frequency_container = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_low_frequency_container = 0x00000002;
            bool common_low_frequency_container_ec {false};
            CommonStructMember common_low_frequency_container {TypeObjectUtils::build_common_struct_member(member_id_low_frequency_container, member_flags_low_frequency_container, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_low_frequency_container, common_low_frequency_container_ec))};
            if (!common_low_frequency_container_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure low_frequency_container member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_low_frequency_container = "low_frequency_container";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_low_frequency_container;
            ann_custom_CamParameters.reset();
            CompleteMemberDetail detail_low_frequency_container = TypeObjectUtils::build_complete_member_detail(name_low_frequency_container, member_ann_builtin_low_frequency_container, ann_custom_CamParameters);
            CompleteStructMember member_low_frequency_container = TypeObjectUtils::build_complete_struct_member(common_low_frequency_container, detail_low_frequency_container);
            TypeObjectUtils::add_complete_struct_member(member_seq_CamParameters, member_low_frequency_container);
        }
        {
            TypeIdentifierPair type_ids_low_frequency_container_is_present;
            ReturnCode_t return_code_low_frequency_container_is_present {eprosima::fastdds::dds::RETCODE_OK};
            return_code_low_frequency_container_is_present =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_low_frequency_container_is_present);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_low_frequency_container_is_present)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "low_frequency_container_is_present Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_low_frequency_container_is_present = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_low_frequency_container_is_present = 0x00000003;
            bool common_low_frequency_container_is_present_ec {false};
            CommonStructMember common_low_frequency_container_is_present {TypeObjectUtils::build_common_struct_member(member_id_low_frequency_container_is_present, member_flags_low_frequency_container_is_present, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_low_frequency_container_is_present, common_low_frequency_container_is_present_ec))};
            if (!common_low_frequency_container_is_present_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure low_frequency_container_is_present member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_low_frequency_container_is_present = "low_frequency_container_is_present";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_low_frequency_container_is_present;
            ann_custom_CamParameters.reset();
            CompleteMemberDetail detail_low_frequency_container_is_present = TypeObjectUtils::build_complete_member_detail(name_low_frequency_container_is_present, member_ann_builtin_low_frequency_container_is_present, ann_custom_CamParameters);
            CompleteStructMember member_low_frequency_container_is_present = TypeObjectUtils::build_complete_struct_member(common_low_frequency_container_is_present, detail_low_frequency_container_is_present);
            TypeObjectUtils::add_complete_struct_member(member_seq_CamParameters, member_low_frequency_container_is_present);
        }
        {
            TypeIdentifierPair type_ids_special_vehicle_container;
            ReturnCode_t return_code_special_vehicle_container {eprosima::fastdds::dds::RETCODE_OK};
            return_code_special_vehicle_container =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::SpecialVehicleContainer_", type_ids_special_vehicle_container);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_special_vehicle_container)
            {
                etsi_its_cam_msgs::msg::register_SpecialVehicleContainer_type_identifier(type_ids_special_vehicle_container);
            }
            StructMemberFlag member_flags_special_vehicle_container = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_special_vehicle_container = 0x00000004;
            bool common_special_vehicle_container_ec {false};
            CommonStructMember common_special_vehicle_container {TypeObjectUtils::build_common_struct_member(member_id_special_vehicle_container, member_flags_special_vehicle_container, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_special_vehicle_container, common_special_vehicle_container_ec))};
            if (!common_special_vehicle_container_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure special_vehicle_container member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_special_vehicle_container = "special_vehicle_container";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_special_vehicle_container;
            ann_custom_CamParameters.reset();
            CompleteMemberDetail detail_special_vehicle_container = TypeObjectUtils::build_complete_member_detail(name_special_vehicle_container, member_ann_builtin_special_vehicle_container, ann_custom_CamParameters);
            CompleteStructMember member_special_vehicle_container = TypeObjectUtils::build_complete_struct_member(common_special_vehicle_container, detail_special_vehicle_container);
            TypeObjectUtils::add_complete_struct_member(member_seq_CamParameters, member_special_vehicle_container);
        }
        {
            TypeIdentifierPair type_ids_special_vehicle_container_is_present;
            ReturnCode_t return_code_special_vehicle_container_is_present {eprosima::fastdds::dds::RETCODE_OK};
            return_code_special_vehicle_container_is_present =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_special_vehicle_container_is_present);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_special_vehicle_container_is_present)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "special_vehicle_container_is_present Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_special_vehicle_container_is_present = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_special_vehicle_container_is_present = 0x00000005;
            bool common_special_vehicle_container_is_present_ec {false};
            CommonStructMember common_special_vehicle_container_is_present {TypeObjectUtils::build_common_struct_member(member_id_special_vehicle_container_is_present, member_flags_special_vehicle_container_is_present, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_special_vehicle_container_is_present, common_special_vehicle_container_is_present_ec))};
            if (!common_special_vehicle_container_is_present_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure special_vehicle_container_is_present member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_special_vehicle_container_is_present = "special_vehicle_container_is_present";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_special_vehicle_container_is_present;
            ann_custom_CamParameters.reset();
            CompleteMemberDetail detail_special_vehicle_container_is_present = TypeObjectUtils::build_complete_member_detail(name_special_vehicle_container_is_present, member_ann_builtin_special_vehicle_container_is_present, ann_custom_CamParameters);
            CompleteStructMember member_special_vehicle_container_is_present = TypeObjectUtils::build_complete_struct_member(common_special_vehicle_container_is_present, detail_special_vehicle_container_is_present);
            TypeObjectUtils::add_complete_struct_member(member_seq_CamParameters, member_special_vehicle_container_is_present);
        }
        CompleteStructType struct_type_CamParameters = TypeObjectUtils::build_complete_struct_type(struct_flags_CamParameters, header_CamParameters, member_seq_CamParameters);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_CamParameters, type_name_CamParameters.to_string(), type_ids_CamParameters))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "etsi_its_cam_msgs::msg::CamParameters already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace etsi_its_cam_msgs

