// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CenDsrcTollingZone.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_CENDSRCTOLLINGZONE_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_CENDSRCTOLLINGZONE_HPP

#include <cstdint>
#include <utility>
#include "CenDsrcTollingZoneID.hpp"
#include "Latitude.hpp"
#include "Longitude.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CENDSRCTOLLINGZONE_SOURCE)
#define CENDSRCTOLLINGZONE_DllAPI __declspec( dllexport )
#else
#define CENDSRCTOLLINGZONE_DllAPI __declspec( dllimport )
#endif // CENDSRCTOLLINGZONE_SOURCE
#else
#define CENDSRCTOLLINGZONE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CENDSRCTOLLINGZONE_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CenDsrcTollingZone defined by the user in the IDL file.
 * @ingroup CenDsrcTollingZone
 */
class CenDsrcTollingZone
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CenDsrcTollingZone()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CenDsrcTollingZone()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone(
            const CenDsrcTollingZone& x)
    {
                    m_protected_zone_latitude = x.m_protected_zone_latitude;

                    m_protected_zone_longitude = x.m_protected_zone_longitude;

                    m_cen_dsrc_tolling_zone_id = x.m_cen_dsrc_tolling_zone_id;

                    m_cen_dsrc_tolling_zone_id_is_present = x.m_cen_dsrc_tolling_zone_id_is_present;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone(
            CenDsrcTollingZone&& x) noexcept
    {
        m_protected_zone_latitude = std::move(x.m_protected_zone_latitude);
        m_protected_zone_longitude = std::move(x.m_protected_zone_longitude);
        m_cen_dsrc_tolling_zone_id = std::move(x.m_cen_dsrc_tolling_zone_id);
        m_cen_dsrc_tolling_zone_id_is_present = x.m_cen_dsrc_tolling_zone_id_is_present;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone& operator =(
            const CenDsrcTollingZone& x)
    {

                    m_protected_zone_latitude = x.m_protected_zone_latitude;

                    m_protected_zone_longitude = x.m_protected_zone_longitude;

                    m_cen_dsrc_tolling_zone_id = x.m_cen_dsrc_tolling_zone_id;

                    m_cen_dsrc_tolling_zone_id_is_present = x.m_cen_dsrc_tolling_zone_id_is_present;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone& operator =(
            CenDsrcTollingZone&& x) noexcept
    {

        m_protected_zone_latitude = std::move(x.m_protected_zone_latitude);
        m_protected_zone_longitude = std::move(x.m_protected_zone_longitude);
        m_cen_dsrc_tolling_zone_id = std::move(x.m_cen_dsrc_tolling_zone_id);
        m_cen_dsrc_tolling_zone_id_is_present = x.m_cen_dsrc_tolling_zone_id_is_present;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CenDsrcTollingZone object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CenDsrcTollingZone& x) const
    {
        return (m_protected_zone_latitude == x.m_protected_zone_latitude &&
           m_protected_zone_longitude == x.m_protected_zone_longitude &&
           m_cen_dsrc_tolling_zone_id == x.m_cen_dsrc_tolling_zone_id &&
           m_cen_dsrc_tolling_zone_id_is_present == x.m_cen_dsrc_tolling_zone_id_is_present);
    }

    /*!
     * @brief Comparison operator.
     * @param x CenDsrcTollingZone object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CenDsrcTollingZone& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member protected_zone_latitude
     * @param _protected_zone_latitude New value to be copied in member protected_zone_latitude
     */
    eProsima_user_DllExport void protected_zone_latitude(
            const Latitude& _protected_zone_latitude)
    {
        m_protected_zone_latitude = _protected_zone_latitude;
    }

    /*!
     * @brief This function moves the value in member protected_zone_latitude
     * @param _protected_zone_latitude New value to be moved in member protected_zone_latitude
     */
    eProsima_user_DllExport void protected_zone_latitude(
            Latitude&& _protected_zone_latitude)
    {
        m_protected_zone_latitude = std::move(_protected_zone_latitude);
    }

    /*!
     * @brief This function returns a constant reference to member protected_zone_latitude
     * @return Constant reference to member protected_zone_latitude
     */
    eProsima_user_DllExport const Latitude& protected_zone_latitude() const
    {
        return m_protected_zone_latitude;
    }

    /*!
     * @brief This function returns a reference to member protected_zone_latitude
     * @return Reference to member protected_zone_latitude
     */
    eProsima_user_DllExport Latitude& protected_zone_latitude()
    {
        return m_protected_zone_latitude;
    }


    /*!
     * @brief This function copies the value in member protected_zone_longitude
     * @param _protected_zone_longitude New value to be copied in member protected_zone_longitude
     */
    eProsima_user_DllExport void protected_zone_longitude(
            const Longitude& _protected_zone_longitude)
    {
        m_protected_zone_longitude = _protected_zone_longitude;
    }

    /*!
     * @brief This function moves the value in member protected_zone_longitude
     * @param _protected_zone_longitude New value to be moved in member protected_zone_longitude
     */
    eProsima_user_DllExport void protected_zone_longitude(
            Longitude&& _protected_zone_longitude)
    {
        m_protected_zone_longitude = std::move(_protected_zone_longitude);
    }

    /*!
     * @brief This function returns a constant reference to member protected_zone_longitude
     * @return Constant reference to member protected_zone_longitude
     */
    eProsima_user_DllExport const Longitude& protected_zone_longitude() const
    {
        return m_protected_zone_longitude;
    }

    /*!
     * @brief This function returns a reference to member protected_zone_longitude
     * @return Reference to member protected_zone_longitude
     */
    eProsima_user_DllExport Longitude& protected_zone_longitude()
    {
        return m_protected_zone_longitude;
    }


    /*!
     * @brief This function copies the value in member cen_dsrc_tolling_zone_id
     * @param _cen_dsrc_tolling_zone_id New value to be copied in member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_id(
            const CenDsrcTollingZoneID& _cen_dsrc_tolling_zone_id)
    {
        m_cen_dsrc_tolling_zone_id = _cen_dsrc_tolling_zone_id;
    }

    /*!
     * @brief This function moves the value in member cen_dsrc_tolling_zone_id
     * @param _cen_dsrc_tolling_zone_id New value to be moved in member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_id(
            CenDsrcTollingZoneID&& _cen_dsrc_tolling_zone_id)
    {
        m_cen_dsrc_tolling_zone_id = std::move(_cen_dsrc_tolling_zone_id);
    }

    /*!
     * @brief This function returns a constant reference to member cen_dsrc_tolling_zone_id
     * @return Constant reference to member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport const CenDsrcTollingZoneID& cen_dsrc_tolling_zone_id() const
    {
        return m_cen_dsrc_tolling_zone_id;
    }

    /*!
     * @brief This function returns a reference to member cen_dsrc_tolling_zone_id
     * @return Reference to member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport CenDsrcTollingZoneID& cen_dsrc_tolling_zone_id()
    {
        return m_cen_dsrc_tolling_zone_id;
    }


    /*!
     * @brief This function sets a value in member cen_dsrc_tolling_zone_id_is_present
     * @param _cen_dsrc_tolling_zone_id_is_present New value for member cen_dsrc_tolling_zone_id_is_present
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_id_is_present(
            bool _cen_dsrc_tolling_zone_id_is_present)
    {
        m_cen_dsrc_tolling_zone_id_is_present = _cen_dsrc_tolling_zone_id_is_present;
    }

    /*!
     * @brief This function returns the value of member cen_dsrc_tolling_zone_id_is_present
     * @return Value of member cen_dsrc_tolling_zone_id_is_present
     */
    eProsima_user_DllExport bool cen_dsrc_tolling_zone_id_is_present() const
    {
        return m_cen_dsrc_tolling_zone_id_is_present;
    }

    /*!
     * @brief This function returns a reference to member cen_dsrc_tolling_zone_id_is_present
     * @return Reference to member cen_dsrc_tolling_zone_id_is_present
     */
    eProsima_user_DllExport bool& cen_dsrc_tolling_zone_id_is_present()
    {
        return m_cen_dsrc_tolling_zone_id_is_present;
    }



private:

    Latitude m_protected_zone_latitude;
    Longitude m_protected_zone_longitude;
    CenDsrcTollingZoneID m_cen_dsrc_tolling_zone_id;
    bool m_cen_dsrc_tolling_zone_id_is_present{false};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_CENDSRCTOLLINGZONE_HPP_


