// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CoopAwareness.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_COOPAWARENESS_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_COOPAWARENESS_HPP

#include <cstdint>
#include <utility>
#include "GenerationDeltaTime.hpp"
#include "CamParameters.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COOPAWARENESS_SOURCE)
#define COOPAWARENESS_DllAPI __declspec( dllexport )
#else
#define COOPAWARENESS_DllAPI __declspec( dllimport )
#endif // COOPAWARENESS_SOURCE
#else
#define COOPAWARENESS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COOPAWARENESS_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure CoopAwareness defined by the user in the IDL file.
 * @ingroup CoopAwareness
 */
class CoopAwareness
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CoopAwareness()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CoopAwareness()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CoopAwareness that will be copied.
     */
    eProsima_user_DllExport CoopAwareness(
            const CoopAwareness& x)
    {
                    m_generation_delta_time = x.m_generation_delta_time;

                    m_cam_parameters = x.m_cam_parameters;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CoopAwareness that will be copied.
     */
    eProsima_user_DllExport CoopAwareness(
            CoopAwareness&& x) noexcept
    {
        m_generation_delta_time = std::move(x.m_generation_delta_time);
        m_cam_parameters = std::move(x.m_cam_parameters);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CoopAwareness that will be copied.
     */
    eProsima_user_DllExport CoopAwareness& operator =(
            const CoopAwareness& x)
    {

                    m_generation_delta_time = x.m_generation_delta_time;

                    m_cam_parameters = x.m_cam_parameters;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CoopAwareness that will be copied.
     */
    eProsima_user_DllExport CoopAwareness& operator =(
            CoopAwareness&& x) noexcept
    {

        m_generation_delta_time = std::move(x.m_generation_delta_time);
        m_cam_parameters = std::move(x.m_cam_parameters);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CoopAwareness object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CoopAwareness& x) const
    {
        return (m_generation_delta_time == x.m_generation_delta_time &&
           m_cam_parameters == x.m_cam_parameters);
    }

    /*!
     * @brief Comparison operator.
     * @param x CoopAwareness object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CoopAwareness& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member generation_delta_time
     * @param _generation_delta_time New value to be copied in member generation_delta_time
     */
    eProsima_user_DllExport void generation_delta_time(
            const GenerationDeltaTime& _generation_delta_time)
    {
        m_generation_delta_time = _generation_delta_time;
    }

    /*!
     * @brief This function moves the value in member generation_delta_time
     * @param _generation_delta_time New value to be moved in member generation_delta_time
     */
    eProsima_user_DllExport void generation_delta_time(
            GenerationDeltaTime&& _generation_delta_time)
    {
        m_generation_delta_time = std::move(_generation_delta_time);
    }

    /*!
     * @brief This function returns a constant reference to member generation_delta_time
     * @return Constant reference to member generation_delta_time
     */
    eProsima_user_DllExport const GenerationDeltaTime& generation_delta_time() const
    {
        return m_generation_delta_time;
    }

    /*!
     * @brief This function returns a reference to member generation_delta_time
     * @return Reference to member generation_delta_time
     */
    eProsima_user_DllExport GenerationDeltaTime& generation_delta_time()
    {
        return m_generation_delta_time;
    }


    /*!
     * @brief This function copies the value in member cam_parameters
     * @param _cam_parameters New value to be copied in member cam_parameters
     */
    eProsima_user_DllExport void cam_parameters(
            const CamParameters& _cam_parameters)
    {
        m_cam_parameters = _cam_parameters;
    }

    /*!
     * @brief This function moves the value in member cam_parameters
     * @param _cam_parameters New value to be moved in member cam_parameters
     */
    eProsima_user_DllExport void cam_parameters(
            CamParameters&& _cam_parameters)
    {
        m_cam_parameters = std::move(_cam_parameters);
    }

    /*!
     * @brief This function returns a constant reference to member cam_parameters
     * @return Constant reference to member cam_parameters
     */
    eProsima_user_DllExport const CamParameters& cam_parameters() const
    {
        return m_cam_parameters;
    }

    /*!
     * @brief This function returns a reference to member cam_parameters
     * @return Reference to member cam_parameters
     */
    eProsima_user_DllExport CamParameters& cam_parameters()
    {
        return m_cam_parameters;
    }



private:

    GenerationDeltaTime m_generation_delta_time;
    CamParameters m_cam_parameters;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_COOPAWARENESS_HPP_


