// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DangerousGoodsContainerTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "DangerousGoodsContainerTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "DangerousGoodsContainer.hpp"

#include "DangerousGoodsBasic.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace etsi_its_cam_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_DangerousGoodsContainer_type_identifier(
        TypeIdentifierPair& type_ids_DangerousGoodsContainer)
{

    ReturnCode_t return_code_DangerousGoodsContainer {eprosima::fastdds::dds::RETCODE_OK};
    return_code_DangerousGoodsContainer =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "etsi_its_cam_msgs::msg::dds_::DangerousGoodsContainer_", type_ids_DangerousGoodsContainer);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_DangerousGoodsContainer)
    {
        StructTypeFlag struct_flags_DangerousGoodsContainer = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_DangerousGoodsContainer = "etsi_its_cam_msgs::msg::dds_::DangerousGoodsContainer_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_DangerousGoodsContainer;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_DangerousGoodsContainer;
        AppliedAnnotationSeq tmp_ann_custom_DangerousGoodsContainer;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_DangerousGoodsContainer;
        PlacementKind placement_DangerousGoodsContainer = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_DangerousGoodsContainer = "*";
        std::string text_DangerousGoodsContainer;
        language_DangerousGoodsContainer = "comment";

        placement_DangerousGoodsContainer = PlacementKind::BEFORE_DECLARATION;

        text_DangerousGoodsContainer = "==============================================================================\nMIT License\n\nCopyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n==============================================================================";

        verbatim_DangerousGoodsContainer = TypeObjectUtils::build_applied_verbatim_annotation(placement_DangerousGoodsContainer, language_DangerousGoodsContainer, text_DangerousGoodsContainer);
        type_ann_builtin_DangerousGoodsContainer = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_DangerousGoodsContainer);

        if (!tmp_ann_custom_DangerousGoodsContainer.empty())
        {
            ann_custom_DangerousGoodsContainer = tmp_ann_custom_DangerousGoodsContainer;
        }

        CompleteTypeDetail detail_DangerousGoodsContainer = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_DangerousGoodsContainer, ann_custom_DangerousGoodsContainer, type_name_DangerousGoodsContainer.to_string());
        CompleteStructHeader header_DangerousGoodsContainer;
        header_DangerousGoodsContainer = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_DangerousGoodsContainer);
        CompleteStructMemberSeq member_seq_DangerousGoodsContainer;
        {
            TypeIdentifierPair type_ids_dangerous_goods_basic;
            ReturnCode_t return_code_dangerous_goods_basic {eprosima::fastdds::dds::RETCODE_OK};
            return_code_dangerous_goods_basic =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::DangerousGoodsBasic_", type_ids_dangerous_goods_basic);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_dangerous_goods_basic)
            {
                etsi_its_cam_msgs::msg::register_DangerousGoodsBasic_type_identifier(type_ids_dangerous_goods_basic);
            }
            StructMemberFlag member_flags_dangerous_goods_basic = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_dangerous_goods_basic = 0x00000000;
            bool common_dangerous_goods_basic_ec {false};
            CommonStructMember common_dangerous_goods_basic {TypeObjectUtils::build_common_struct_member(member_id_dangerous_goods_basic, member_flags_dangerous_goods_basic, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_dangerous_goods_basic, common_dangerous_goods_basic_ec))};
            if (!common_dangerous_goods_basic_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure dangerous_goods_basic member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_dangerous_goods_basic = "dangerous_goods_basic";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_dangerous_goods_basic;
            ann_custom_DangerousGoodsContainer.reset();
            AppliedAnnotationSeq tmp_ann_custom_dangerous_goods_basic;
            eprosima::fastcdr::optional<std::string> unit_dangerous_goods_basic;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_dangerous_goods_basic;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_dangerous_goods_basic;
            eprosima::fastcdr::optional<std::string> hash_id_dangerous_goods_basic;
            if (unit_dangerous_goods_basic.has_value() || min_dangerous_goods_basic.has_value() || max_dangerous_goods_basic.has_value() || hash_id_dangerous_goods_basic.has_value())
            {
                member_ann_builtin_dangerous_goods_basic = TypeObjectUtils::build_applied_builtin_member_annotations(unit_dangerous_goods_basic, min_dangerous_goods_basic, max_dangerous_goods_basic, hash_id_dangerous_goods_basic);
            }
            if (!tmp_ann_custom_dangerous_goods_basic.empty())
            {
                ann_custom_DangerousGoodsContainer = tmp_ann_custom_dangerous_goods_basic;
            }
            CompleteMemberDetail detail_dangerous_goods_basic = TypeObjectUtils::build_complete_member_detail(name_dangerous_goods_basic, member_ann_builtin_dangerous_goods_basic, ann_custom_DangerousGoodsContainer);
            CompleteStructMember member_dangerous_goods_basic = TypeObjectUtils::build_complete_struct_member(common_dangerous_goods_basic, detail_dangerous_goods_basic);
            TypeObjectUtils::add_complete_struct_member(member_seq_DangerousGoodsContainer, member_dangerous_goods_basic);
        }
        CompleteStructType struct_type_DangerousGoodsContainer = TypeObjectUtils::build_complete_struct_type(struct_flags_DangerousGoodsContainer, header_DangerousGoodsContainer, member_seq_DangerousGoodsContainer);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_DangerousGoodsContainer, type_name_DangerousGoodsContainer.to_string(), type_ids_DangerousGoodsContainer))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "etsi_its_cam_msgs::msg::DangerousGoodsContainer already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace etsi_its_cam_msgs

