// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DeltaReferencePositionTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "DeltaReferencePositionTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "DeltaReferencePosition.hpp"

#include "DeltaLongitude.hpp"
#include "DeltaAltitude.hpp"
#include "DeltaLatitude.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace etsi_its_cam_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_DeltaReferencePosition_type_identifier(
        TypeIdentifierPair& type_ids_DeltaReferencePosition)
{

    ReturnCode_t return_code_DeltaReferencePosition {eprosima::fastdds::dds::RETCODE_OK};
    return_code_DeltaReferencePosition =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "etsi_its_cam_msgs::msg::dds_::DeltaReferencePosition_", type_ids_DeltaReferencePosition);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_DeltaReferencePosition)
    {
        StructTypeFlag struct_flags_DeltaReferencePosition = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_DeltaReferencePosition = "etsi_its_cam_msgs::msg::dds_::DeltaReferencePosition_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_DeltaReferencePosition;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_DeltaReferencePosition;
        AppliedAnnotationSeq tmp_ann_custom_DeltaReferencePosition;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_DeltaReferencePosition;
        PlacementKind placement_DeltaReferencePosition = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_DeltaReferencePosition = "*";
        std::string text_DeltaReferencePosition;
        language_DeltaReferencePosition = "comment";

        placement_DeltaReferencePosition = PlacementKind::BEFORE_DECLARATION;

        text_DeltaReferencePosition = "==============================================================================\nMIT License\n\nCopyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n==============================================================================";

        verbatim_DeltaReferencePosition = TypeObjectUtils::build_applied_verbatim_annotation(placement_DeltaReferencePosition, language_DeltaReferencePosition, text_DeltaReferencePosition);
        type_ann_builtin_DeltaReferencePosition = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_DeltaReferencePosition);

        if (!tmp_ann_custom_DeltaReferencePosition.empty())
        {
            ann_custom_DeltaReferencePosition = tmp_ann_custom_DeltaReferencePosition;
        }

        CompleteTypeDetail detail_DeltaReferencePosition = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_DeltaReferencePosition, ann_custom_DeltaReferencePosition, type_name_DeltaReferencePosition.to_string());
        CompleteStructHeader header_DeltaReferencePosition;
        header_DeltaReferencePosition = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_DeltaReferencePosition);
        CompleteStructMemberSeq member_seq_DeltaReferencePosition;
        {
            TypeIdentifierPair type_ids_delta_latitude;
            ReturnCode_t return_code_delta_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_delta_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::DeltaLatitude_", type_ids_delta_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_delta_latitude)
            {
                etsi_its_cam_msgs::msg::register_DeltaLatitude_type_identifier(type_ids_delta_latitude);
            }
            StructMemberFlag member_flags_delta_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_delta_latitude = 0x00000000;
            bool common_delta_latitude_ec {false};
            CommonStructMember common_delta_latitude {TypeObjectUtils::build_common_struct_member(member_id_delta_latitude, member_flags_delta_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_delta_latitude, common_delta_latitude_ec))};
            if (!common_delta_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure delta_latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_delta_latitude = "delta_latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_delta_latitude;
            ann_custom_DeltaReferencePosition.reset();
            AppliedAnnotationSeq tmp_ann_custom_delta_latitude;
            eprosima::fastcdr::optional<std::string> unit_delta_latitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_delta_latitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_delta_latitude;
            eprosima::fastcdr::optional<std::string> hash_id_delta_latitude;
            if (unit_delta_latitude.has_value() || min_delta_latitude.has_value() || max_delta_latitude.has_value() || hash_id_delta_latitude.has_value())
            {
                member_ann_builtin_delta_latitude = TypeObjectUtils::build_applied_builtin_member_annotations(unit_delta_latitude, min_delta_latitude, max_delta_latitude, hash_id_delta_latitude);
            }
            if (!tmp_ann_custom_delta_latitude.empty())
            {
                ann_custom_DeltaReferencePosition = tmp_ann_custom_delta_latitude;
            }
            CompleteMemberDetail detail_delta_latitude = TypeObjectUtils::build_complete_member_detail(name_delta_latitude, member_ann_builtin_delta_latitude, ann_custom_DeltaReferencePosition);
            CompleteStructMember member_delta_latitude = TypeObjectUtils::build_complete_struct_member(common_delta_latitude, detail_delta_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_DeltaReferencePosition, member_delta_latitude);
        }
        {
            TypeIdentifierPair type_ids_delta_longitude;
            ReturnCode_t return_code_delta_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_delta_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::DeltaLongitude_", type_ids_delta_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_delta_longitude)
            {
                etsi_its_cam_msgs::msg::register_DeltaLongitude_type_identifier(type_ids_delta_longitude);
            }
            StructMemberFlag member_flags_delta_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_delta_longitude = 0x00000001;
            bool common_delta_longitude_ec {false};
            CommonStructMember common_delta_longitude {TypeObjectUtils::build_common_struct_member(member_id_delta_longitude, member_flags_delta_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_delta_longitude, common_delta_longitude_ec))};
            if (!common_delta_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure delta_longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_delta_longitude = "delta_longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_delta_longitude;
            ann_custom_DeltaReferencePosition.reset();
            CompleteMemberDetail detail_delta_longitude = TypeObjectUtils::build_complete_member_detail(name_delta_longitude, member_ann_builtin_delta_longitude, ann_custom_DeltaReferencePosition);
            CompleteStructMember member_delta_longitude = TypeObjectUtils::build_complete_struct_member(common_delta_longitude, detail_delta_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_DeltaReferencePosition, member_delta_longitude);
        }
        {
            TypeIdentifierPair type_ids_delta_altitude;
            ReturnCode_t return_code_delta_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_delta_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::DeltaAltitude_", type_ids_delta_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_delta_altitude)
            {
                etsi_its_cam_msgs::msg::register_DeltaAltitude_type_identifier(type_ids_delta_altitude);
            }
            StructMemberFlag member_flags_delta_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_delta_altitude = 0x00000002;
            bool common_delta_altitude_ec {false};
            CommonStructMember common_delta_altitude {TypeObjectUtils::build_common_struct_member(member_id_delta_altitude, member_flags_delta_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_delta_altitude, common_delta_altitude_ec))};
            if (!common_delta_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure delta_altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_delta_altitude = "delta_altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_delta_altitude;
            ann_custom_DeltaReferencePosition.reset();
            CompleteMemberDetail detail_delta_altitude = TypeObjectUtils::build_complete_member_detail(name_delta_altitude, member_ann_builtin_delta_altitude, ann_custom_DeltaReferencePosition);
            CompleteStructMember member_delta_altitude = TypeObjectUtils::build_complete_struct_member(common_delta_altitude, detail_delta_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_DeltaReferencePosition, member_delta_altitude);
        }
        CompleteStructType struct_type_DeltaReferencePosition = TypeObjectUtils::build_complete_struct_type(struct_flags_DeltaReferencePosition, header_DeltaReferencePosition, member_seq_DeltaReferencePosition);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_DeltaReferencePosition, type_name_DeltaReferencePosition.to_string(), type_ids_DeltaReferencePosition))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "etsi_its_cam_msgs::msg::DeltaReferencePosition already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace etsi_its_cam_msgs

