// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Heading.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_HEADING_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_HEADING_HPP

#include <cstdint>
#include <utility>
#include "HeadingConfidence.hpp"
#include "HeadingValue.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HEADING_SOURCE)
#define HEADING_DllAPI __declspec( dllexport )
#else
#define HEADING_DllAPI __declspec( dllimport )
#endif // HEADING_SOURCE
#else
#define HEADING_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define HEADING_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Heading defined by the user in the IDL file.
 * @ingroup Heading
 */
class Heading
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Heading()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Heading()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Heading that will be copied.
     */
    eProsima_user_DllExport Heading(
            const Heading& x)
    {
                    m_heading_value = x.m_heading_value;

                    m_heading_confidence = x.m_heading_confidence;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Heading that will be copied.
     */
    eProsima_user_DllExport Heading(
            Heading&& x) noexcept
    {
        m_heading_value = std::move(x.m_heading_value);
        m_heading_confidence = std::move(x.m_heading_confidence);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Heading that will be copied.
     */
    eProsima_user_DllExport Heading& operator =(
            const Heading& x)
    {

                    m_heading_value = x.m_heading_value;

                    m_heading_confidence = x.m_heading_confidence;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Heading that will be copied.
     */
    eProsima_user_DllExport Heading& operator =(
            Heading&& x) noexcept
    {

        m_heading_value = std::move(x.m_heading_value);
        m_heading_confidence = std::move(x.m_heading_confidence);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Heading object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Heading& x) const
    {
        return (m_heading_value == x.m_heading_value &&
           m_heading_confidence == x.m_heading_confidence);
    }

    /*!
     * @brief Comparison operator.
     * @param x Heading object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Heading& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member heading_value
     * @param _heading_value New value to be copied in member heading_value
     */
    eProsima_user_DllExport void heading_value(
            const HeadingValue& _heading_value)
    {
        m_heading_value = _heading_value;
    }

    /*!
     * @brief This function moves the value in member heading_value
     * @param _heading_value New value to be moved in member heading_value
     */
    eProsima_user_DllExport void heading_value(
            HeadingValue&& _heading_value)
    {
        m_heading_value = std::move(_heading_value);
    }

    /*!
     * @brief This function returns a constant reference to member heading_value
     * @return Constant reference to member heading_value
     */
    eProsima_user_DllExport const HeadingValue& heading_value() const
    {
        return m_heading_value;
    }

    /*!
     * @brief This function returns a reference to member heading_value
     * @return Reference to member heading_value
     */
    eProsima_user_DllExport HeadingValue& heading_value()
    {
        return m_heading_value;
    }


    /*!
     * @brief This function copies the value in member heading_confidence
     * @param _heading_confidence New value to be copied in member heading_confidence
     */
    eProsima_user_DllExport void heading_confidence(
            const HeadingConfidence& _heading_confidence)
    {
        m_heading_confidence = _heading_confidence;
    }

    /*!
     * @brief This function moves the value in member heading_confidence
     * @param _heading_confidence New value to be moved in member heading_confidence
     */
    eProsima_user_DllExport void heading_confidence(
            HeadingConfidence&& _heading_confidence)
    {
        m_heading_confidence = std::move(_heading_confidence);
    }

    /*!
     * @brief This function returns a constant reference to member heading_confidence
     * @return Constant reference to member heading_confidence
     */
    eProsima_user_DllExport const HeadingConfidence& heading_confidence() const
    {
        return m_heading_confidence;
    }

    /*!
     * @brief This function returns a reference to member heading_confidence
     * @return Reference to member heading_confidence
     */
    eProsima_user_DllExport HeadingConfidence& heading_confidence()
    {
        return m_heading_confidence;
    }



private:

    HeadingValue m_heading_value;
    HeadingConfidence m_heading_confidence;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_HEADING_HPP_


