// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ItsPduHeaderPubSubTypes.hpp
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */


#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_ITSPDUHEADER_PUBSUBTYPES_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_ITSPDUHEADER_PUBSUBTYPES_HPP

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>
#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>

#include "ItsPduHeader.hpp"

#include "StationIDPubSubTypes.hpp"

#if !defined(FASTDDS_GEN_API_VER) || (FASTDDS_GEN_API_VER != 3)
#error \
    Generated ItsPduHeader is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // FASTDDS_GEN_API_VER

namespace etsi_its_cam_msgs
{
    namespace msg
    {
        namespace ItsPduHeader_Constants
        {
        } // namespace ItsPduHeader_Constants

        #ifndef SWIG
        namespace detail {

        template<typename Tag, typename Tag::type M>
        struct ItsPduHeader_rob
        {
            friend constexpr typename Tag::type get(
                    Tag)
            {
                return M;
            }

        };

        struct ItsPduHeader_f
        {
            typedef etsi_its_cam_msgs::msg::StationID ItsPduHeader::* type;
            friend constexpr type get(
                    ItsPduHeader_f);
        };

        template struct ItsPduHeader_rob<ItsPduHeader_f, &ItsPduHeader::m_station_id>;

        template <typename T, typename Tag>
        inline size_t constexpr ItsPduHeader_offset_of()
        {
            return ((::size_t) &reinterpret_cast<char const volatile&>((((T*)0)->*get(Tag()))));
        }

        } // namespace detail
        #endif // ifndef SWIG


        /*!
         * @brief This class represents the TopicDataType of the type ItsPduHeader defined by the user in the IDL file.
         * @ingroup ItsPduHeader
         */
        class ItsPduHeaderPubSubType : public eprosima::fastdds::dds::TopicDataType
        {
        public:

            typedef ItsPduHeader type;

            eProsima_user_DllExport ItsPduHeaderPubSubType();

            eProsima_user_DllExport ~ItsPduHeaderPubSubType() override;

            eProsima_user_DllExport bool serialize(
                    const void* const data,
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

            eProsima_user_DllExport bool deserialize(
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    void* data) override;

            eProsima_user_DllExport uint32_t calculate_serialized_size(
                    const void* const data,
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

            eProsima_user_DllExport bool compute_key(
                    eprosima::fastdds::rtps::SerializedPayload_t& payload,
                    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
                    bool force_md5 = false) override;

            eProsima_user_DllExport bool compute_key(
                    const void* const data,
                    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
                    bool force_md5 = false) override;

            eProsima_user_DllExport void* create_data() override;

            eProsima_user_DllExport void delete_data(
                    void* data) override;

            //Register TypeObject representation in Fast DDS TypeObjectRegistry
            eProsima_user_DllExport void register_type_object_representation() override;

        #ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
            eProsima_user_DllExport inline bool is_bounded() const override
            {
                return true;
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

        #ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

            eProsima_user_DllExport inline bool is_plain(
                    eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
            {
                if (data_representation == eprosima::fastdds::dds::DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)
                {
                    return is_plain_xcdrv2_impl();
                }
                else
                {
                    return is_plain_xcdrv1_impl();
                }
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

        #ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
            eProsima_user_DllExport inline bool construct_sample(
                    void* memory) const override
            {
                new (memory) ItsPduHeader();
                return true;
            }

        #endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

        private:

            eprosima::fastdds::MD5 md5_;
            unsigned char* key_buffer_;


            static constexpr bool is_plain_xcdrv1_impl()
            {
                return 8ULL ==
                       (detail::ItsPduHeader_offset_of<ItsPduHeader, detail::ItsPduHeader_f>() +
                       sizeof(etsi_its_cam_msgs::msg::StationID));
            }

            static constexpr bool is_plain_xcdrv2_impl()
            {
                return 8ULL ==
                       (detail::ItsPduHeader_offset_of<ItsPduHeader, detail::ItsPduHeader_f>() +
                       sizeof(etsi_its_cam_msgs::msg::StationID));
            }

        };
    } // namespace msg
} // namespace etsi_its_cam_msgs

#endif // FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_ITSPDUHEADER_PUBSUBTYPES_HPP

