// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Latitude.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LATITUDE_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LATITUDE_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LATITUDE_SOURCE)
#define LATITUDE_DllAPI __declspec( dllexport )
#else
#define LATITUDE_DllAPI __declspec( dllimport )
#endif // LATITUDE_SOURCE
#else
#define LATITUDE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LATITUDE_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

namespace Latitude_Constants {

const int32_t MIN = -900000000;
const int32_t MAX = 900000001;
const int32_t ONE_MICRODEGREE_NORTH = 10;
const int32_t ONE_MICRODEGREE_SOUTH = -10;
const int32_t UNAVAILABLE = 900000001;

} // namespace Latitude_Constants
/*!
 * @brief This class represents the structure Latitude defined by the user in the IDL file.
 * @ingroup Latitude
 */
class Latitude
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Latitude()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Latitude()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Latitude that will be copied.
     */
    eProsima_user_DllExport Latitude(
            const Latitude& x)
    {
                    m_value = x.m_value;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Latitude that will be copied.
     */
    eProsima_user_DllExport Latitude(
            Latitude&& x) noexcept
    {
        m_value = x.m_value;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Latitude that will be copied.
     */
    eProsima_user_DllExport Latitude& operator =(
            const Latitude& x)
    {

                    m_value = x.m_value;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Latitude that will be copied.
     */
    eProsima_user_DllExport Latitude& operator =(
            Latitude&& x) noexcept
    {

        m_value = x.m_value;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Latitude object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Latitude& x) const
    {
        return (m_value == x.m_value);
    }

    /*!
     * @brief Comparison operator.
     * @param x Latitude object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Latitude& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            int32_t _value)
    {
        m_value = _value;
    }

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport int32_t value() const
    {
        return m_value;
    }

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport int32_t& value()
    {
        return m_value;
    }



private:

    int32_t m_value{0};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_LATITUDE_HPP_


