// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LightBarSirenInUse.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LIGHTBARSIRENINUSE_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LIGHTBARSIRENINUSE_HPP

#include <cstdint>
#include <utility>
#include <vector>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LIGHTBARSIRENINUSE_SOURCE)
#define LIGHTBARSIRENINUSE_DllAPI __declspec( dllexport )
#else
#define LIGHTBARSIRENINUSE_DllAPI __declspec( dllimport )
#endif // LIGHTBARSIRENINUSE_SOURCE
#else
#define LIGHTBARSIRENINUSE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LIGHTBARSIRENINUSE_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

namespace LightBarSirenInUse_Constants {

const uint8_t SIZE_BITS = 2;
const uint8_t BIT_INDEX_LIGHT_BAR_ACTIVATED = 0;
const uint8_t BIT_INDEX_SIREN_ACTIVATED = 1;

} // namespace LightBarSirenInUse_Constants
/*!
 * @brief This class represents the structure LightBarSirenInUse defined by the user in the IDL file.
 * @ingroup LightBarSirenInUse
 */
class LightBarSirenInUse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LightBarSirenInUse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LightBarSirenInUse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LightBarSirenInUse that will be copied.
     */
    eProsima_user_DllExport LightBarSirenInUse(
            const LightBarSirenInUse& x)
    {
                    m_value = x.m_value;

                    m_bits_unused = x.m_bits_unused;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LightBarSirenInUse that will be copied.
     */
    eProsima_user_DllExport LightBarSirenInUse(
            LightBarSirenInUse&& x) noexcept
    {
        m_value = std::move(x.m_value);
        m_bits_unused = x.m_bits_unused;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LightBarSirenInUse that will be copied.
     */
    eProsima_user_DllExport LightBarSirenInUse& operator =(
            const LightBarSirenInUse& x)
    {

                    m_value = x.m_value;

                    m_bits_unused = x.m_bits_unused;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LightBarSirenInUse that will be copied.
     */
    eProsima_user_DllExport LightBarSirenInUse& operator =(
            LightBarSirenInUse&& x) noexcept
    {

        m_value = std::move(x.m_value);
        m_bits_unused = x.m_bits_unused;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LightBarSirenInUse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LightBarSirenInUse& x) const
    {
        return (m_value == x.m_value &&
           m_bits_unused == x.m_bits_unused);
    }

    /*!
     * @brief Comparison operator.
     * @param x LightBarSirenInUse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LightBarSirenInUse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member value
     * @param _value New value to be copied in member value
     */
    eProsima_user_DllExport void value(
            const std::vector<uint8_t>& _value)
    {
        m_value = _value;
    }

    /*!
     * @brief This function moves the value in member value
     * @param _value New value to be moved in member value
     */
    eProsima_user_DllExport void value(
            std::vector<uint8_t>&& _value)
    {
        m_value = std::move(_value);
    }

    /*!
     * @brief This function returns a constant reference to member value
     * @return Constant reference to member value
     */
    eProsima_user_DllExport const std::vector<uint8_t>& value() const
    {
        return m_value;
    }

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport std::vector<uint8_t>& value()
    {
        return m_value;
    }


    /*!
     * @brief This function sets a value in member bits_unused
     * @param _bits_unused New value for member bits_unused
     */
    eProsima_user_DllExport void bits_unused(
            uint8_t _bits_unused)
    {
        m_bits_unused = _bits_unused;
    }

    /*!
     * @brief This function returns the value of member bits_unused
     * @return Value of member bits_unused
     */
    eProsima_user_DllExport uint8_t bits_unused() const
    {
        return m_bits_unused;
    }

    /*!
     * @brief This function returns a reference to member bits_unused
     * @return Reference to member bits_unused
     */
    eProsima_user_DllExport uint8_t& bits_unused()
    {
        return m_bits_unused;
    }



private:

    std::vector<uint8_t> m_value;
    uint8_t m_bits_unused{0};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_LIGHTBARSIRENINUSE_HPP_


