// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LongitudinalAccelerationValue.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LONGITUDINALACCELERATIONVALUE_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LONGITUDINALACCELERATIONVALUE_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LONGITUDINALACCELERATIONVALUE_SOURCE)
#define LONGITUDINALACCELERATIONVALUE_DllAPI __declspec( dllexport )
#else
#define LONGITUDINALACCELERATIONVALUE_DllAPI __declspec( dllimport )
#endif // LONGITUDINALACCELERATIONVALUE_SOURCE
#else
#define LONGITUDINALACCELERATIONVALUE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LONGITUDINALACCELERATIONVALUE_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

namespace LongitudinalAccelerationValue_Constants {

const int16_t MIN = -160;
const int16_t MAX = 161;
const int16_t POINT_ONE_METER_PER_SEC_SQUARED_FORWARD = 1;
const int16_t POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD = -1;
const int16_t UNAVAILABLE = 161;

} // namespace LongitudinalAccelerationValue_Constants
/*!
 * @brief This class represents the structure LongitudinalAccelerationValue defined by the user in the IDL file.
 * @ingroup LongitudinalAccelerationValue
 */
class LongitudinalAccelerationValue
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LongitudinalAccelerationValue()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LongitudinalAccelerationValue()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LongitudinalAccelerationValue that will be copied.
     */
    eProsima_user_DllExport LongitudinalAccelerationValue(
            const LongitudinalAccelerationValue& x)
    {
                    m_value = x.m_value;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LongitudinalAccelerationValue that will be copied.
     */
    eProsima_user_DllExport LongitudinalAccelerationValue(
            LongitudinalAccelerationValue&& x) noexcept
    {
        m_value = x.m_value;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LongitudinalAccelerationValue that will be copied.
     */
    eProsima_user_DllExport LongitudinalAccelerationValue& operator =(
            const LongitudinalAccelerationValue& x)
    {

                    m_value = x.m_value;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LongitudinalAccelerationValue that will be copied.
     */
    eProsima_user_DllExport LongitudinalAccelerationValue& operator =(
            LongitudinalAccelerationValue&& x) noexcept
    {

        m_value = x.m_value;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LongitudinalAccelerationValue object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LongitudinalAccelerationValue& x) const
    {
        return (m_value == x.m_value);
    }

    /*!
     * @brief Comparison operator.
     * @param x LongitudinalAccelerationValue object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LongitudinalAccelerationValue& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            int16_t _value)
    {
        m_value = _value;
    }

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport int16_t value() const
    {
        return m_value;
    }

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport int16_t& value()
    {
        return m_value;
    }



private:

    int16_t m_value{0};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_LONGITUDINALACCELERATIONVALUE_HPP_


