// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LongitudinalAcceleration.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LONGITUDINALACCELERATION_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_LONGITUDINALACCELERATION_HPP

#include <cstdint>
#include <utility>
#include "LongitudinalAccelerationValue.hpp"
#include "AccelerationConfidence.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LONGITUDINALACCELERATION_SOURCE)
#define LONGITUDINALACCELERATION_DllAPI __declspec( dllexport )
#else
#define LONGITUDINALACCELERATION_DllAPI __declspec( dllimport )
#endif // LONGITUDINALACCELERATION_SOURCE
#else
#define LONGITUDINALACCELERATION_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LONGITUDINALACCELERATION_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure LongitudinalAcceleration defined by the user in the IDL file.
 * @ingroup LongitudinalAcceleration
 */
class LongitudinalAcceleration
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LongitudinalAcceleration()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LongitudinalAcceleration()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LongitudinalAcceleration that will be copied.
     */
    eProsima_user_DllExport LongitudinalAcceleration(
            const LongitudinalAcceleration& x)
    {
                    m_longitudinal_acceleration_value = x.m_longitudinal_acceleration_value;

                    m_longitudinal_acceleration_confidence = x.m_longitudinal_acceleration_confidence;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LongitudinalAcceleration that will be copied.
     */
    eProsima_user_DllExport LongitudinalAcceleration(
            LongitudinalAcceleration&& x) noexcept
    {
        m_longitudinal_acceleration_value = std::move(x.m_longitudinal_acceleration_value);
        m_longitudinal_acceleration_confidence = std::move(x.m_longitudinal_acceleration_confidence);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LongitudinalAcceleration that will be copied.
     */
    eProsima_user_DllExport LongitudinalAcceleration& operator =(
            const LongitudinalAcceleration& x)
    {

                    m_longitudinal_acceleration_value = x.m_longitudinal_acceleration_value;

                    m_longitudinal_acceleration_confidence = x.m_longitudinal_acceleration_confidence;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LongitudinalAcceleration that will be copied.
     */
    eProsima_user_DllExport LongitudinalAcceleration& operator =(
            LongitudinalAcceleration&& x) noexcept
    {

        m_longitudinal_acceleration_value = std::move(x.m_longitudinal_acceleration_value);
        m_longitudinal_acceleration_confidence = std::move(x.m_longitudinal_acceleration_confidence);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LongitudinalAcceleration object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LongitudinalAcceleration& x) const
    {
        return (m_longitudinal_acceleration_value == x.m_longitudinal_acceleration_value &&
           m_longitudinal_acceleration_confidence == x.m_longitudinal_acceleration_confidence);
    }

    /*!
     * @brief Comparison operator.
     * @param x LongitudinalAcceleration object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LongitudinalAcceleration& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member longitudinal_acceleration_value
     * @param _longitudinal_acceleration_value New value to be copied in member longitudinal_acceleration_value
     */
    eProsima_user_DllExport void longitudinal_acceleration_value(
            const LongitudinalAccelerationValue& _longitudinal_acceleration_value)
    {
        m_longitudinal_acceleration_value = _longitudinal_acceleration_value;
    }

    /*!
     * @brief This function moves the value in member longitudinal_acceleration_value
     * @param _longitudinal_acceleration_value New value to be moved in member longitudinal_acceleration_value
     */
    eProsima_user_DllExport void longitudinal_acceleration_value(
            LongitudinalAccelerationValue&& _longitudinal_acceleration_value)
    {
        m_longitudinal_acceleration_value = std::move(_longitudinal_acceleration_value);
    }

    /*!
     * @brief This function returns a constant reference to member longitudinal_acceleration_value
     * @return Constant reference to member longitudinal_acceleration_value
     */
    eProsima_user_DllExport const LongitudinalAccelerationValue& longitudinal_acceleration_value() const
    {
        return m_longitudinal_acceleration_value;
    }

    /*!
     * @brief This function returns a reference to member longitudinal_acceleration_value
     * @return Reference to member longitudinal_acceleration_value
     */
    eProsima_user_DllExport LongitudinalAccelerationValue& longitudinal_acceleration_value()
    {
        return m_longitudinal_acceleration_value;
    }


    /*!
     * @brief This function copies the value in member longitudinal_acceleration_confidence
     * @param _longitudinal_acceleration_confidence New value to be copied in member longitudinal_acceleration_confidence
     */
    eProsima_user_DllExport void longitudinal_acceleration_confidence(
            const AccelerationConfidence& _longitudinal_acceleration_confidence)
    {
        m_longitudinal_acceleration_confidence = _longitudinal_acceleration_confidence;
    }

    /*!
     * @brief This function moves the value in member longitudinal_acceleration_confidence
     * @param _longitudinal_acceleration_confidence New value to be moved in member longitudinal_acceleration_confidence
     */
    eProsima_user_DllExport void longitudinal_acceleration_confidence(
            AccelerationConfidence&& _longitudinal_acceleration_confidence)
    {
        m_longitudinal_acceleration_confidence = std::move(_longitudinal_acceleration_confidence);
    }

    /*!
     * @brief This function returns a constant reference to member longitudinal_acceleration_confidence
     * @return Constant reference to member longitudinal_acceleration_confidence
     */
    eProsima_user_DllExport const AccelerationConfidence& longitudinal_acceleration_confidence() const
    {
        return m_longitudinal_acceleration_confidence;
    }

    /*!
     * @brief This function returns a reference to member longitudinal_acceleration_confidence
     * @return Reference to member longitudinal_acceleration_confidence
     */
    eProsima_user_DllExport AccelerationConfidence& longitudinal_acceleration_confidence()
    {
        return m_longitudinal_acceleration_confidence;
    }



private:

    LongitudinalAccelerationValue m_longitudinal_acceleration_value;
    AccelerationConfidence m_longitudinal_acceleration_confidence;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_LONGITUDINALACCELERATION_HPP_


