// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RescueContainerTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "RescueContainerTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "RescueContainer.hpp"

#include "LightBarSirenInUse.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace etsi_its_cam_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_RescueContainer_type_identifier(
        TypeIdentifierPair& type_ids_RescueContainer)
{

    ReturnCode_t return_code_RescueContainer {eprosima::fastdds::dds::RETCODE_OK};
    return_code_RescueContainer =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "etsi_its_cam_msgs::msg::dds_::RescueContainer_", type_ids_RescueContainer);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_RescueContainer)
    {
        StructTypeFlag struct_flags_RescueContainer = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_RescueContainer = "etsi_its_cam_msgs::msg::dds_::RescueContainer_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_RescueContainer;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_RescueContainer;
        AppliedAnnotationSeq tmp_ann_custom_RescueContainer;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_RescueContainer;
        PlacementKind placement_RescueContainer = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_RescueContainer = "*";
        std::string text_RescueContainer;
        language_RescueContainer = "comment";

        placement_RescueContainer = PlacementKind::BEFORE_DECLARATION;

        text_RescueContainer = "==============================================================================\nMIT License\n\nCopyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n==============================================================================";

        verbatim_RescueContainer = TypeObjectUtils::build_applied_verbatim_annotation(placement_RescueContainer, language_RescueContainer, text_RescueContainer);
        type_ann_builtin_RescueContainer = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_RescueContainer);

        if (!tmp_ann_custom_RescueContainer.empty())
        {
            ann_custom_RescueContainer = tmp_ann_custom_RescueContainer;
        }

        CompleteTypeDetail detail_RescueContainer = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_RescueContainer, ann_custom_RescueContainer, type_name_RescueContainer.to_string());
        CompleteStructHeader header_RescueContainer;
        header_RescueContainer = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_RescueContainer);
        CompleteStructMemberSeq member_seq_RescueContainer;
        {
            TypeIdentifierPair type_ids_light_bar_siren_in_use;
            ReturnCode_t return_code_light_bar_siren_in_use {eprosima::fastdds::dds::RETCODE_OK};
            return_code_light_bar_siren_in_use =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::LightBarSirenInUse_", type_ids_light_bar_siren_in_use);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_light_bar_siren_in_use)
            {
                etsi_its_cam_msgs::msg::register_LightBarSirenInUse_type_identifier(type_ids_light_bar_siren_in_use);
            }
            StructMemberFlag member_flags_light_bar_siren_in_use = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_light_bar_siren_in_use = 0x00000000;
            bool common_light_bar_siren_in_use_ec {false};
            CommonStructMember common_light_bar_siren_in_use {TypeObjectUtils::build_common_struct_member(member_id_light_bar_siren_in_use, member_flags_light_bar_siren_in_use, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_light_bar_siren_in_use, common_light_bar_siren_in_use_ec))};
            if (!common_light_bar_siren_in_use_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure light_bar_siren_in_use member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_light_bar_siren_in_use = "light_bar_siren_in_use";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_light_bar_siren_in_use;
            ann_custom_RescueContainer.reset();
            AppliedAnnotationSeq tmp_ann_custom_light_bar_siren_in_use;
            eprosima::fastcdr::optional<std::string> unit_light_bar_siren_in_use;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_light_bar_siren_in_use;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_light_bar_siren_in_use;
            eprosima::fastcdr::optional<std::string> hash_id_light_bar_siren_in_use;
            if (unit_light_bar_siren_in_use.has_value() || min_light_bar_siren_in_use.has_value() || max_light_bar_siren_in_use.has_value() || hash_id_light_bar_siren_in_use.has_value())
            {
                member_ann_builtin_light_bar_siren_in_use = TypeObjectUtils::build_applied_builtin_member_annotations(unit_light_bar_siren_in_use, min_light_bar_siren_in_use, max_light_bar_siren_in_use, hash_id_light_bar_siren_in_use);
            }
            if (!tmp_ann_custom_light_bar_siren_in_use.empty())
            {
                ann_custom_RescueContainer = tmp_ann_custom_light_bar_siren_in_use;
            }
            CompleteMemberDetail detail_light_bar_siren_in_use = TypeObjectUtils::build_complete_member_detail(name_light_bar_siren_in_use, member_ann_builtin_light_bar_siren_in_use, ann_custom_RescueContainer);
            CompleteStructMember member_light_bar_siren_in_use = TypeObjectUtils::build_complete_struct_member(common_light_bar_siren_in_use, detail_light_bar_siren_in_use);
            TypeObjectUtils::add_complete_struct_member(member_seq_RescueContainer, member_light_bar_siren_in_use);
        }
        CompleteStructType struct_type_RescueContainer = TypeObjectUtils::build_complete_struct_type(struct_flags_RescueContainer, header_RescueContainer, member_seq_RescueContainer);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_RescueContainer, type_name_RescueContainer.to_string(), type_ids_RescueContainer))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "etsi_its_cam_msgs::msg::RescueContainer already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace etsi_its_cam_msgs

