// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RoadworksSubCauseCodeTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "RoadworksSubCauseCodeTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "RoadworksSubCauseCode.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace etsi_its_cam_msgs {
namespace msg {
namespace RoadworksSubCauseCode_Constants {
} // namespace RoadworksSubCauseCode_Constants
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_RoadworksSubCauseCode_type_identifier(
        TypeIdentifierPair& type_ids_RoadworksSubCauseCode)
{

    ReturnCode_t return_code_RoadworksSubCauseCode {eprosima::fastdds::dds::RETCODE_OK};
    return_code_RoadworksSubCauseCode =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "etsi_its_cam_msgs::msg::dds_::RoadworksSubCauseCode_", type_ids_RoadworksSubCauseCode);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_RoadworksSubCauseCode)
    {
        StructTypeFlag struct_flags_RoadworksSubCauseCode = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_RoadworksSubCauseCode = "etsi_its_cam_msgs::msg::dds_::RoadworksSubCauseCode_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_RoadworksSubCauseCode;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_RoadworksSubCauseCode;
        AppliedAnnotationSeq tmp_ann_custom_RoadworksSubCauseCode;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_RoadworksSubCauseCode;
        PlacementKind placement_RoadworksSubCauseCode = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_RoadworksSubCauseCode = "*";
        std::string text_RoadworksSubCauseCode;
        language_RoadworksSubCauseCode = "comment";

        placement_RoadworksSubCauseCode = PlacementKind::BEFORE_DECLARATION;

        text_RoadworksSubCauseCode = "==============================================================================\nMIT License\n\nCopyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n==============================================================================";

        verbatim_RoadworksSubCauseCode = TypeObjectUtils::build_applied_verbatim_annotation(placement_RoadworksSubCauseCode, language_RoadworksSubCauseCode, text_RoadworksSubCauseCode);
        type_ann_builtin_RoadworksSubCauseCode = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_RoadworksSubCauseCode);

        if (!tmp_ann_custom_RoadworksSubCauseCode.empty())
        {
            ann_custom_RoadworksSubCauseCode = tmp_ann_custom_RoadworksSubCauseCode;
        }

        CompleteTypeDetail detail_RoadworksSubCauseCode = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_RoadworksSubCauseCode, ann_custom_RoadworksSubCauseCode, type_name_RoadworksSubCauseCode.to_string());
        CompleteStructHeader header_RoadworksSubCauseCode;
        header_RoadworksSubCauseCode = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_RoadworksSubCauseCode);
        CompleteStructMemberSeq member_seq_RoadworksSubCauseCode;
        {
            TypeIdentifierPair type_ids_value;
            ReturnCode_t return_code_value {eprosima::fastdds::dds::RETCODE_OK};
            return_code_value =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint8_t", type_ids_value);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_value)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "value Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_value = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_value = 0x00000000;
            bool common_value_ec {false};
            CommonStructMember common_value {TypeObjectUtils::build_common_struct_member(member_id_value, member_flags_value, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_value, common_value_ec))};
            if (!common_value_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure value member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_value = "value";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_value;
            ann_custom_RoadworksSubCauseCode.reset();
            AppliedAnnotationSeq tmp_ann_custom_value;
            eprosima::fastcdr::optional<std::string> unit_value;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_value;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_value;
            eprosima::fastcdr::optional<std::string> hash_id_value;
            if (unit_value.has_value() || min_value.has_value() || max_value.has_value() || hash_id_value.has_value())
            {
                member_ann_builtin_value = TypeObjectUtils::build_applied_builtin_member_annotations(unit_value, min_value, max_value, hash_id_value);
            }
            if (!tmp_ann_custom_value.empty())
            {
                ann_custom_RoadworksSubCauseCode = tmp_ann_custom_value;
            }
            CompleteMemberDetail detail_value = TypeObjectUtils::build_complete_member_detail(name_value, member_ann_builtin_value, ann_custom_RoadworksSubCauseCode);
            CompleteStructMember member_value = TypeObjectUtils::build_complete_struct_member(common_value, detail_value);
            TypeObjectUtils::add_complete_struct_member(member_seq_RoadworksSubCauseCode, member_value);
        }
        CompleteStructType struct_type_RoadworksSubCauseCode = TypeObjectUtils::build_complete_struct_type(struct_flags_RoadworksSubCauseCode, header_RoadworksSubCauseCode, member_seq_RoadworksSubCauseCode);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_RoadworksSubCauseCode, type_name_RoadworksSubCauseCode.to_string(), type_ids_RoadworksSubCauseCode))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "etsi_its_cam_msgs::msg::RoadworksSubCauseCode already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace etsi_its_cam_msgs

