// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RSUContainerHighFrequency.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_RSUCONTAINERHIGHFREQUENCY_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_RSUCONTAINERHIGHFREQUENCY_HPP

#include <cstdint>
#include <utility>
#include "ProtectedCommunicationZonesRSU.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RSUCONTAINERHIGHFREQUENCY_SOURCE)
#define RSUCONTAINERHIGHFREQUENCY_DllAPI __declspec( dllexport )
#else
#define RSUCONTAINERHIGHFREQUENCY_DllAPI __declspec( dllimport )
#endif // RSUCONTAINERHIGHFREQUENCY_SOURCE
#else
#define RSUCONTAINERHIGHFREQUENCY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RSUCONTAINERHIGHFREQUENCY_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure RSUContainerHighFrequency defined by the user in the IDL file.
 * @ingroup RSUContainerHighFrequency
 */
class RSUContainerHighFrequency
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport RSUContainerHighFrequency()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~RSUContainerHighFrequency()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object RSUContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport RSUContainerHighFrequency(
            const RSUContainerHighFrequency& x)
    {
                    m_protected_communication_zones_rsu = x.m_protected_communication_zones_rsu;

                    m_protected_communication_zones_rsu_is_present = x.m_protected_communication_zones_rsu_is_present;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object RSUContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport RSUContainerHighFrequency(
            RSUContainerHighFrequency&& x) noexcept
    {
        m_protected_communication_zones_rsu = std::move(x.m_protected_communication_zones_rsu);
        m_protected_communication_zones_rsu_is_present = x.m_protected_communication_zones_rsu_is_present;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object RSUContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport RSUContainerHighFrequency& operator =(
            const RSUContainerHighFrequency& x)
    {

                    m_protected_communication_zones_rsu = x.m_protected_communication_zones_rsu;

                    m_protected_communication_zones_rsu_is_present = x.m_protected_communication_zones_rsu_is_present;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object RSUContainerHighFrequency that will be copied.
     */
    eProsima_user_DllExport RSUContainerHighFrequency& operator =(
            RSUContainerHighFrequency&& x) noexcept
    {

        m_protected_communication_zones_rsu = std::move(x.m_protected_communication_zones_rsu);
        m_protected_communication_zones_rsu_is_present = x.m_protected_communication_zones_rsu_is_present;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x RSUContainerHighFrequency object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const RSUContainerHighFrequency& x) const
    {
        return (m_protected_communication_zones_rsu == x.m_protected_communication_zones_rsu &&
           m_protected_communication_zones_rsu_is_present == x.m_protected_communication_zones_rsu_is_present);
    }

    /*!
     * @brief Comparison operator.
     * @param x RSUContainerHighFrequency object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const RSUContainerHighFrequency& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member protected_communication_zones_rsu
     * @param _protected_communication_zones_rsu New value to be copied in member protected_communication_zones_rsu
     */
    eProsima_user_DllExport void protected_communication_zones_rsu(
            const ProtectedCommunicationZonesRSU& _protected_communication_zones_rsu)
    {
        m_protected_communication_zones_rsu = _protected_communication_zones_rsu;
    }

    /*!
     * @brief This function moves the value in member protected_communication_zones_rsu
     * @param _protected_communication_zones_rsu New value to be moved in member protected_communication_zones_rsu
     */
    eProsima_user_DllExport void protected_communication_zones_rsu(
            ProtectedCommunicationZonesRSU&& _protected_communication_zones_rsu)
    {
        m_protected_communication_zones_rsu = std::move(_protected_communication_zones_rsu);
    }

    /*!
     * @brief This function returns a constant reference to member protected_communication_zones_rsu
     * @return Constant reference to member protected_communication_zones_rsu
     */
    eProsima_user_DllExport const ProtectedCommunicationZonesRSU& protected_communication_zones_rsu() const
    {
        return m_protected_communication_zones_rsu;
    }

    /*!
     * @brief This function returns a reference to member protected_communication_zones_rsu
     * @return Reference to member protected_communication_zones_rsu
     */
    eProsima_user_DllExport ProtectedCommunicationZonesRSU& protected_communication_zones_rsu()
    {
        return m_protected_communication_zones_rsu;
    }


    /*!
     * @brief This function sets a value in member protected_communication_zones_rsu_is_present
     * @param _protected_communication_zones_rsu_is_present New value for member protected_communication_zones_rsu_is_present
     */
    eProsima_user_DllExport void protected_communication_zones_rsu_is_present(
            bool _protected_communication_zones_rsu_is_present)
    {
        m_protected_communication_zones_rsu_is_present = _protected_communication_zones_rsu_is_present;
    }

    /*!
     * @brief This function returns the value of member protected_communication_zones_rsu_is_present
     * @return Value of member protected_communication_zones_rsu_is_present
     */
    eProsima_user_DllExport bool protected_communication_zones_rsu_is_present() const
    {
        return m_protected_communication_zones_rsu_is_present;
    }

    /*!
     * @brief This function returns a reference to member protected_communication_zones_rsu_is_present
     * @return Reference to member protected_communication_zones_rsu_is_present
     */
    eProsima_user_DllExport bool& protected_communication_zones_rsu_is_present()
    {
        return m_protected_communication_zones_rsu_is_present;
    }



private:

    ProtectedCommunicationZonesRSU m_protected_communication_zones_rsu;
    bool m_protected_communication_zones_rsu_is_present{false};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_RSUCONTAINERHIGHFREQUENCY_HPP_


