// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SpecialTransportContainer.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_SPECIALTRANSPORTCONTAINER_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_SPECIALTRANSPORTCONTAINER_HPP

#include <cstdint>
#include <utility>
#include "SpecialTransportType.hpp"
#include "LightBarSirenInUse.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SPECIALTRANSPORTCONTAINER_SOURCE)
#define SPECIALTRANSPORTCONTAINER_DllAPI __declspec( dllexport )
#else
#define SPECIALTRANSPORTCONTAINER_DllAPI __declspec( dllimport )
#endif // SPECIALTRANSPORTCONTAINER_SOURCE
#else
#define SPECIALTRANSPORTCONTAINER_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SPECIALTRANSPORTCONTAINER_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure SpecialTransportContainer defined by the user in the IDL file.
 * @ingroup SpecialTransportContainer
 */
class SpecialTransportContainer
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SpecialTransportContainer()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SpecialTransportContainer()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer(
            const SpecialTransportContainer& x)
    {
                    m_special_transport_type = x.m_special_transport_type;

                    m_light_bar_siren_in_use = x.m_light_bar_siren_in_use;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer(
            SpecialTransportContainer&& x) noexcept
    {
        m_special_transport_type = std::move(x.m_special_transport_type);
        m_light_bar_siren_in_use = std::move(x.m_light_bar_siren_in_use);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer& operator =(
            const SpecialTransportContainer& x)
    {

                    m_special_transport_type = x.m_special_transport_type;

                    m_light_bar_siren_in_use = x.m_light_bar_siren_in_use;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer& operator =(
            SpecialTransportContainer&& x) noexcept
    {

        m_special_transport_type = std::move(x.m_special_transport_type);
        m_light_bar_siren_in_use = std::move(x.m_light_bar_siren_in_use);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SpecialTransportContainer object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SpecialTransportContainer& x) const
    {
        return (m_special_transport_type == x.m_special_transport_type &&
           m_light_bar_siren_in_use == x.m_light_bar_siren_in_use);
    }

    /*!
     * @brief Comparison operator.
     * @param x SpecialTransportContainer object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SpecialTransportContainer& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member special_transport_type
     * @param _special_transport_type New value to be copied in member special_transport_type
     */
    eProsima_user_DllExport void special_transport_type(
            const SpecialTransportType& _special_transport_type)
    {
        m_special_transport_type = _special_transport_type;
    }

    /*!
     * @brief This function moves the value in member special_transport_type
     * @param _special_transport_type New value to be moved in member special_transport_type
     */
    eProsima_user_DllExport void special_transport_type(
            SpecialTransportType&& _special_transport_type)
    {
        m_special_transport_type = std::move(_special_transport_type);
    }

    /*!
     * @brief This function returns a constant reference to member special_transport_type
     * @return Constant reference to member special_transport_type
     */
    eProsima_user_DllExport const SpecialTransportType& special_transport_type() const
    {
        return m_special_transport_type;
    }

    /*!
     * @brief This function returns a reference to member special_transport_type
     * @return Reference to member special_transport_type
     */
    eProsima_user_DllExport SpecialTransportType& special_transport_type()
    {
        return m_special_transport_type;
    }


    /*!
     * @brief This function copies the value in member light_bar_siren_in_use
     * @param _light_bar_siren_in_use New value to be copied in member light_bar_siren_in_use
     */
    eProsima_user_DllExport void light_bar_siren_in_use(
            const LightBarSirenInUse& _light_bar_siren_in_use)
    {
        m_light_bar_siren_in_use = _light_bar_siren_in_use;
    }

    /*!
     * @brief This function moves the value in member light_bar_siren_in_use
     * @param _light_bar_siren_in_use New value to be moved in member light_bar_siren_in_use
     */
    eProsima_user_DllExport void light_bar_siren_in_use(
            LightBarSirenInUse&& _light_bar_siren_in_use)
    {
        m_light_bar_siren_in_use = std::move(_light_bar_siren_in_use);
    }

    /*!
     * @brief This function returns a constant reference to member light_bar_siren_in_use
     * @return Constant reference to member light_bar_siren_in_use
     */
    eProsima_user_DllExport const LightBarSirenInUse& light_bar_siren_in_use() const
    {
        return m_light_bar_siren_in_use;
    }

    /*!
     * @brief This function returns a reference to member light_bar_siren_in_use
     * @return Reference to member light_bar_siren_in_use
     */
    eProsima_user_DllExport LightBarSirenInUse& light_bar_siren_in_use()
    {
        return m_light_bar_siren_in_use;
    }



private:

    SpecialTransportType m_special_transport_type;
    LightBarSirenInUse m_light_bar_siren_in_use;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPECIALTRANSPORTCONTAINER_HPP_


