// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SpeedTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "SpeedTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Speed.hpp"

#include "SpeedValue.hpp"
#include "SpeedConfidence.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace etsi_its_cam_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Speed_type_identifier(
        TypeIdentifierPair& type_ids_Speed)
{

    ReturnCode_t return_code_Speed {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Speed =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "etsi_its_cam_msgs::msg::dds_::Speed_", type_ids_Speed);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Speed)
    {
        StructTypeFlag struct_flags_Speed = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Speed = "etsi_its_cam_msgs::msg::dds_::Speed_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Speed;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Speed;
        AppliedAnnotationSeq tmp_ann_custom_Speed;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_Speed;
        PlacementKind placement_Speed = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_Speed = "*";
        std::string text_Speed;
        language_Speed = "comment";

        placement_Speed = PlacementKind::BEFORE_DECLARATION;

        text_Speed = "==============================================================================\nMIT License\n\nCopyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n==============================================================================";

        verbatim_Speed = TypeObjectUtils::build_applied_verbatim_annotation(placement_Speed, language_Speed, text_Speed);
        type_ann_builtin_Speed = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_Speed);

        if (!tmp_ann_custom_Speed.empty())
        {
            ann_custom_Speed = tmp_ann_custom_Speed;
        }

        CompleteTypeDetail detail_Speed = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Speed, ann_custom_Speed, type_name_Speed.to_string());
        CompleteStructHeader header_Speed;
        header_Speed = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Speed);
        CompleteStructMemberSeq member_seq_Speed;
        {
            TypeIdentifierPair type_ids_speed_value;
            ReturnCode_t return_code_speed_value {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed_value =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::SpeedValue_", type_ids_speed_value);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed_value)
            {
                etsi_its_cam_msgs::msg::register_SpeedValue_type_identifier(type_ids_speed_value);
            }
            StructMemberFlag member_flags_speed_value = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed_value = 0x00000000;
            bool common_speed_value_ec {false};
            CommonStructMember common_speed_value {TypeObjectUtils::build_common_struct_member(member_id_speed_value, member_flags_speed_value, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed_value, common_speed_value_ec))};
            if (!common_speed_value_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed_value member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed_value = "speed_value";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed_value;
            ann_custom_Speed.reset();
            AppliedAnnotationSeq tmp_ann_custom_speed_value;
            eprosima::fastcdr::optional<std::string> unit_speed_value;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_speed_value;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_speed_value;
            eprosima::fastcdr::optional<std::string> hash_id_speed_value;
            if (unit_speed_value.has_value() || min_speed_value.has_value() || max_speed_value.has_value() || hash_id_speed_value.has_value())
            {
                member_ann_builtin_speed_value = TypeObjectUtils::build_applied_builtin_member_annotations(unit_speed_value, min_speed_value, max_speed_value, hash_id_speed_value);
            }
            if (!tmp_ann_custom_speed_value.empty())
            {
                ann_custom_Speed = tmp_ann_custom_speed_value;
            }
            CompleteMemberDetail detail_speed_value = TypeObjectUtils::build_complete_member_detail(name_speed_value, member_ann_builtin_speed_value, ann_custom_Speed);
            CompleteStructMember member_speed_value = TypeObjectUtils::build_complete_struct_member(common_speed_value, detail_speed_value);
            TypeObjectUtils::add_complete_struct_member(member_seq_Speed, member_speed_value);
        }
        {
            TypeIdentifierPair type_ids_speed_confidence;
            ReturnCode_t return_code_speed_confidence {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed_confidence =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "etsi_its_cam_msgs::msg::dds_::SpeedConfidence_", type_ids_speed_confidence);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed_confidence)
            {
                etsi_its_cam_msgs::msg::register_SpeedConfidence_type_identifier(type_ids_speed_confidence);
            }
            StructMemberFlag member_flags_speed_confidence = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed_confidence = 0x00000001;
            bool common_speed_confidence_ec {false};
            CommonStructMember common_speed_confidence {TypeObjectUtils::build_common_struct_member(member_id_speed_confidence, member_flags_speed_confidence, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed_confidence, common_speed_confidence_ec))};
            if (!common_speed_confidence_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed_confidence member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed_confidence = "speed_confidence";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed_confidence;
            ann_custom_Speed.reset();
            CompleteMemberDetail detail_speed_confidence = TypeObjectUtils::build_complete_member_detail(name_speed_confidence, member_ann_builtin_speed_confidence, ann_custom_Speed);
            CompleteStructMember member_speed_confidence = TypeObjectUtils::build_complete_struct_member(common_speed_confidence, detail_speed_confidence);
            TypeObjectUtils::add_complete_struct_member(member_seq_Speed, member_speed_confidence);
        }
        CompleteStructType struct_type_Speed = TypeObjectUtils::build_complete_struct_type(struct_flags_Speed, header_Speed, member_seq_Speed);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Speed, type_name_Speed.to_string(), type_ids_Speed))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "etsi_its_cam_msgs::msg::Speed already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace etsi_its_cam_msgs

