// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Speed.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_SPEED_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_SPEED_HPP

#include <cstdint>
#include <utility>
#include "SpeedValue.hpp"
#include "SpeedConfidence.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SPEED_SOURCE)
#define SPEED_DllAPI __declspec( dllexport )
#else
#define SPEED_DllAPI __declspec( dllimport )
#endif // SPEED_SOURCE
#else
#define SPEED_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SPEED_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Speed defined by the user in the IDL file.
 * @ingroup Speed
 */
class Speed
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Speed()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Speed()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Speed that will be copied.
     */
    eProsima_user_DllExport Speed(
            const Speed& x)
    {
                    m_speed_value = x.m_speed_value;

                    m_speed_confidence = x.m_speed_confidence;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Speed that will be copied.
     */
    eProsima_user_DllExport Speed(
            Speed&& x) noexcept
    {
        m_speed_value = std::move(x.m_speed_value);
        m_speed_confidence = std::move(x.m_speed_confidence);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Speed that will be copied.
     */
    eProsima_user_DllExport Speed& operator =(
            const Speed& x)
    {

                    m_speed_value = x.m_speed_value;

                    m_speed_confidence = x.m_speed_confidence;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Speed that will be copied.
     */
    eProsima_user_DllExport Speed& operator =(
            Speed&& x) noexcept
    {

        m_speed_value = std::move(x.m_speed_value);
        m_speed_confidence = std::move(x.m_speed_confidence);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Speed object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Speed& x) const
    {
        return (m_speed_value == x.m_speed_value &&
           m_speed_confidence == x.m_speed_confidence);
    }

    /*!
     * @brief Comparison operator.
     * @param x Speed object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Speed& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member speed_value
     * @param _speed_value New value to be copied in member speed_value
     */
    eProsima_user_DllExport void speed_value(
            const SpeedValue& _speed_value)
    {
        m_speed_value = _speed_value;
    }

    /*!
     * @brief This function moves the value in member speed_value
     * @param _speed_value New value to be moved in member speed_value
     */
    eProsima_user_DllExport void speed_value(
            SpeedValue&& _speed_value)
    {
        m_speed_value = std::move(_speed_value);
    }

    /*!
     * @brief This function returns a constant reference to member speed_value
     * @return Constant reference to member speed_value
     */
    eProsima_user_DllExport const SpeedValue& speed_value() const
    {
        return m_speed_value;
    }

    /*!
     * @brief This function returns a reference to member speed_value
     * @return Reference to member speed_value
     */
    eProsima_user_DllExport SpeedValue& speed_value()
    {
        return m_speed_value;
    }


    /*!
     * @brief This function copies the value in member speed_confidence
     * @param _speed_confidence New value to be copied in member speed_confidence
     */
    eProsima_user_DllExport void speed_confidence(
            const SpeedConfidence& _speed_confidence)
    {
        m_speed_confidence = _speed_confidence;
    }

    /*!
     * @brief This function moves the value in member speed_confidence
     * @param _speed_confidence New value to be moved in member speed_confidence
     */
    eProsima_user_DllExport void speed_confidence(
            SpeedConfidence&& _speed_confidence)
    {
        m_speed_confidence = std::move(_speed_confidence);
    }

    /*!
     * @brief This function returns a constant reference to member speed_confidence
     * @return Constant reference to member speed_confidence
     */
    eProsima_user_DllExport const SpeedConfidence& speed_confidence() const
    {
        return m_speed_confidence;
    }

    /*!
     * @brief This function returns a reference to member speed_confidence
     * @return Reference to member speed_confidence
     */
    eProsima_user_DllExport SpeedConfidence& speed_confidence()
    {
        return m_speed_confidence;
    }



private:

    SpeedValue m_speed_value;
    SpeedConfidence m_speed_confidence;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPEED_HPP_


