// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SpeedLimit.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_SPEEDLIMIT_HPP
#define FAST_DDS_GENERATED__ETSI_ITS_CAM_MSGS_MSG_SPEEDLIMIT_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SPEEDLIMIT_SOURCE)
#define SPEEDLIMIT_DllAPI __declspec( dllexport )
#else
#define SPEEDLIMIT_DllAPI __declspec( dllimport )
#endif // SPEEDLIMIT_SOURCE
#else
#define SPEEDLIMIT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SPEEDLIMIT_DllAPI
#endif // _WIN32

namespace etsi_its_cam_msgs {

namespace msg {

namespace SpeedLimit_Constants {

const uint8_t MIN = 1;
const uint8_t MAX = 255;
const uint8_t ONE_KM_PER_HOUR = 1;

} // namespace SpeedLimit_Constants
/*!
 * @brief This class represents the structure SpeedLimit defined by the user in the IDL file.
 * @ingroup SpeedLimit
 */
class SpeedLimit
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SpeedLimit()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SpeedLimit()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SpeedLimit that will be copied.
     */
    eProsima_user_DllExport SpeedLimit(
            const SpeedLimit& x)
    {
                    m_value = x.m_value;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SpeedLimit that will be copied.
     */
    eProsima_user_DllExport SpeedLimit(
            SpeedLimit&& x) noexcept
    {
        m_value = x.m_value;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SpeedLimit that will be copied.
     */
    eProsima_user_DllExport SpeedLimit& operator =(
            const SpeedLimit& x)
    {

                    m_value = x.m_value;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SpeedLimit that will be copied.
     */
    eProsima_user_DllExport SpeedLimit& operator =(
            SpeedLimit&& x) noexcept
    {

        m_value = x.m_value;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SpeedLimit object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SpeedLimit& x) const
    {
        return (m_value == x.m_value);
    }

    /*!
     * @brief Comparison operator.
     * @param x SpeedLimit object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SpeedLimit& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            uint8_t _value)
    {
        m_value = _value;
    }

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport uint8_t value() const
    {
        return m_value;
    }

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport uint8_t& value()
    {
        return m_value;
    }



private:

    uint8_t m_value{0};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPEEDLIMIT_HPP_


