// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AckermannDriveTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "AckermannDriveTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "AckermannDrive.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace ackermann_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_AckermannDrive_type_identifier(
        TypeIdentifierPair& type_ids_AckermannDrive)
{

    ReturnCode_t return_code_AckermannDrive {eprosima::fastdds::dds::RETCODE_OK};
    return_code_AckermannDrive =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "ackermann_msgs::msg::dds_::AckermannDrive_", type_ids_AckermannDrive);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_AckermannDrive)
    {
        StructTypeFlag struct_flags_AckermannDrive = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_AckermannDrive = "ackermann_msgs::msg::dds_::AckermannDrive_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_AckermannDrive;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_AckermannDrive;
        AppliedAnnotationSeq tmp_ann_custom_AckermannDrive;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_AckermannDrive;
        PlacementKind placement_AckermannDrive = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_AckermannDrive = "*";
        std::string text_AckermannDrive;
        language_AckermannDrive = "comment";

        placement_AckermannDrive = PlacementKind::BEFORE_DECLARATION;

        text_AckermannDrive = "Driving command for a car-like vehicle using Ackermann steering.\n $Id$";

        verbatim_AckermannDrive = TypeObjectUtils::build_applied_verbatim_annotation(placement_AckermannDrive, language_AckermannDrive, text_AckermannDrive);
        type_ann_builtin_AckermannDrive = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_AckermannDrive);

        if (!tmp_ann_custom_AckermannDrive.empty())
        {
            ann_custom_AckermannDrive = tmp_ann_custom_AckermannDrive;
        }

        CompleteTypeDetail detail_AckermannDrive = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_AckermannDrive, ann_custom_AckermannDrive, type_name_AckermannDrive.to_string());
        CompleteStructHeader header_AckermannDrive;
        header_AckermannDrive = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_AckermannDrive);
        CompleteStructMemberSeq member_seq_AckermannDrive;
        {
            TypeIdentifierPair type_ids_steering_angle;
            ReturnCode_t return_code_steering_angle {eprosima::fastdds::dds::RETCODE_OK};
            return_code_steering_angle =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_steering_angle);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_steering_angle)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "steering_angle Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_steering_angle = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_steering_angle = 0x00000000;
            bool common_steering_angle_ec {false};
            CommonStructMember common_steering_angle {TypeObjectUtils::build_common_struct_member(member_id_steering_angle, member_flags_steering_angle, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_steering_angle, common_steering_angle_ec))};
            if (!common_steering_angle_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure steering_angle member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_steering_angle = "steering_angle";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_steering_angle;
            ann_custom_AckermannDrive.reset();
            AppliedAnnotationSeq tmp_ann_custom_steering_angle;
            eprosima::fastcdr::optional<std::string> unit_steering_angle;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_steering_angle;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_steering_angle;
            eprosima::fastcdr::optional<std::string> hash_id_steering_angle;
            if (unit_steering_angle.has_value() || min_steering_angle.has_value() || max_steering_angle.has_value() || hash_id_steering_angle.has_value())
            {
                member_ann_builtin_steering_angle = TypeObjectUtils::build_applied_builtin_member_annotations(unit_steering_angle, min_steering_angle, max_steering_angle, hash_id_steering_angle);
            }
            if (!tmp_ann_custom_steering_angle.empty())
            {
                ann_custom_AckermannDrive = tmp_ann_custom_steering_angle;
            }
            CompleteMemberDetail detail_steering_angle = TypeObjectUtils::build_complete_member_detail(name_steering_angle, member_ann_builtin_steering_angle, ann_custom_AckermannDrive);
            CompleteStructMember member_steering_angle = TypeObjectUtils::build_complete_struct_member(common_steering_angle, detail_steering_angle);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDrive, member_steering_angle);
        }
        {
            TypeIdentifierPair type_ids_steering_angle_velocity;
            ReturnCode_t return_code_steering_angle_velocity {eprosima::fastdds::dds::RETCODE_OK};
            return_code_steering_angle_velocity =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_steering_angle_velocity);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_steering_angle_velocity)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "steering_angle_velocity Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_steering_angle_velocity = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_steering_angle_velocity = 0x00000001;
            bool common_steering_angle_velocity_ec {false};
            CommonStructMember common_steering_angle_velocity {TypeObjectUtils::build_common_struct_member(member_id_steering_angle_velocity, member_flags_steering_angle_velocity, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_steering_angle_velocity, common_steering_angle_velocity_ec))};
            if (!common_steering_angle_velocity_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure steering_angle_velocity member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_steering_angle_velocity = "steering_angle_velocity";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_steering_angle_velocity;
            ann_custom_AckermannDrive.reset();
            AppliedAnnotationSeq tmp_ann_custom_steering_angle_velocity;
            eprosima::fastcdr::optional<std::string> unit_steering_angle_velocity;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_steering_angle_velocity;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_steering_angle_velocity;
            eprosima::fastcdr::optional<std::string> hash_id_steering_angle_velocity;
            if (unit_steering_angle_velocity.has_value() || min_steering_angle_velocity.has_value() || max_steering_angle_velocity.has_value() || hash_id_steering_angle_velocity.has_value())
            {
                member_ann_builtin_steering_angle_velocity = TypeObjectUtils::build_applied_builtin_member_annotations(unit_steering_angle_velocity, min_steering_angle_velocity, max_steering_angle_velocity, hash_id_steering_angle_velocity);
            }
            if (!tmp_ann_custom_steering_angle_velocity.empty())
            {
                ann_custom_AckermannDrive = tmp_ann_custom_steering_angle_velocity;
            }
            CompleteMemberDetail detail_steering_angle_velocity = TypeObjectUtils::build_complete_member_detail(name_steering_angle_velocity, member_ann_builtin_steering_angle_velocity, ann_custom_AckermannDrive);
            CompleteStructMember member_steering_angle_velocity = TypeObjectUtils::build_complete_struct_member(common_steering_angle_velocity, detail_steering_angle_velocity);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDrive, member_steering_angle_velocity);
        }
        {
            TypeIdentifierPair type_ids_speed;
            ReturnCode_t return_code_speed {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_speed);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed = 0x00000002;
            bool common_speed_ec {false};
            CommonStructMember common_speed {TypeObjectUtils::build_common_struct_member(member_id_speed, member_flags_speed, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed, common_speed_ec))};
            if (!common_speed_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed = "speed";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed;
            ann_custom_AckermannDrive.reset();
            AppliedAnnotationSeq tmp_ann_custom_speed;
            eprosima::fastcdr::optional<std::string> unit_speed;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_speed;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_speed;
            eprosima::fastcdr::optional<std::string> hash_id_speed;
            if (unit_speed.has_value() || min_speed.has_value() || max_speed.has_value() || hash_id_speed.has_value())
            {
                member_ann_builtin_speed = TypeObjectUtils::build_applied_builtin_member_annotations(unit_speed, min_speed, max_speed, hash_id_speed);
            }
            if (!tmp_ann_custom_speed.empty())
            {
                ann_custom_AckermannDrive = tmp_ann_custom_speed;
            }
            CompleteMemberDetail detail_speed = TypeObjectUtils::build_complete_member_detail(name_speed, member_ann_builtin_speed, ann_custom_AckermannDrive);
            CompleteStructMember member_speed = TypeObjectUtils::build_complete_struct_member(common_speed, detail_speed);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDrive, member_speed);
        }
        {
            TypeIdentifierPair type_ids_acceleration;
            ReturnCode_t return_code_acceleration {eprosima::fastdds::dds::RETCODE_OK};
            return_code_acceleration =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_acceleration);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_acceleration)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "acceleration Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_acceleration = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_acceleration = 0x00000003;
            bool common_acceleration_ec {false};
            CommonStructMember common_acceleration {TypeObjectUtils::build_common_struct_member(member_id_acceleration, member_flags_acceleration, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_acceleration, common_acceleration_ec))};
            if (!common_acceleration_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure acceleration member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_acceleration = "acceleration";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_acceleration;
            ann_custom_AckermannDrive.reset();
            AppliedAnnotationSeq tmp_ann_custom_acceleration;
            eprosima::fastcdr::optional<std::string> unit_acceleration;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_acceleration;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_acceleration;
            eprosima::fastcdr::optional<std::string> hash_id_acceleration;
            if (unit_acceleration.has_value() || min_acceleration.has_value() || max_acceleration.has_value() || hash_id_acceleration.has_value())
            {
                member_ann_builtin_acceleration = TypeObjectUtils::build_applied_builtin_member_annotations(unit_acceleration, min_acceleration, max_acceleration, hash_id_acceleration);
            }
            if (!tmp_ann_custom_acceleration.empty())
            {
                ann_custom_AckermannDrive = tmp_ann_custom_acceleration;
            }
            CompleteMemberDetail detail_acceleration = TypeObjectUtils::build_complete_member_detail(name_acceleration, member_ann_builtin_acceleration, ann_custom_AckermannDrive);
            CompleteStructMember member_acceleration = TypeObjectUtils::build_complete_struct_member(common_acceleration, detail_acceleration);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDrive, member_acceleration);
        }
        {
            TypeIdentifierPair type_ids_jerk;
            ReturnCode_t return_code_jerk {eprosima::fastdds::dds::RETCODE_OK};
            return_code_jerk =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_jerk);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_jerk)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "jerk Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_jerk = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_jerk = 0x00000004;
            bool common_jerk_ec {false};
            CommonStructMember common_jerk {TypeObjectUtils::build_common_struct_member(member_id_jerk, member_flags_jerk, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_jerk, common_jerk_ec))};
            if (!common_jerk_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure jerk member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_jerk = "jerk";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_jerk;
            ann_custom_AckermannDrive.reset();
            AppliedAnnotationSeq tmp_ann_custom_jerk;
            eprosima::fastcdr::optional<std::string> unit_jerk;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_jerk;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_jerk;
            eprosima::fastcdr::optional<std::string> hash_id_jerk;
            if (unit_jerk.has_value() || min_jerk.has_value() || max_jerk.has_value() || hash_id_jerk.has_value())
            {
                member_ann_builtin_jerk = TypeObjectUtils::build_applied_builtin_member_annotations(unit_jerk, min_jerk, max_jerk, hash_id_jerk);
            }
            if (!tmp_ann_custom_jerk.empty())
            {
                ann_custom_AckermannDrive = tmp_ann_custom_jerk;
            }
            CompleteMemberDetail detail_jerk = TypeObjectUtils::build_complete_member_detail(name_jerk, member_ann_builtin_jerk, ann_custom_AckermannDrive);
            CompleteStructMember member_jerk = TypeObjectUtils::build_complete_struct_member(common_jerk, detail_jerk);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDrive, member_jerk);
        }
        CompleteStructType struct_type_AckermannDrive = TypeObjectUtils::build_complete_struct_type(struct_flags_AckermannDrive, header_AckermannDrive, member_seq_AckermannDrive);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_AckermannDrive, type_name_AckermannDrive.to_string(), type_ids_AckermannDrive))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "ackermann_msgs::msg::AckermannDrive already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace ackermann_msgs

