// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AckermannDriveStampedTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#include "AckermannDriveStampedTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "AckermannDriveStamped.hpp"

#include "AckermannDrive.hpp"
#include "std_msgs/msg/Header.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace ackermann_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_AckermannDriveStamped_type_identifier(
        TypeIdentifierPair& type_ids_AckermannDriveStamped)
{

    ReturnCode_t return_code_AckermannDriveStamped {eprosima::fastdds::dds::RETCODE_OK};
    return_code_AckermannDriveStamped =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "ackermann_msgs::msg::dds_::AckermannDriveStamped_", type_ids_AckermannDriveStamped);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_AckermannDriveStamped)
    {
        StructTypeFlag struct_flags_AckermannDriveStamped = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_AckermannDriveStamped = "ackermann_msgs::msg::dds_::AckermannDriveStamped_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_AckermannDriveStamped;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_AckermannDriveStamped;
        AppliedAnnotationSeq tmp_ann_custom_AckermannDriveStamped;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_AckermannDriveStamped;
        PlacementKind placement_AckermannDriveStamped = PlacementKind::BEFORE_DECLARATION;
        eprosima::fastcdr::fixed_string<32> language_AckermannDriveStamped = "*";
        std::string text_AckermannDriveStamped;
        language_AckermannDriveStamped = "comment";

        placement_AckermannDriveStamped = PlacementKind::BEFORE_DECLARATION;

        text_AckermannDriveStamped = "Time stamped drive command for robots with Ackermann steering.\n $Id$";

        verbatim_AckermannDriveStamped = TypeObjectUtils::build_applied_verbatim_annotation(placement_AckermannDriveStamped, language_AckermannDriveStamped, text_AckermannDriveStamped);
        type_ann_builtin_AckermannDriveStamped = TypeObjectUtils::build_applied_builtin_type_annotations(verbatim_AckermannDriveStamped);

        if (!tmp_ann_custom_AckermannDriveStamped.empty())
        {
            ann_custom_AckermannDriveStamped = tmp_ann_custom_AckermannDriveStamped;
        }

        CompleteTypeDetail detail_AckermannDriveStamped = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_AckermannDriveStamped, ann_custom_AckermannDriveStamped, type_name_AckermannDriveStamped.to_string());
        CompleteStructHeader header_AckermannDriveStamped;
        header_AckermannDriveStamped = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_AckermannDriveStamped);
        CompleteStructMemberSeq member_seq_AckermannDriveStamped;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "std_msgs::msg::dds_::Header_", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                std_msgs::msg::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_AckermannDriveStamped.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_AckermannDriveStamped);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDriveStamped, member_header);
        }
        {
            TypeIdentifierPair type_ids_drive;
            ReturnCode_t return_code_drive {eprosima::fastdds::dds::RETCODE_OK};
            return_code_drive =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "ackermann_msgs::msg::dds_::AckermannDrive_", type_ids_drive);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_drive)
            {
                ackermann_msgs::msg::register_AckermannDrive_type_identifier(type_ids_drive);
            }
            StructMemberFlag member_flags_drive = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_drive = 0x00000001;
            bool common_drive_ec {false};
            CommonStructMember common_drive {TypeObjectUtils::build_common_struct_member(member_id_drive, member_flags_drive, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_drive, common_drive_ec))};
            if (!common_drive_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure drive member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_drive = "drive";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_drive;
            ann_custom_AckermannDriveStamped.reset();
            CompleteMemberDetail detail_drive = TypeObjectUtils::build_complete_member_detail(name_drive, member_ann_builtin_drive, ann_custom_AckermannDriveStamped);
            CompleteStructMember member_drive = TypeObjectUtils::build_complete_struct_member(common_drive, detail_drive);
            TypeObjectUtils::add_complete_struct_member(member_seq_AckermannDriveStamped, member_drive);
        }
        CompleteStructType struct_type_AckermannDriveStamped = TypeObjectUtils::build_complete_struct_type(struct_flags_AckermannDriveStamped, header_AckermannDriveStamped, member_seq_AckermannDriveStamped);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_AckermannDriveStamped, type_name_AckermannDriveStamped.to_string(), type_ids_AckermannDriveStamped))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "ackermann_msgs::msg::AckermannDriveStamped already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace ackermann_msgs

