// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AckermannDriveStamped.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.0.5).
 */

#ifndef FAST_DDS_GENERATED__ACKERMANN_MSGS_MSG_ACKERMANNDRIVESTAMPED_HPP
#define FAST_DDS_GENERATED__ACKERMANN_MSGS_MSG_ACKERMANNDRIVESTAMPED_HPP

#include <cstdint>
#include <utility>
#include "AckermannDrive.hpp"
#include "std_msgs/msg/Header.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ACKERMANNDRIVESTAMPED_SOURCE)
#define ACKERMANNDRIVESTAMPED_DllAPI __declspec( dllexport )
#else
#define ACKERMANNDRIVESTAMPED_DllAPI __declspec( dllimport )
#endif // ACKERMANNDRIVESTAMPED_SOURCE
#else
#define ACKERMANNDRIVESTAMPED_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ACKERMANNDRIVESTAMPED_DllAPI
#endif // _WIN32

namespace ackermann_msgs {

namespace msg {

/*!
 * @brief This class represents the structure AckermannDriveStamped defined by the user in the IDL file.
 * @ingroup AckermannDriveStamped
 */
class AckermannDriveStamped
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AckermannDriveStamped()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AckermannDriveStamped()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AckermannDriveStamped that will be copied.
     */
    eProsima_user_DllExport AckermannDriveStamped(
            const AckermannDriveStamped& x)
    {
                    m_header = x.m_header;

                    m_drive = x.m_drive;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AckermannDriveStamped that will be copied.
     */
    eProsima_user_DllExport AckermannDriveStamped(
            AckermannDriveStamped&& x) noexcept
    {
        m_header = std::move(x.m_header);
        m_drive = std::move(x.m_drive);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AckermannDriveStamped that will be copied.
     */
    eProsima_user_DllExport AckermannDriveStamped& operator =(
            const AckermannDriveStamped& x)
    {

                    m_header = x.m_header;

                    m_drive = x.m_drive;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AckermannDriveStamped that will be copied.
     */
    eProsima_user_DllExport AckermannDriveStamped& operator =(
            AckermannDriveStamped&& x) noexcept
    {

        m_header = std::move(x.m_header);
        m_drive = std::move(x.m_drive);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AckermannDriveStamped object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AckermannDriveStamped& x) const
    {
        return (m_header == x.m_header &&
           m_drive == x.m_drive);
    }

    /*!
     * @brief Comparison operator.
     * @param x AckermannDriveStamped object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AckermannDriveStamped& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::Header& _header)
    {
        m_header = _header;
    }

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::Header&& _header)
    {
        m_header = std::move(_header);
    }

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::Header& header() const
    {
        return m_header;
    }

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::Header& header()
    {
        return m_header;
    }


    /*!
     * @brief This function copies the value in member drive
     * @param _drive New value to be copied in member drive
     */
    eProsima_user_DllExport void drive(
            const AckermannDrive& _drive)
    {
        m_drive = _drive;
    }

    /*!
     * @brief This function moves the value in member drive
     * @param _drive New value to be moved in member drive
     */
    eProsima_user_DllExport void drive(
            AckermannDrive&& _drive)
    {
        m_drive = std::move(_drive);
    }

    /*!
     * @brief This function returns a constant reference to member drive
     * @return Constant reference to member drive
     */
    eProsima_user_DllExport const AckermannDrive& drive() const
    {
        return m_drive;
    }

    /*!
     * @brief This function returns a reference to member drive
     * @return Reference to member drive
     */
    eProsima_user_DllExport AckermannDrive& drive()
    {
        return m_drive;
    }



private:

    std_msgs::msg::Header m_header;
    AckermannDrive m_drive;

};

} // namespace msg

} // namespace ackermann_msgs

#endif // _FAST_DDS_GENERATED_ACKERMANN_MSGS_MSG_ACKERMANNDRIVESTAMPED_HPP_


